### ISSUE TITLE
How can I build the files in layer folder by my own? 

### ISSUE THREAD

**Issue by byumjin** [KhronosGroup/Vulkan-ValidationLayers#1000]
Hello, 

I'm trying to fix issue #984. 
And, it seems like it conflicts with the files in `layers` [folder](https://github.com/KhronosGroup/Vulkan-ValidationLayers/tree/master/layers) already pre-built in this repository.
I want to build them by myself to test it, but I have no idea which command arguments are needed for CMake.

Is there anyone who knows how to build them?

Thank you.

**Comment by mark-lunarg** [comment]
@byumjin, we typically follow command-line process, and don't actively use or support the build-android cmake build process.  @ggfan and @cnorthrop are the authorities in this area.  Since there's already a lot of cross-posting between issue #984 and #985, lets track this in issue #984 so that everything is in one spot.  If you are talking about building for Linux or Windows, please correct me and we'll reopen this issue.  Thanks!
