### ISSUE TITLE
Draw state image layout check

### ISSUE THREAD

**Issue by iostrowsINTEL** [KhronosGroup/Vulkan-ValidationLayers#1064]
Hi,

there was a regression in the VK-GL-CTS, introduced here: https://github.com/KhronosGroup/VK-GL-CTS/commit/4301d73b33b2a793640939903bff9d9c9378ba5a, that validation layers could not spot.  

The change starts to use optimal layout instead of general in some cases, but does not adjust image layouts in descriptors.

Based on the test **dEQP-VK.descriptor_indexing.sampled_image**:
Sampled images in `VkDescriptorImageInfo` structures are declared to be used in layout `VK_IMAGE_LAYOUT_GENERAL`, but they are transitioned to `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL` layout before use.

**Comment by Tony-LunarG** [comment]
We currently cannot validate image layouts with partially bound descriptor sets because we cannot, from the CPU, know which array elements will be used as part of a draw.  We use gpu assisted validation to validate updated descriptors and out of bounds array accesses with partially bound descriptors, and it would be a good idea to add layout validation to that  code.  I've added layout validation with descriptor indexing to our list of gpu assisted validation todos here #852
Closing this since we're tracking the issue in #852  Thanks
