### ISSUE TITLE
Lack validation for imcompatible flag of VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR flag

### ISSUE THREAD

**Issue by zhaijialong** [KhronosGroup/Vulkan-ValidationLayers#1077]
Hi,

I have two descriptor set layout with basically same layouts, except for the `flag`. If the descriptor set layout used for creating pipeline layout has the flag `VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR `, while the descriptor set layout used for creating descriptor set doesn't,  there is no validaiton errors/warnings. And the driver will silently ignore the descriptor set when I bind it.

I'm using the validation layer from vulkan sdk 1.1.108, on Windows 10/ RTX 2060.

**Comment by mark-lunarg** [comment]
@zhaijialong, can you please share the spec text with this instance of valid usage?

**Comment by mark-lunarg** [comment]
@zhaijialong, apparently, this is not invalid behavior.  It may be intentional, or may be a hole in the Vulkan spec.  You may file an issue in [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs) to have this explained/fixed.  The best we can do without more explicit spec language is to add this to the Best Practices validation, and a reference to this issue has been added to the [BP tracking issue](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/24).  Thanks!
