### ISSUE TITLE
No more message codes

### ISSUE THREAD

**Issue by fduranleau-gl** [KhronosGroup/Vulkan-ValidationLayers#1160]
Back when `VK_LAYER_KHRONOS_validation` did not exist yet and was split in various layers, messages in debug report callback had message codes. Now, we always get message code 0 (it seems to be hardcoded this way in `log_msg` in `vk_layer_logging.h`). Thus, if we want to filter out some message types, we have to parse the message instead of just doing some simple integer comparisons with the code, which adds to the cost of logging.

Any reason why message codes where dropped?

**Comment by mark-lunarg** [comment]
@fduranleau-gl, I think it's been just over a year since we used numeric VUIDs.  There were a handful of reasons for the change, but the main reason is that the validation layers enforce the valid usage IDs defined in the specification, and in it they are defined as text strings.  Maintaining a consistent string-to-number mapping across many hundreds of specification changes was labor-intensive, error-prone, and unnecessarily confusing -- likely the same reasons numeric IDs were not used in the Vulkan specification.

BTW, if you are using the `VK_EXT_debug_report` extension, you will need to parse the message.  However, using the `VK_EXT_debug_utils` extension (which has superseded debug_report) will provide the VUID text in the `pMessageIdName `parameter of the debug callback.  You still have to do a string compare, but it might save you some trouble.

**Comment by krOoze** [comment]
What if we just returned some hash of the string?

**Comment by mark-lunarg** [comment]
There's likely not too much difference between the layer doing a hash at `log_msg()` time, and an application doing a string-compare.

**Comment by fduranleau-gl** [comment]
Except that if those VUID texts are constant, hashes can be precomputed offline.

**Comment by krOoze** [comment]
I think @mark-lunarg meant from convenience standpoint. Performance of measly hash does not matter that much when layers are on, and it would be paid only when actual error msg is reported, which matters even less.

**Comment by fduranleau-gl** [comment]
So I guess we close this issue, seems like there is no more to elaborare and/or suggest.

**Comment by mark-lunarg** [comment]
If this is purely for _convenience_, we can certainly create a hash for the VUID and pass it back in the messageIdNumber member of the callback, that is completely reasonable.  Does it matter what the hash function is?

**Comment by fduranleau-gl** [comment]
The intent was to try cut down on logging tax. If the validation layer would compute the hash at each call to `log_msg`, I see little point in doing so. Eventually we will migrate to use GL_EXT_debug_util, so we won't have to parse the message at that point.

**Comment by mark-lunarg** [comment]
Ah, OK.  Even if we precompute the hashes, we have to look up the hash value for the VUID string at log_msg time (or look up the string from the hash).  Thanks for your understanding.
