### ISSUE TITLE
vkCmdWriteTimestamp validation bugs, incorrect message

### ISSUE THREAD

**Issue by hrydgard** [KhronosGroup/Vulkan-ValidationLayers#1179]
This is with SDK 1.1.114.0.

I create a query pool like this: 
```
		#define MAX_TIMESTAMP_QUERIES 256
		VkQueryPoolCreateInfo query_ci{ VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO };
		query_ci.queryCount = MAX_TIMESTAMP_QUERIES;
		query_ci.queryType = VK_QUERY_TYPE_TIMESTAMP;
		res = vkCreateQueryPool(vulkan_->GetDevice(), &query_ci, nullptr, &frameData_[i].timestampQueryPool_);

```

Then on the first frame I do this:
```
		vkCmdResetQueryPool(initCmd, frameData.timestampQueryPool_, 0, MAX_TIMESTAMP_QUERIES);
		vkCmdWriteTimestamp(initCmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, frameData.timestampQueryPool_, 0);
```

And I get the following validation error when submitting initCmd (together with another command buffer):

```ERROR(validation:0) vkCmdBeginQuery(): VkQueryPool 0x9[] and query 0: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.```

Not only is the pool reset, but I haven't even called ```vkCmdBeginQuery``` at all! I presume there's some shared code between the validation for ```vkCmdWriteTimestamp``` and ```vkCmdBeginQuery```, but logging the wrong function name is not right.

With validation disabled, the code runs and works perfectly.

**Comment by jzulauf-lunarg** [comment]
I've found the spot in the code where the incorrect entrypoint name is assumed and fixed this.  However, we have this exact case in our unit test suite, and the only way I can get it to produce (the now corrected) error message is with a *2nd* call to vkCmdWriteTimestamp at index 0.  I'll post a pull request with the fixed message, but cannot reproduce the other condition.

**Comment by hrydgard** [comment]
OK, I'll double check my code and create a repro or close as appropriate.

**Comment by jzulauf-lunarg** [comment]
@hrydgard -- pushed a branch with the naming fixes...

**Comment by mikhailov-work** [comment]
I seem to be getting a similar issue. If I Reset a pool full of timestamps right after a successful GetResults, then I get validation errors next time I try to use the pool. However if I Reset it right before using it, then the errors disappear. I'm trying to issue the Reset call as early as possible (presumably that's favorable to the driver?) so I think the issue may be that the Reset happens in a different command buffer and submit than the WriteTimestamp call to that buffer. To be clear, I'm doing something like this:

Frame N:
- GetResults of query pool for N-1
- Reset pool for N-1
- WriteTimestamp calls for N
- Submit
-> This yields validation errors

if instead I do:

Frame N:
- GetResults of query pool for N-1
- Reset pool for N
- WriteTimestamp calls for N

Then the errors disappear. I would have thought the first version would be ok (obviously I reset all the pools to start with) since the Write just happens a frame after Reset. But perhaps the submit's are getting reordered somehow? 

Anyway if there is no performance penalty for "resetting right before writing" then I'll just do that, but it's still a bit confusing why the first version is "invalid"...

**Comment by mark-lunarg** [comment]
@jzulauf-lunarg, what's the current status of this issue, can it be closed?
