### ISSUE TITLE
VK_EXT_host_query_reset validation does not seem correct

### ISSUE THREAD

**Issue by Themaister** [KhronosGroup/Vulkan-ValidationLayers#1218]
I implemented this extension, and the validation layers appear to support this extension, but it doesn't seem to flag queries as being reset when I call vkResetQueryPoolEXT. Is this expected behavior?

**Comment by mark-lunarg** [comment]
PR #1062 probably has relevant information.

**Comment by Themaister** [comment]
```
For example, if a query is reset from the host using vkResetQueryPoolEXT(), then work is submitted to a queue beginning and ending this query, then vkGetQueryPoolResults() is called using the wait bit without waiting for the queue or device to be idle, the validation layers would emit an error indicating the code is waiting on a query that has been reset and not issued. This error is spurious because what would happen is that the call to vkGetQueryPoolResults() succeeds after waiting until the GPU finishes the query and makes results available for it.
```
seems very similar to what I'm doing, was that PR supposed to fix these issues? I tried building master today and I'm seeing these kinds of error messages:
```
[ERROR]: [Vulkan]: Validation Error: vkCmdBeginQuery(): VkQueryPool 0x3f000000003f[] and query 24: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.
[ERROR]: [Vulkan]: Validation Error: vkCmdBeginQuery(): VkQueryPool 0x3f000000003f[] and query 25: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.
[ERROR]: [Vulkan]: Validation Error: vkCmdBeginQuery(): VkQueryPool 0x3f000000003f[] and query 26: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.
[ERROR]: [Vulkan]: Validation Error: vkCmdBeginQuery(): VkQueryPool 0x3f000000003f[] and query 27: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.
[ERROR]: [Vulkan]: Validation Error: vkCmdBeginQuery(): VkQueryPool 0x3f000000003f[] and query 28: query not reset. After query pool creation, each query must be reset before it is used. Queries must also be reset between uses.
```
Calling code is: https://github.com/Themaister/Granite/blob/5e5404c16dee81cc15be378c1fce6e34788805ea/vulkan/query_pool.cpp#L61.

I can't see anything obviously wrong with it, my old approach of calling vkCmdResetQueryPool of one element right before signaling the query worked fine without any validation error.

The flow of things is, a VkFence is waited for, then vkGetQueryPoolResults with WAIT_BIT (which shouldn't wait since I waited on the fence), then vkResetQueryPoolEXT is called right after to reset everything. The query is then reused.

**Comment by mark-lunarg** [comment]
We'll take a look!

**Comment by jzulauf-lunarg** [comment]
TRIAGE NOTES: 

This is a hole (or two) in our RetireWorkOnQueue logic.  Since `vkResetQueryPoolEXT` can (and in this case *does*) wait on query completion, the command functions similarly to `vkDeviceWaitIdle`, `vkQueueWaitIdle`, `vkWaitForFences` or `vkAcquireNextImageKHR` in that they provide information regarding execution synchronization with the queue the queries were submitted on.

Currently we aren't tracking the queue/sequence of query submissions in the query metadata, nor use that to update global query state with `RetireWorkOnQueue`

What is less clear is whether QUEUE_STATE::queryToStateMap is being correctly updated. It is both updated at Submit and RetireWork time, which seems contradictory. Submit time operations typically are used to track what subsequent Submissions would see as the value when executed, RetireWorkOnQueue could possibly "rewind" that value to an earlier state (for example waiting for a fence prior to the last query state change).  

Additionally, the interaction of vkResetQueryPoolEXT with the QUEUE_STATE needs careful attention.

**Comment by jzulauf-lunarg** [comment]
@Themaister  -- as a work-around, you should be able to wait on any fence subsequent to the EndQuery before resetting the queries to silence the error.  That's not optimal of course.

**Comment by locke-lunarg** [comment]
According to @Themaister response, the issue doesn't happen any longer. Closed.
