### ISSUE TITLE
Crash when using the VK_KHR_imageless_framebuffer extension

### ISSUE THREAD

**Issue by Jelly3D** [KhronosGroup/Vulkan-ValidationLayers#1256]
The framebuffer's VkFramebufferCreateInfo is filled with:
```
flags = VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT_KHR
attachmentCount = 1
pAttachments = nullptr
next = ptr to a VkFramebufferAttachmentsCreateInfoKHR with 1 attachment
```
Then at render time a ptr to a VkRenderPassAttachmentBeginInfoKHR containing the actual image view used for rendering is passed in the pNext member of the VkRenderPassBeginInfo struct.

The validation layer then tries to validate the framebuffer's attachments in 
ValidationStateTracker::RecordCmdBeginRenderPassState(),
--> ValidationStateTracker::AddFramebufferBinding()
----> ValidationStateTracker::GetAttachmentImageViewState(), in which it dereferences the nullptr provided in the pAttachments of the framebuffer creation info.

I may have misunderstood the (quite obscure) documentation but I tried giving the framebuffer's creation info the same image views as if it was non-imageless and it fixed the issue, even if it defeats the point of this extension.

On Windows 10, with the LunarG SDK 1.1.121

**Comment by mark-lunarg** [comment]
@Jelly3D,  can you share a repro case?  I looked through the tests in vklayertests_imageless_framebuffer.cpp and it looks like this same scenario comes up a few times.  Did you receive any validation errors/warnings before the crash?  Thanks!

**Comment by mark-lunarg** [comment]
With the available information, we are unable to reproduce this issue. If more information becomes available, or a test case is available, please reopen this issue.

**Comment by h3r2tic** [comment]
Hey!

I ran into this today, and managed to reproduce it with a small modification to `vklayertests_imageless_framebuffer.cpp`. Please see https://github.com/h3r2tic/Vulkan-ValidationLayers/commit/9547f42a3b14201052ffb13cbe2f3afe0ad6cc47

I believe the result should be a test failure (due to the modification), yet it results in an access violation as described by @Jelly3D.

Perhaps the tests which look like they would cover this manage to find other validation errors, and bail before running into this crash. A positive test case (`ExpectSuccess`) might do the trick.

Please let me know if you need anything else!

**Comment by mark-lunarg** [comment]
@h3r2tic, thanks, I'll give this a shot today!

**Comment by mark-lunarg** [comment]
Easily reproduced the issue, verified against the spec, and working on tests and a fix.  Thanks guys!

**Comment by h3r2tic** [comment]
Awesome, thank you!
