### ISSUE TITLE
No validation for storage image formats in SPIR-V

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/Vulkan-ValidationLayers#1276]
The Vulkan spec requires that the format specified in the SPIR-V for a shader must match the Vulkan format of the attached image view:

> If the instruction is OpImageRead or OpImageSparseRead and the shaderStorageImageReadWithoutFormat feature is not enabled, or the instruction is OpImageWrite and the shaderStorageImageWriteWithoutFormat feature is not enabled, then the SPIR-V Image Format must be compatible with the image view’s format.

There is no validation for this and Intel relies on it for certain image formats for certain hardware.

**Comment by danginsburg** [comment]
To add a bit more detail about the bug in Dota 2, see: https://github.com/ValveSoftware/Dota-2-Vulkan/issues/314

The current version of Dota 2 on Steam Public has this bug if you enable the "Compute Shader" option so you could use that to check validation.  Although I plan to fix this today so it might not be there much longer.

The shader has an OpTypeImage declared with rgba32f but the actual format of the image is VK_FORMAT_R8G8B8A8_UNORM.  I think there are other things that might be missing here that I want to make sure Validation is also catching:

* If OpTypeImage has format Unknown and there is an OpImageWrite - does it check that shaderStorageImageWriteWithoutFormat is supported/enabled in vkCreateDevice?
* If OpTypeImage has format Unknown and there is an OpImageRead - does it check shaderStorageImageReadWithoutFormat is supported/enabled in vkCreateDevice?

Those two checks are related to the above, because my fix is going to use Unknown but it's important validation checks the feature bits otherwise I might accidentally use Unknown when it's not supported.

**Comment by jekstrand** [comment]
We also need to make sure this is properly validated:
> - If shaderStorageImageReadWithoutFormat is not enabled and an OpTypeImage has “Image Format” operand of Unknown, any variables created with the given type must be decorated with NonReadable.
>
> - If shaderStorageImageWriteWithoutFormat is not enabled and an OpTypeImage has “Image Format” operand of Unknown, any variables created with the given type must be decorated with NonWritable.

**Comment by mark-lunarg** [comment]
To the eventual issue owner:  @jeremy-lunarg said he would "...have a lot of info/data on #1276 so if he wants that one, he should talk to me."

**Comment by spencer-lunarg** [comment]
So there has been some spec changes to the VUID and quite a few PR related to this since this was created

Between the following VUIDs (all which have validations and tests) should enough to close this issue

- VUID-RuntimeSpirv-OpTypeImage-06269
- VUID-RuntimeSpirv-OpTypeImage-06270
- VUID-RuntimeSpirv-OpImageWrite-07112
- VUID-vkCmdDraw-OpTypeImage-07027
- VUID-vkCmdDraw-OpTypeImage-07028
- VUID-vkCmdDraw-OpTypeImage-07029
- VUID-vkCmdDraw-OpTypeImage-07030
