### ISSUE TITLE
Warn if accessing texture from ram

### ISSUE THREAD

**Issue by fundies** [KhronosGroup/Vulkan-ValidationLayers#1285]
So I'm an idiot and messed up some code to select the proper memory index for using when uploading/accessing textures. This caused huge fps dips and multiple devs were unable to spot the error. If the validation layers printed an error for when not using VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT this problem could've been caught and fixed much sooner.

**Comment by DethRaid** [comment]
This wouldn't have caused a performance problem if you were using a system with a Unified Memory Architecture (integrated GPUs on desktop, every mobile device I'm aware of). The validation layers should only warn when you're sampling from an image in host memory if you're running on a NUMA system

This shouldn't be an error because maybe your application needs more image data than can fit in device memory. There's some situations where you do actually need to sample an image from host memory

**Comment by mark-lunarg** [comment]
In their default mode, the validation layers can only attempt to enforce the Vulkan specification.  Unless this warning/error is called out in the spec or an explicit/implicit VUID exists, it will not be added to validation.
However, there is a best-practices mode which can be enabled where this might be useful, and this warning request has been added to the Best Practices tracking issue (#24).
