### ISSUE TITLE
Inconsistent warning for pipeline layout "compatible for set N"

### ISSUE THREAD

**Issue by btolsch** [KhronosGroup/Vulkan-ValidationLayers#1286]
I have some rendering code that uses multiple pipeline layouts.  There are three that are relevant for this bug (using descriptor set layouts A and B):
1. descriptor set layouts: {A, B}, push constant range: {offset: 0, size: 16}
2. descriptor set layouts: {A, B}, push constant range: {offset: 0, size: 24}
3. descriptor set layouts: {A}, push constant range: {offset: 0, size: 92}

There's a sequence of code that draws with pipelines having layout 1, then 2, then 3.  It seems that by the Vulkan spec definition of pipeline layout "compatible for set N", it shouldn't be possible to leave descriptor set 0 bound from any of the prior draw sequences (i.e. 1->2 and 2->3 both should invalidate set 0).  However, what I observe is that omitting a new descriptor set binding for layout 2 both generates a validation error and crashes.  The specific error is:
```
UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound(ERROR / SPEC): msgNum: 0 - VkPipeline 0x55e84d1ea1b0[] uses set #0 but that set is not bound.
```
However, omitting a new descriptor set binding for layout 3 (i.e. reusing the one bound for layout 2) works fine without any validation errors.

This seems to be the same as a previously closed issue (KhronosGroup/Vulkan-LoaderAndValidationLayers#2214) but it (still or again?) seems to be present in release 1.1.121.  Additionally, the error text given above doesn't seem to match the error text added by KhronosGroup/Vulkan-LoaderAndValidationLayers#2423, but I'm that's the specific case it's catching anyway (i.e. no bind vs. incorrect bind).

**Comment by jzulauf-lunarg** [comment]
@btolsch  -- First, you've identified a good "incomplete" to fix -- there is a class of missing Valid Usage statements like:   

> `VUID-vkCmdDraw-None-02697`
> For each set n that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a descriptor set must have been bound to n at the same pipeline bind point, with a VkPipelineLayout that is compatible for set n, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility

There are errors you should be getting and *aren't*  which might have helped you.  Tagging the bug to reflect this.

Second  -- clarification on usage (to make sure there isn't something *else* broken).  You spoke of "prior draw sequence" invalidating sets.  Currently bound descriptor sets are only invalidated at vkCmdBindDescriptor time, AKAICT, so that simply a draw command or sequence *without* a BindDescriptor wouldn't invalidate a binding.

Can you give a calling sequence that results in the issue you are seeing? (or a simple reproduction case?)

Also, the error message seems to be the correct one for invalidated bindings (and wasn't altered at the listed change).  It is a draw time test that all bindings referenced in bound shaders have valid descriptors (in ValidateCmdBufDrawState).  Note that *only* bindings referenced in the bound shaders are examine for correctness.
