### ISSUE TITLE
Validation-Layers cause a segfault on vkBeginCommandBuffer

### ISSUE THREAD

**Issue by DadSchoorse** [KhronosGroup/Vulkan-ValidationLayers#1345]
I am the author of a [little vulkan layer](https://github.com/DadSchoorse/vkBasalt/tree/master) that does some post processing. The layer works as intended, but if I also use the Validation Layers they cause a segfault on vkBeginnCommandBuffer with no validation error reported before.

Validation Layers used are 1.1.121.0~rc3-1lunarg18.04.1.1 from the lunarg PPA.

**Comment by mark-lunarg** [comment]
@DadSchoorse, if we load up the post-processing layer and run with vkcube, will that be sufficient to observe the crash?  Is it Linux only?  Is the behavior the same if you reverse the order of the layers? Does the post-processing layer work fine with other layers (such as apidump)?  Thanks in advance for the extra information!

**Comment by DadSchoorse** [comment]
My layer is Linux only, and yes the crash can be observed with vkcube. I do not know how do change the order of the layer. Isn't a implicit layer always loaded closer to the program than the to icd compered to an explicit layer? 
With apidump and my layer vkcube crashes on BeginCommandBuffer too, does this mean it is a bug in my layer or not?

**Comment by mark-lunarg** [comment]
@DadSchoorse, as the crash occurs with both the Khronos layer and with api_dump, the issue is likely related to initializing dispatch tables for your _layer-created_ dispatchable objects.  Any DO (instances, devices, physical_devices, queues and command_buffers) must have their dispatch tables initialized.  So, for instance, in your `allocateCommandBuffer` routine, for each command buffer you need to do something like the following:

```
VkResult result = dispatchTable.AllocateCommandBuffers(device, &allocInfo, commandBuffers);
for index in commandBuffers:
    *reinterpret_cast<void**>(command_buffer[index]) = *reinterpret_cast<void**>(device);
```

**Comment by DadSchoorse** [comment]
Oh thanks for pointing this out, I did not know that I need to do this. Now everything works as expect.
