### ISSUE TITLE
Validation coverage of vkCmdDraw* entry points

### ISSUE THREAD

**Issue by mikes-lunarg** [KhronosGroup/Vulkan-ValidationLayers#135]
A small percentage of VUs for the vkCmdDraw* entry points are currently claimed to be covered by the validation database.  Most of the existing coverage is coming from implicit VUs (codegen) leaving large gaps in validation coverage for the explicit VU statements in these functions.

Entry point | Implicit VUs covered | Explicit VUs covered
---|---|---
vkCmdDraw | 4/4 | 3/24
vkCmdDrawIndexed | 4/4 | 4/25
vkCmdDrawIndirect | 6/6 | 4/32
vkCmdDrawIndexedIndirect | 6/6 | 4/32

**Updated counts as of 2020/11/18:**
Entry point | Implicit VUs covered | Explicit VUs covered
---|---|---
vkCmdDraw | 4/4 | 18/41
vkCmdDrawIndexed | 4/4 | 19/41
vkCmdDrawIndirect | 6/6 | 23/49
vkCmdDrawIndexedIndirect | 6/6 | 23/49

**Updated counts as of 2021/01/04:**
Entry point | Implicit VUs covered | Explicit VUs covered
---|---|---
vkCmdDraw | 4/4 | 33/50
vkCmdDrawIndexed | 4/4 | 33/50
vkCmdDrawIndirect | 6/6 | 39/57
vkCmdDrawIndexedIndirect | 6/6 | 39/57

**Comment by daveh-lunarg** [comment]
Still high priority.

**Comment by sfricke-samsung** [comment]
So I looked into this, most of the `VkCmdDraw`/`Dispatch`/etc commands have a lot of `VUID-vkCmd*-none-#####` VUID. One class of VUs I personally want to write validation for are ones like `VUID-vkCmdDraw-None-02690`

> If a VkImageView is sampled with VK_FILTER_LINEAR as a result of this command, then the image view’s format features must contain VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT

This is an issue that when you create `VkSampler` you can't check if the `VK_FILTER_LINEAR` is valid due to not knowing the tiling of the Image in the ImageView until its confirmed it is used (this tiling is needed to query format feature)

These are shared across all the commands, so adding one VUID is really more (for example of `02690` there are 14 VU's it covers!)

What I found is in `CoreChecks::ValidateDescriptorSetBindingData(` you know all the valid descriptor bindings are to check. The issue I realized is you really need to backtrack the pipeline being used and know if the SPIR-V does a sampling operation on an image potentially from another descriptor set (in case where on binding is a `VK_DESCRIPTOR_TYPE_SAMPLER` and another is `VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE`)

My idea to solve this is to keep data saved in `PIPELINE_STATE`, for all these "is it sampled" VU's I figure I just need to track with a map which descriptor binding/set is being sampled from what binding/set (in the case of a `COMBINED_IMAGE_SAMPLER` it doesn't need SPIR-V disecting). From there when validating the DrawState I would just iterator through that map and check they meet the various VU checks in place

**Comment by mark-lunarg** [comment]
@sfricke-samsung -- This doesn't seem unreasonable.  In drawdispatch.cpp, there's a function `ValidateCmdDrawType`, which is responsible for checking a handful of these 'multi-vuids', where the numeric portion is the same (i.e., `02690`) but the command name changes.  It'd be nice to change `ValidateCmdDrawType `to just take a command name, and then construct the VUIDs for each of the subchecks instead of passing them all in -- there seem to be at least a dozen.  

As for the specific VUIDs you are interested in, saving the state (somewhere in the statetracker, maybe?) and using it later for the checks is normal practice.  If the state data you need does not already exist elsewhere, this seems OK to me.

**Comment by sfricke-samsung** [comment]
My question about generating the VUID is how to let the script know that the VUID are covered

It seems to all work in my mind, just a matter of writing up an attempt and maybe going from there t

**Comment by mark-lunarg** [comment]
If I'm understanding your question correctly, the script parses the validation layer source code, comparing any discovered VUIDs to those in the `validusage.json` file in the Vulkan registry which describes them.  The on-line versions (on LunarXchange) are only updated at SDK-release time, but you can run reports yourself.  It has a bunch of options for ouput, or checking a single VUID, etc.

**Comment by sfricke-samsung** [comment]
I meant I was under the impression the script input was just the source

> It'd be nice to change ValidateCmdDrawType to just take a command name, and then construct the VUIDs for each of the subchecks instead of passing them all in -- there seem to be at least a dozen.

How would the script know about the VUID in this case?

**Comment by mark-lunarg** [comment]
Ah, right, sorry for my misunderstanding.  Not sure yet, but we've had to cover this in other cases.  Maybe they're in a table or structure which is selected in ValidateCmdDrawType?  I know there are several/many VUIDS checked but which are not getting picked up by the script.

**Comment by mark-lunarg** [comment]
Coverage exceeds original VUID totals and CmdDraw validation, while incomplete and still in progress, is on par with other API coverage.
