### ISSUE TITLE
unexpected error about VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT

### ISSUE THREAD

**Issue by pixeljetstream** [KhronosGroup/Vulkan-ValidationLayers#1366]
using 1.1.126.0 SDK

getting the following error message, which references a non existing "0" primary buffer, and imo the application doesn't actually fall into that problem.

ERROR: VUID-vkQueueSubmit-pCommandBuffers-00073
 --> VkCommandBuffer 0x2540994cdc0[] was submitted with secondary VkCommandBuffer 0x2540994b3a0[] but that buffer has subsequently been bound to primary VkCommandBuffer 0x0[] and it does not have VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT set.

**Comment by mark-lunarg** [comment]
Hey @pixeljetstream, after some investigation it looks like we may indeed have some issues with these validation checks.  It'd help us out a lot if you could list any validation errors that appeared before this one, and to share either a sample program or some pseudocode showing the creation and use of the commandbuffers in question.  Thanks!

**Comment by pixeljetstream** [comment]
reproducer app (use the ...VULKAN_ONLY build option)
https://github.com/nvpro-samples/gl_vk_threaded_cadscene
to enable validation layer, build in debug and remove the || 1 in the setupVulkanContextInfo function inside csfthreaded.cpp that removes the layer by default. 
there is two mult-threaded renderers in the "renderer" list, I think the first one throws the errors (one of them does).

**Comment by mark-lunarg** [comment]
@pixeljetstream, thanks for the great repro instructions!  I was easily able to reproduce the problem, and found that the application is passing secondary command buffers to QueueSubmit, in pSubmits->pCommandBuffers, violating `VUID-VkSubmitInfo-pCommandBuffers-00075`, which says 
`Each element of pCommandBuffers must not have been allocated with VK_COMMAND_BUFFER_LEVEL_SECONDARY`.  This VUID check was unimplemented, and I have a PR now underway to correct this.  The error messages you saw were from further down the secondary/simultaneous_use checks, which were rendered less than useful (if not downright confusing) due to the initial error.  I will update this issue with that PR when it's ready.

**Comment by pixeljetstream** [comment]
thanks, that is fixed via https://github.com/nvpro-samples/gl_vk_threaded_cadscene/commit/6f023efc98a2388cc1dd382ea4b7554fb98cbc78 so don't use newer commits if you want to repro old error behavior.
