### ISSUE TITLE
Validation layers don't flag usage of absent extensions

### ISSUE THREAD

**Issue by ROTARTSI82** [KhronosGroup/Vulkan-ValidationLayers#1399]
I originally posted an issue at https://github.com/LunarG/VulkanTools/issues/933 since I was using the LunarG sdk, but I was told to post it here instead.

*Disclaimer: I am a newbie at Vulkan*

When attempting to call a function such as `vkCreateSwapchainKHR` without including the necessary extensions, the program just segfaults and the validation layers do not detect this at all. It would be nice if validation layers checked for usage of absent extensions instead of the program just segfaulting. (I made this dumb mistake and it took quite a while to debug)

**Comment by mark-lunarg** [comment]
@ROTARTSI82, thanks for the report.  The decision was made by the Vulkan working group to have the Vulkan loader export this function as a core function regardless of whether it was enabled or not.  Since the pointer is null (as it was not enabled, and the layers/driver correctly return a null pointer for GetInstanceProcAddr) the layers are never called.  So, there's no way for the layers to detect and report this case.  This is by design (!), and any follow-up would need to be in the ma[in Vulkan-Docs repository](https://github.com/KhronosGroup/Vulkan-Docs/issues).  Good luck!
