### ISSUE TITLE
Support for validating shaderSampledImageArrayDynamicIndexing and other related caps?

### ISSUE THREAD

**Issue by null77** [KhronosGroup/Vulkan-ValidationLayers#1407]
From the spec:

> shaderSampledImageArrayDynamicIndexing specifies whether arrays of samplers or sampled images can be indexed by dynamically uniform integer expressions in shader code. If this feature is not enabled, resources with a descriptor type of VK_DESCRIPTOR_TYPE_SAMPLER, VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, or VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE must be indexed only by constant integral expressions when aggregated into arrays in shader code. This also specifies whether shader modules can declare the SampledImageArrayDynamicIndexing capability.

Is there a check for this already? If not, could we add validation for this? It is possible an ANGLE bug could have been caught by the layers when we were testing GLES 3.2 functionality with SwiftShader.

Related features:

```
    VkBool32    shaderUniformBufferArrayDynamicIndexing;
    VkBool32    shaderSampledImageArrayDynamicIndexing;
    VkBool32    shaderStorageBufferArrayDynamicIndexing;
    VkBool32    shaderStorageImageArrayDynamicIndexing;
```

**Comment by locke-lunarg** [comment]
This issue might need to be fix in shader compiler.

The whole shader features support validation are checked in  `CoreChecks::ValidateShaderCapabilities`.

It can catch _shaderInputAttachmentArrayDynamicIndexing_, _shaderUniformTexelBufferArrayDynamicIndexing_, and _shaderStorageTexelBufferArrayDynamicIndexing_, 
BUT NOT _shaderUniformBufferArrayDynamicIndexing_, _shaderSampledImageArrayDynamicIndexing_, _shaderStorageBufferArrayDynamicIndexing_, _shaderStorageImageArrayDynamicIndexing_.


The reason is shader compiler generates
```
Capability InputAttachmentArrayDynamicIndexingEXT
Capability UniformTexelBufferArrayDynamicIndexingEXT
Capability StorageTexelBufferArrayDynamicIndexingEXT
```
if the shader code matches _shaderInputAttachmentArrayDynamicIndexing_, _shaderUniformTexelBufferArrayDynamicIndexing_, and _shaderStorageTexelBufferArrayDynamicIndexing_ situations.


BUT shader compiler doesn't generate
```
Capability UniformBufferArrayDynamicIndexing
Capability SampledImageArrayDynamicIndexing
Capability StorageBufferArrayDynamicIndexing
Capability StorageImageArrayDynamicIndexing
```
even if the shader code matches _shaderUniformBufferArrayDynamicIndexing_, _shaderSampledImageArrayDynamicIndexing_, _shaderStorageBufferArrayDynamicIndexing_, _shaderStorageImageArrayDynamicIndexing_. situations.

**Comment by jeremy-lunarg** [comment]
We do test if the Vulkan features associated with SPIR-V capabilities are enabled. However, as @locke-lunarg  pointed out, glslang doesn't generate those four ArrayDynamicIndexing capabilities. Nor does spirv-val validate them. There's an issue logged in the glslang repositor. See https://github.com/KhronosGroup/glslang/issues/2056.

**Comment by null77** [comment]
Thanks for pointing out the glslang issue Jeremy. Shouldn't we hold this open until the glslang issue is resolved? It's likely going to be an issue for ANGLE on Android.

**Comment by jeremy-lunarg** [comment]
> Thanks for pointing out the glslang issue Jeremy. Shouldn't we hold this open until the glslang issue is resolved? It's likely going to be an issue for ANGLE on Android.

There's not much to be done with respect to the validation layers repo. The validation layers check for Vulkan features when the relevant SPIR-V OpCapabilities are encountered, but the glslang compiler will need to generate the OpCapabilities before we can report these disabled features in the validation layers. I just added [tests](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1595) for the features discussed in this issue.

i.e. Once the glslang issue is fixed, the validation layers will report the problem you encountered.
