### ISSUE TITLE
Improved tests for VK_EXT_validation_features

### ISSUE THREAD

**Issue by rg3igalia** [KhronosGroup/Vulkan-ValidationLayers#1413]
Related to #1412 and also somewhat to #1392, I've seen several tests using VK_EXT_validation_features, like checking the best practices layer and GPU-assisted validation. There are also some checks disabling features, like CreatePipelineWithCoreChecksDisabled and StatelessValidationDisable. These could be made more comprehensive by also checking other features that can be disabled: thread safety, object lifetimes, shaders, the "all" meta-feature and, if possible, unique handles (for this last one I'm unsure about how to test it).

As with #1412, there was an open issue to create tests for this extension in VK-GL-CTS, but by being implemented in the layer they are not related to conformance.

**Comment by mark-lunarg** [comment]
Due to the normal resource constraints, it is standard practice to implement a subset of tests to verify a mechanism or family of checks without requiring full coverage.  However, if issues arise layer, fixes are typically accompanied by new tests.  For the foreseeable future, this'll be the case for this extension and the ValdationCache one (#1412) as well.

**Comment by mark-lunarg** [comment]
Rolling these wants into the internal worklist.  Thanks for the pointers!
