### ISSUE TITLE
Distributed SDK binaries for Apple platforms should be built with VK_EXT_metal_surface support

### ISSUE THREAD

**Issue by Valakor** [KhronosGroup/Vulkan-ValidationLayers#1416]
It seems like the `VK_EXT_metal_surface` extension is technically supported in the validation layers, but the distributed SDK binaries don't seem to actually be built with `VK_USE_PLATFORM_METAL_EXT` defined, at least in SDK 1.1.126.0.
This causes a validation layer error (and subsequent crash) about an unsupported instance extension when I try to use the now-recommended `VK_EXT_metal_surface` extension in place of `VK_MVK_macos_surface`.

**Comment by Valakor** [comment]
Also, tagging @billhollings for any additional input.

**Comment by mark-lunarg** [comment]
@jeremyk-lunarg, can you post a short update?

**Comment by jeremyk-lunarg** [comment]
- Certain parts of the layer code where not being built because our CMake file was not setting the option VK_USE_PLATFORM_METAL_EXT.
- After changing the CMake file to set this option, build errors occurred due to the generated file `vk_safe_struct.cpp` not including a MacOS specific file that contains a required class, `CAMetalLayer`, to create a VkMetalSurfaceEXT.
- Unfortunately, the include file I have found so far, `QuartzCore/CAMetalLayer.h`, references other header files, one of which, `Foundation/NSObjCRuntime.h`, is causing the `xcodebuild` compiler to throw errors.

I'll keep hunting down what needs to be done, but if anyone has any new information on this subject that would be greatly appreciated.

**Comment by KarenGhavam-lunarG** [comment]
> Certain parts of the layer code where not being built because our CMake file was not setting the option VK_USE_PLATFORM_METAL_EXT.

Does this mean this option must be set whenever building for macOS? Who put the option into the Validation Layers initially?

**Comment by jeremyk-lunarg** [comment]
It does not need to be set every time it's built.  CMake can detect if it is on MacOS and set the option automatically.

From a quick look, it would seem this was originally put in by @karl-lunarg in [this commit](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/2e5ed33c9548444ea89813e474ede98dcb0840b6#diff-107716343bf49cdc077faa63026a8482).
