### ISSUE TITLE
Unclear validation message when creating a VkPipeline with too many push constants

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/Vulkan-ValidationLayers#1597]
I recently got the following message from the validation layers:
```
Push constant range covering variable starting at offset 4 not declared in layout
```
After some digging, I found that the problem was that my vertex shader module declared three push constants, but my VkPipelineLayout was only created with one push constant

The validation message was pretty confusing at first. I think something like "Shader declares `n` push constants, but only `m` were declared in VkPipelineLayout `layout`" would be more direct and clear

**Comment by jeremy-lunarg** [comment]
I [reworked](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2045) the output of that message and enumerated the structure members. It should make it a little more clear as to what is missing in the layout. I also have a [WIP](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2046) for the size calculation in that code as well since the association is across bytes and our current method isn't entirely accurate.
