### ISSUE TITLE
Validation dependency revisions are not tracked

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#161]
The repo split caused Validation CI to be non-deterministic and makes it impossible to consistently check older versions of Validation repo against known-good versions of various repo dependencies which now include glslang, Loader, Header, & Tools.

See #162 for an example of this problem.
[PR160](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/160) for an example CI run.

The immediate solution would seem to be to move to a file with known-good SHA1s for all of the dependent repos. Those SHA1s can be set to roll fwd automatically, but in the instance of an external repo causing Validation to break, the SHA1 must stick to the last known-good version.

**Comment by karl-lunarg** [comment]
@tobine:
> The immediate solution would seem to be to move to a file with known-good SHA1s for all of the dependent repos. 

The immediate solution (#162) was to fix the simple oversight of not updating the V-VL CI to reflect changes in the V-L build structure.  Normally, this would be done within a few minutes of each other, thus leaving a pretty small window for error.   Although I do agree it would be good to close this window for this and other changes that cause cross-repo incompatibilities.

> Those SHA1s can be set to roll fwd automatically

How?  Can you explain?  I do wonder about who would update these SHA1s.

> but in the instance of an external repo causing Validation to break, the SHA1 must stick to the last known-good version.

Again, how?  Are you saying that the V-VL repo would attempt to roll forward and if successful, keep the new SHA1s, and if not, leave then the same and re-run the jobs?

**Comment by tobine** [comment]
> The immediate solution (#162) was to fix the simple oversight of not updating the V-VL CI to reflect changes in the V-L build structure.

That was a spot fix for a single failure, but not an immediate solution to fixing the lack of dependency tracking.

The dependency tracking is needed not only to prevent failures in VVL CI when dependencies break, but also to allow for repeatably testing/replicating previous VVL runs.

Regarding the general "how?" of SHA1s can be managed a basic outline of a potential solution is:

- Store known-good SHA1s for all dependent repos in a file (deps) that's part of the repo
- Pull repo dependencies based on the known-good SHA1s from the deps file

That is sufficient to keep VVL CI from breaking. The conservative solution is to just keep this file static and if someone updates a dependency that they want VVL to pick up, they update the deps file manually. This is how [ANGLE](https://chromium.googlesource.com/angle/angle/+/master/DEPS) manages an extensive list of external deps.

If it's important/desired to auto-roll the SHA1s (it's not to me), the above process can be enhanced as:
- Run CI with the latest HEAD of each repo and grab SHA1 for each repo
- If CI passes, update SHA1s in deps file and commit along w/ changes
- If CI does not pass, could iterate over repos where a single repo is locked to known-good version and all others are rolled fwd.

If this cannot all be automated within the cloud CI system (I suspect it can but don't know how offhand), then it could be setup with a script that's run as a cron job or in some external farm system, that would then post PRs as things change.
Obviously with lots of deps the possible combinations of repos causing failure can make for very intricate and complicated solutions. I don't think we need anything that's comprehensive.

Instead if we want to automate the rolling fwd then I think it should work in most cases, but when it fails we fall-back to known-good SHA1s and put an indicator in deps file to stick to known-goods. Then whoever next wants to roll forward a dep will have to do so manually and when the fail with latest is fixed, the indicator in the deps file is manually removed.

**Comment by karl-lunarg** [comment]
When we first started dealing with this repo split, we had always envisioned that additional tools or structure could be added that would do things like pick selected revisions and/or build groups of repos into useful collections of tools.

And that's still the case.

Since this is a cross-repo problem, the final solution probably lies with another "meta repo" or some other place that contains known-good information and perhaps scripting to help with build tasks.  I don't think we're quite ready to implement this yet, as more thinking needs to be done.

But for the "immediate solution" for this repo, we could implement a known-good file of some sort and provide a script that pulls and builds the prerequisite repos.  Since this repeatability seems especially important for this repo, we could pilot it here first, with the intention of it getting moved someplace later and/or expanded to other repos.  While some of us might have the luxury of only being concerned about what happens in this repo, we do need to think about the rest of them.

For example, when thinking about a "known-good" list for multiple repos, do you have one "known-good" for all repos, or do you have a "known-good" for Vulkan-ValidationLayers and another "known-good" for something like Vulkan-Loader?  If the latter, what happens with conflicts?

Random thoughts about this file and script:
* known-good would probably be a json file, like the one used in glslang
* script would hopefully be python so that it can run on Win/Lin/Mac
* script would checkout the known-good versions of the repos
* script should be directly usable by Travis and Appveyor CI.  This would cut down on CI config verbosity
* script should be directly usable by repo developers.  This may let them set up their dev environment quickly
* script usage should be _optional_.  That is, a user can easily get by with things the way they are now (eh, soon).

While the routine PR-triggered CI would use this known-good system, I also feel that it is important to test the repo using HEAD revisions, at least periodically.  So, some CI machine could be set up to build all the repos from HEAD on a crontab-determined schedule (e.g., daily).  It would send email with the results to the repo maintainers and maybe even with an updated known-good json, saying that the build failed, or saying the build worked and to consider checking in the updated known-good json.   The repo maintainers would then decide when to update the known-good.

I'm a little leery of auto-rolling or other automated updates for many of the same reasons you point out.  And I don't think it is important ATM.  The above scheme is a compromise between auto-rolling and the unpredictability with "if someone updates a dependency that they want VVL to pick up", without pressuring the repo maintainers too much.

Thoughts?

**Comment by tobine** [comment]
Everything here sounds good and reasonable to me. I echo your sentiment

> Since this repeatability seems especially important for this repo, we could pilot it here first, with the intention of it getting moved someplace later and/or expanded to other repos.

Regarding potential known-good conflicts between separate repos my initial thought is that each repo should be self-contained. So VVL repo who have known-good for all of its repos (including Vulkan-Headers), but Loader may have a different known-good value for its common dep of Vulkan-Headers.

json format & python script sound great to me as well as the rest of your script thoughts.
