### ISSUE TITLE
ValidationStateTracker::PostCallRecordQueueSubmit missing failure check?

### ISSUE THREAD

**Issue by jpark37** [KhronosGroup/Vulkan-ValidationLayers#1653]
I have a vkQueueSubmit call that I use with a fence and Win32 keyed mutexes, and expect it to fail with VK_TIMEOUT occasionally if there is contention. When it does, I get validation errors later on about the fence being signaled. I would expect the fence to remain unsignaled because the call failed.

Should the fence be considered signaled on vkQueueSubmit failure? Or is this a validation bug?

**Comment by mark-lunarg** [comment]
@jzulauf-lunarg, if you determine what The Right Thing is, I'm happy to implement it either way.

**Comment by jzulauf-lunarg** [comment]
I note that none of the PostCallRecordQueueSubmit calls have tests for result == VK_SUCESS ... this is likely the cause of the error.

Looking at the spec, this seems wrong ... because

> If vkQueueSubmit fails, it may return VK_ERROR_OUT_OF_HOST_MEMORY or VK_ERROR_OUT_OF_DEVICE_MEMORY. If it does, the implementation must ensure that the state and contents of any resources or synchronization primitives referenced by the submitted command buffers and any semaphores referenced by pSubmits is unaffected by the call or its failure. If vkQueueSubmit fails in such a way that the implementation is unable to make that guarantee, the implementation must return VK_ERROR_DEVICE_LOST

So for anything other than SUCCESS either we know the state can't have changed or we don't know what the right state is.  In either case updating state doesn't make sense.
