### ISSUE TITLE
Why are submodules being removed? \ build too complicated

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#169]
http://www.monkeyuser.com/2017/keep-up-to-date/

Why are submodules being removed? They seem the simpler alternative, and fit my usage well.

Current setup requires too much manual work, does not manage versions, and is pain to update dependencies each time. It requires to keep a repo duplicate anyway (to make sure it is not dirty), so there is little advantage.

**Comment by sarnex** [comment]
From a distribution packaging point of view, submodules are not acceptable

**Comment by mark-lunarg** [comment]
Eh, @krOoze, it turns out submodules aren't very popular.  Also, we quickly ran into issues where a superproject had subprojects with duplicate submodules (i.e., headers, glslang, etc.) which led to a whole new batch of problems. Though things are rough at present we hope to get things running a bit more smoothly in the short-term (fingers-crossed).

**Comment by karl-lunarg** [comment]
> From a distribution packaging point of view, submodules are not acceptable

What he said.  In addition, there was some pushback from the Vulkan WG.  Some other platform owners said that submodules don't work well or at all with their systems.

We would like to make a script or some other helper (see #161) that would ease setting up the dependencies and syncing the revisions.  We hope to get that started soon.  Feel free to discuss in #161 and/or contribute.
