### ISSUE TITLE
WriteDescriptorSet wrong dstArrayElement can crash validation

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-ValidationLayers#182]
Observed on 1.1.73.0.
I have a DS layout as the following:
[0] input attachment
[2] uniform buffer
[3] uniform buffer

I tried to update the input attachment in my DS wrongly, by passing in dstArrayElement = 1, instead of 0. This crashes the validation (`update->**pBufferInfo** was 0x111011101110112` : `VkLayer_core_validation.dll!cvdescriptorset::BufferDescriptor::WriteUpdate(const VkWriteDescriptorSet * update, const unsigned int index) Line 1473 at C:\vulkansdkbuild\workspace\loaderandvalidationlayers\layers\descriptor_sets.cpp(1473)`), my guess is that it reads the wrong descriptor type and then tries to fetch the DescriptorBufferInfo. While the crash is not great, there might be also a validation missing for these error types.

**Comment by mark-lunarg** [comment]
@martty, guessing you received no validation errors prior to the crash?

**Comment by locke-lunarg** [comment]
I'm not sure if the issue still exist.

If dstArrayElement is wrong, it shows `VUID-VkWriteDescriptorSet-dstArrayElement-00321: The sum of dstArrayElement and descriptorCount must be less than or equal to the number of array elements in the descriptor set binding specified by dstBinding, and all applicable consecutive bindings, as described by consecutive binding updates`.

And it crashes in `descriptors_[global_idx + di]->WriteUpdate of cvdescriptorset::DescriptorSet::PerformWriteUpdate`, not in `cvdescriptorset::BufferDescriptor::WriteUpdate`.

Even it runs `WriteUpdate`, it runs `cvdescriptorset::ImageDescriptor::WriteUpdate`, not  `cvdescriptorset::BufferDescriptor::WriteUpdate` because the descriptor type is `VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT`.
