### ISSUE TITLE
CMAKE_INSTALL_INCLUDEDIR putting .cpp files in /usr/include?

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [KhronosGroup/Vulkan-ValidationLayers#1905]
See SDK issue https://gitlab.khronos.org/vulkan/Vulkan-SDK-Packaging/-/issues/348

We believe that the validation layers build is putting some files in the /usr/include that we are not sure is correct.

**Comment by mark-lunarg** [comment]
The SDK builds (Linux and Mac, possibly Windows) are explicitly requesting to install these files by specifying the `BUILD_LAYER_SUPPORT_FILES `build definition.  This is usually only required when this repo is a dependency of a downstream repo, in order to build layers in that repo that use source code from this repository (i.e., VulkanTools).  By default the files in question are not installed.
