### ISSUE TITLE
Incorrect image layout validation error

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#1919]
Issue found by @egdaniel that I suspect is a validation bug.

I have a simple test where I'm adding 3 memory barriers to a command buffer and submitting it. It hits a validation error that seems potentially incorrect. The steps of the test are:

1. Create texturable VkImage
2. With barrier transition image to VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL (no queue family change)
3. Transition image to LAYOUT_GENERAL and QUEUE_FAMILY_EXTERNAL.
4. Keep image as GENERAL but transfer back from EXTERNAL to main graphics queue.
5. Submit command buffer

When executing these commands the barrier in step 4) gives the following validation error:

"Validation Error: [ VUID-VkImageMemoryBarrier-oldLayout-01197 ] Object 0: handle = 0x1d279247240, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x124ffb34 | For VkImage 0x5d11410000000004[] you cannot transition the layout of aspect=1 level=0 layer=0 from VK_IMAGE_LAYOUT_GENERAL when the previous known layout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL. The Vulkan spec states: oldLayout must be VK_IMAGE_LAYOUT_UNDEFINED or the current layout of the image subresources affected by the barrier (https://vulkan.lunarg.com/doc/view/1.2.141.0/windows/1.2-extensions/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01197)"

If I don't do step 4 I get no errors. If I never transition to GENERAL (i.e. keep shader read as old and new layout) in steps 3 and 4 then I get no errors. If I don't go to the external queue then I get no errors.

Is there something in the spec that I'm missing that says I can't do the layout transition to general at the same time as going to external? Again this is just a unit test and not a practical use case we are hitting in real code.

**Comment by jzulauf-lunarg** [comment]
Likely a bookkeeping issue in the release/acquire path.  In general we defer the layout transition "paper" transaction to the acquire s.t. we don't double count it (and cause *other* errors).  Reviewing.

**Comment by jzulauf-lunarg** [comment]
@tobine  -- how does one legitimately transition to and from another queue family within the *same* command buffer?  Once you QFO transfer release, the resource is undefined for further use within that command buffer. Synchronization with an external queue family required (AFAICT) synchronization not possible within the context of a single command buffer (or even submit for that matter)

I'm not sure the validation is correct, but the usage seems terribly wrong as well.  The bookkeeping isn't set up to check for release-acquire in the same command buffer.  Checking the logic for separate CB's

**Comment by egdaniel** [comment]
So for context, this came up in a unit test I wrote to make sure our internal tracking of the VkImage state was staying consistent. So it is by no means meant to be any practical thing someone would do. I have tried doing using a new command buffer for the re-acquiring from external and that does to work without any errors.

Do you have something in the spec that says the Resource is undefined after a queue release within the same command buffer? I was looking but couldn't find something like that myself.

**Comment by jzulauf-lunarg** [comment]
@egdaniel  -- "Access after a release operation has undefined results.."  https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#synchronization-queue-transfers

Also includes the comments:

"A queue family ownership transfer consists of two distinct parts:

Release exclusive ownership from the source queue family

Acquire exclusive ownership for the destination queue family

An application must ensure that these operations occur in the correct order by defining an execution dependency between them, e.g. using a semaphore."

Thus you couldn't have a release and reacquire in the same command buffer, b/c semaphores occur *between* command buffers.

**Comment by egdaniel** [comment]
As to the first thing, there is nothing that says access after a release operation has undefined results if from the same command buffer. Thus if for external queue operations that would suggest that it is never valid to switch the queue family back even with a new command buffer. This doesn't seem right to me.

As for the second part aren't the barriers themselves assuring the correct ordering with the command buffer? The semaphore is just an example of how to assure ordering for the case when you are using different command buffers on different queues.

**Comment by jzulauf-lunarg** [comment]
The context for the quote is: 

"Whilst it is not invalid to provide destination or source access masks for memory barriers used for release or acquire operations, respectively, they have no practical effect. Access after a release operation has undefined results, and so visibility for those accesses has no practical effect. Similarly, write access before an acquire operation will produce undefined results for future access, so availability of those writes has no practical use. In an earlier version of the specification, these were required to match on both sides - but this was subsequently relaxed. These masks should be set to 0."

It's precisely saying that access after a release (and before an acquire) are invalid (which is why the masks don't matter) ... (@Tobski  @jeffbolznv this still reads oddly... shouldn't it say dest access masks for release and source access masks for acquire?)

This is *specifically* talking about commands within the command buffer and queue.

The barriers certainly *do* order operations but only within a given command buffer, then queue and between queues only as "chained" to other inter-queue synchronization operations. For a command buffer to acquire a resource, the release operation needed to permit that reacquistion occurs on an entirely different queue family, let alone queue, Only semaphores, fences, idles, and host triggered events are able to do inter-queue synchronization, but even they would need a command buffer boundary to sequence themselves. Thus, once you release a resource, the resource must be considered invalid for the duration of that command buffer (and until another command buffer, properly synchronized with the other queue family's release) does an acquire.

**Comment by egdaniel** [comment]
I definitely agree with everything you say for the case where there actually is another queue family that is going to acquire the image. The issue here is with external there isn't necessarily another queue out there to acquire the image. I feel that is a gray area in the spec that isn't fully fleshed out.

You say that "For a command buffer to acquire a resource, the release operation needed to permit that reacquistion occurs on an entirely different queue family, let alone queue." So if this is true for external as well, are you saying that it is impossible to release to an external queue family and then reacquire the same image to the main queue without some external context/system on the device taking ownership and then release it?

If the above all true then it isn't every possible to release to external and acquire back without actually doing external stuff, even if those two operations are done in different commandbuffers on the same queue and you even put a semaphore between those two command buffers. Is this really what the spec says?

**Comment by jzulauf-lunarg** [comment]
@egdaniel  -- generally, when taken all together, yes.  The sync bits require a good bit of ferreting to pull the pieces together.  The bread crumbs are all there, you just have follow them. Annotating the original sequence quote:


"A queue family ownership transfer consists of two distinct parts:"

<< Insert (or include in the barrier definition), appropriate synchronization for prior operations in the source queue >>

"Release exclusive ownership from the source queue family"

<< Insert appropriate sync operations between queues here >>
<< If dest waits on a semaphore, submit releasing command buffer with signalling semaphore, before submitting dest >>

"Acquire exclusive ownership for the destination queue family

An application must ensure that these operations occur in the correct order by defining an execution dependency between them, e.g. using a semaphore."

Which means to get the resource back, the destination family must:

* Have appropriate intra-queue synchronization in the destination queue
* release back to the original source
* Have appropriate inter-queue synchronization between orginal dest and orginal source
* The original source must acquire it from the original destination 

This is true for external as well as internal queue_families.  For external foreign there are slightly different rules (e.g. layout must be "general"), and the available inter-queue sync operations will be different (and what the foreign API does that is comparable to acquire and release will of course be different.)

**Comment by jzulauf-lunarg** [comment]
@egdaniel 

" then it isn't every (ed. is it ever) possible to release to external and acquire back without actually doing external stuff,"

@jeffbolznv @Tobski  -- this seems like the sort of thing that would likely confuse an implementation.  Maybe one could safely transition from undefined, discarding the contents, but I'm not sure what submitting a buffer like that would look like in terms of implementation behavior/requirements.

If it's legal which can change the validation to allow it, but it feels like exactly the kind of corner case one doesn't want to explore in an implementation and be portable.

**Comment by critsec** [comment]
> << Insert appropriate sync operations between queues here >>

I think the spec just says appropriate sync operations. It uses inter-queue synchronization as an example, because that's what will be involved in most real-world usage, but any operation that establishes a happens-before relationship [execution dependency] between the release and acquire should work.

**Comment by egdaniel** [comment]
@jzulauf-lunarg I don't disagree with what you wrote, but there is nothing in the spec that says the "external" queue can't just but same vulkan context and queue you just came from. So in some sense you can think of the two queue transitions as independent but they just happen in this case to act on the same underlying vulkan resource. Thus the only other requirement we have to meet is that we ensure the order of the two barriers so that the release happens before the acquire. And I believe even if in the same command buffer this happens.

**Comment by jzulauf-lunarg** [comment]
@critsec  -- one could wait idle, wait on fences, lots of choices, but all of them require a command buffer boundary, and thus I can't see how one could validly release and acquire in the same command buffer.

**Comment by critsec** [comment]
I'm having trouble thinking of any other case where we say that whether a sequence of operations is valid depends on whether they're in the same command buffer or not. Being in separate command buffers provides some implicit synchronization, but that same synchronization is possible within a single command buffer. If it's valid to do them in separate command buffers it should be valid to do them in the same command buffer.

Apart from unit tests, when interacting with an external system you might release an image and then find that you don't actually need to send it to the other system or do any work there. So then you'd want to re-acquire in the same queue. In that case you'd have separate command buffers, but as I said above I really don't think we want to distinguish same command buffer vs. separate command buffers for validity.

**Comment by jzulauf-lunarg** [comment]
@egdaniel  -- the synchronization scopes for barriers don't include commands on other queues while this command buffer is running. Only "commands that occur earlier in submission order."  The dest acquire has to happen *after* (in submission plus interqueue sync order) of the source release, which means that any acquire in that same command buffer on source queue is *already* before any release that could happen in the dest queue.  There's no ordering that allows for barriers to provide sufficient synchronization for a release/acquire within the same command buffer.

**Comment by jzulauf-lunarg** [comment]
@critsec  -- what interqueue sync is possible within a command buffer?  That's what's different here than everywhere else.  It's an operation within a command that requires inter-queue synchronization, and that requires (AFAICT) a buffer boundary for a fence or semaphore.  Events can't be used across queues, and barriers use submission order, s.t. things (like the acquire on the dest queue) that must happen in submission order impose command buffer boundaries...

CB0 on Q0
Release0

CB1 on Q1
Acquire0
Release1

CB2 on Q0
Acquire1

As Acquire1 must be after (in submission order) Release1, and Aqcuire0 must be after Release0, it is impossible to move Acquire1 to CB0.

**Comment by critsec** [comment]
If you're not actually interacting with another queue then no inter-queue sync is required. All that's required is that there be an execution dependency between the release and the acquire operation. If those happen on the same queue then intra-queue sync is sufficient.

**Comment by egdaniel** [comment]
I think the point you're missing is that there is only one queue happening here, so you don't need any inter-queue synchronization.

Would you agree that the follow calls are allowed in the same command buffer on queue family 0 in this order:

1) Release VkImage_M from Queue family 0 to QUEUE_FAMILY_EXTERNAL
2) Acquire VkImage_N from QUEUE_FAMILY_EXTERNAL to Queue family 0

So assuming you agree you can do those two commands, why can't we handle the case where M=N? The only additional requirement is that step 1 happens before step 2, which will hold.

Using your example above, I think part of the confusion is that you think we are trying to do Release0 and Acquire1 on the same command buffer. However what we are actually doing is Release0 and Acquire0 on the same command buffer.

**Comment by jzulauf-lunarg** [comment]
@egdaniel  -- If M != N there no specific ordering nor synchronization is needed because it's different memory, so that sheds no light.

For M==N:
your'e doing Release0 and Acquire1 without an intervening Acquire0, Release1. For every *other* case but external... you can't do that and be valid -- the Release1 would be a requirement for the Acquire1 (they must be paired) -- again for non-external.

So the question is with *external*.  Given that the instance cannot know what the external instance has or hasn't done, for an Acquire it would assume, the Release must have happened -- the memory is available. 

"Queue family ownership transfers may perform read and write accesses on all memory bound to the image subresource or buffer range, so applications must ensure that all memory writes have been made available before a queue family ownership transfer is executed. Available memory is automatically made visible to queue family release and acquire operations, and writes performed by those operations are automatically made available."

Assuming it wouldn't stump the implementation, you could argue the Release/Acquire self-protecting (assuming the pre-release access is sync'd).  Legal if useless/impossible-to-use-usefully?

@jeffbolznv @Tobski  @tobine
