### ISSUE TITLE
Spurious command buffer state errors when synchronizing via vkGetSemaphoreCounterValue

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/Vulkan-ValidationLayers#1999]
To reproduce:
1. Submit command buffer to a queue, configured to signal a timeline semaphore on completion
2. In a second thread, periodically call `vkGetSemaphoreCounterValue`.
3. When the counter value passes the value signaled by the submission, reuse the submitted command buffer in the second thread.

~On Intel, I had to additionally periodically call `vkWaitSemaphores` with a timeout of 0 on the first thread or the counter value would never appear to increase above 0, though it's not clear to me if this is intended~ ([mesa issue #3226](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3226), fixed in master). Calling `vkWaitSemaphores` after `vkGetSemaphoreCounterValue` on the second thread, using the counter value returned, suppresses the error.

Specific validation errors triggered include `VUID-vkBeginCommandBuffer-commandBuffer-00049`, `VUID-vkQueueSubmit-pCommandBuffers-00071`, `VUID-vkDestroyCommandPool-commandPool-00041`.

**Comment by fheavr** [comment]
I additionally see 
VUID-vkResetCommandBuffer-commandBuffer-00045 
VUID-vkResetDescriptorPool-descriptorPool-00313 
and very rarely VUID-vkDestroyFramebuffer-framebuffer-00892 (probably because of how I age out framebuffers)

**Comment by fheavr** [comment]
seems related to #1502

**Comment by farnoy** [comment]
Hey @mark-lunarg, from a brief look, it seems to me that `state_tracker` ought to hook `PostCallRecordGetSemaphoreCounterValue` and call `RetireTimelineSemaphore` with the current value. This will retire all state tied up in earlier submissions (those that signal the timeline semaphore with `<=` current value) and should address all the VUIDs mentioned above.

I am not 100% sure about the execution order, due to this sentence in section 2.2.1:
> Command buffer submissions to a single queue respect submission order and other implicit ordering guarantees, but otherwise may overlap or execute out of order

The way I understand it is that, if we had two submissions:
1. Waits for nothing, signals value `x` of our semaphore
2. Waits for nothing, signals value `x+1` of our semaphore, finishes first

We might have the first submission still executing by the time the second one finishes and advances the semaphore value to `x+1`. If we then observe the semaphore value to be `x+1`, we would retire state of the first submission too, which would be incorrect.

But if this is indeed a valid concern, the layers are already violating this for `vkWaitSemaphores`, so the change I mentioned won't make it more fragile than it is already.

**Comment by farnoy** [comment]
OK nevermind, I found an answer later on in the same section:
> Because the first synchronization scope for a semaphore signal operation contains all semaphore signal operations which occur earlier in submission order, all semaphore signal operations contained in any given batch are guaranteed to happen-after all semaphore signal operations contained in any previous batches

So this seems like the right way to do it. And looking at `RetireTimelineSemaphore`, it finds the most recent submission (in submission order) that is safe to be retired, so it should be solid.

**Comment by mark-lunarg** [comment]
@farnoy, thanks a lot -- timeline semaphores have been a murky and troublesome area for us, and it's nice to have some clarity!

**Comment by coki04** [comment]
It looks like it became idle. Thus I submitted PR #2196 targetting this issue as discussed here.
Tested it on my application and it solves false positive validation error.

**Comment by mark-lunarg** [comment]
Should be addressed by #2196, thanks!
