### ISSUE TITLE
pSizes[i] = VK_WHOLE_SIZE not handled correctly in vkCmdBindTransformFeedbackBuffersEXT

### ISSUE THREAD

**Issue by brianpaul** [KhronosGroup/Vulkan-ValidationLayers#2105]
The Vulkan spec says that values in the pSizes[] array passed to vkCmdBindTransformFeedbackBuffersEXT() may be VK_WHOLE_SIZE.  But the validation check at core_validation.cpp:1292 doesn't handle that.  The current code reads:

   if (pSizes[i] > buffer_state->createInfo.size) {

It should probably be:

   if (pSizes[i] != VK_WHOLE_SIZE && pSizes[i] > buffer_state->createInfo.size) {

as is done a few lines later for checking if offset + size > buffer size.

**Comment by sfricke-samsung** [comment]
1. ` core_validation.cpp:1292` in ToT  doesn't seem to point to this (but found the spot anyway)
2. Agree the spec allows `VK_WHOLE_SIZE`
3. The issue is really the spec Valid Usage `VUID-vkCmdBindTransformFeedbackBuffersEXT-pSizes-02362`

> All elements of pSizes must be less than or equal to the size of the corresponding buffer in pBuffers

should be

> All elements of pSizes, where the element is not `VK_WHOLE_SIZE`, must be less than or equal to the size of the corresponding element in pBuffers

----

I will make the internal proposal to fix that VUID in the spec, @mark-lunarg can decide on the immediate action
