### ISSUE TITLE
Migrate from STD to Abseil

### ISSUE THREAD

**Issue by tobine** [KhronosGroup/Vulkan-ValidationLayers#2188]
@timvpGoogle migrated ANGLE from using some STD containers to using the [abseil](https://github.com/abseil/abseil-cpp) equivalent types. This fixed a number of issues where STD library calls were being hit as hotspots.
Putting this out as a suggestion to do a similar migration in validation layers as I know that STD containers have previously been hot-spots for various workloads.

**Comment by mark-lunarg** [comment]
Moving this to the performance tracking issue #1001, and pinging @karl-lunarg and @Tony-LunarG.

**Comment by karl-lunarg** [comment]
The Abseil [compatibility documentation](https://abseil.io/about/compatibility) suggests that Abseil cannot reliably be used in dynamically-loaded libraries.  In particular:

* Do not rely on dynamic unloading. We consistently use patterns that may not be friendly to dynamic unloading of shared libraries. We make no claims that any of this code is usable in a system with regular unloading of such libraries.
* Not all Abseil libraries are suitable for dynamic loading. Some libraries have startup/initialization requirements and may not be suitable for dynamic loading. We will try to be clear about which libraries are OK for dynamic loading. However we don’t generally deploy code in this fashion, mistakes are possible, and the normal argument of “This code is production hardened” does not apply in such usage.

A quick experiment confirmed these restrictions.

@tobine, if you have any further insights or solutions for using this in the layer, please let us know.  Otherwise, we won't be planning on using this library.
