### ISSUE TITLE
vkSignalSemaphore() payload change seems to be ignored by validation layers.

### ISSUE THREAD

**Issue by Noxagonal** [KhronosGroup/Vulkan-ValidationLayers#2272]
Hey.
So basically vkSignalSemaphore() doesn't report setting value backwards, and trying to submit with a timeline semaphore which value is higher than the VkTimelineSemaphoreSubmitInfo::pSignalSemaphoreValues, it should report about it but doesn't.

I put up a minimal VS project here as a zip if needed.

[VulkanTimelineSemaphoreTest.zip](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/5455467/VulkanTimelineSemaphoreTest.zip)

**Comment by Noxagonal** [comment]
Using Vulkan SDK 1.2.154.1

**Comment by sfricke-samsung** [comment]
For the record, the 2 VUs in play here are

> VUID-VkSemaphoreSignalInfo-value-03258
>
> value must have a value greater than the current value of the semaphore

and

> VUID-VkSemaphoreSignalInfo-value-03259
> 
> value must be less than the value of any pending semaphore signal operations

Both of which have coverage and a test for them

**Comment by sfricke-samsung** [comment]
@Noxagonal ... so found the problem... so when the layers were updated to Vulkan 1.2, the `PreCallValidateSignalSemaphoreKHR()` never turned into an "overloadded" `PreCallValidateSignalSemaphore()` version (actually only for CoreChecks it got missed)

So sure enough if I changed the `InvalidSignalSemaphoreValue` test to use `vkSignalSemaphore()` instead of `vkSignalSemaphoreKHR()` it never gets into `CoreChecks::PreCallValidateSignalSemaphoreKHR()` where the validation code is.

Let me quick write a patch up and get this up soon... I also want to make sure we didn't miss any other functions when up in the 1.2 migration

Thanks for pointing this out and giving the code snippet to help me debug this
