### ISSUE TITLE
VK_LAYER_KHRONOS_validation causing memory corruption

### ISSUE THREAD

**Issue by jzulauf-lunarg** [KhronosGroup/Vulkan-ValidationLayers#2429]
From Rene Lindsay [LunarXchange -- 1001](https://vulkan.lunarg.com/issue/view/5fe404bf5df112bcbc11ae67)

**Describe the Issue**
My application has a main rendering pipeline, which uses either rasterization or raytracing to render to the display, while a second pipeline can be triggered to raytrace images to an off-screen buffer, for output to a file. (Texture baking). The app runs fine, but when I try to close it down, the app crashes with the following error:

corrupted double-linked list

The crash happens as soon as I call vkDestroyPipeline(), and the app immediately exits without cleaning up resources. The error message appears to be malloc related, and comes from glibc, so its probably a heap overflow?

However, the crash only occurs if I've rendered to both pipelines,
AND I have the "VK_LAYER_KHRONOS_validation" layer enabled.
If I disable validation, everything runs fine, and all resources are cleaned up correctly, before exit.

**Valid Usage ID**
N/A

**Environment:**
 - OS: Ubuntu 18.04.5 LTS
 - GPU: NVidia GeForce RTX 2080 Ti
 - SDK or header version if building from repo: 1.2.162.0
 - Options enabled (synchronization, best practices, etc.): VK_LAYER_KHRONOS_validation

**Additional context**
none.

**Comment by jzulauf-lunarg** [comment]
At first blush we could have a double free in the clean up somewhere (a unique_ptr where a shared_ptr was needed, or a plain point not null'd out.

However, arena corruption can also happen in mutli-threaded applications during uncontrolled shutdown on an assert -- so the corruption could be symptom instead of cause.

**Comment by mark-lunarg** [comment]
@jzulauf-lunarg, we'll need a list of any validation messages that were generated before the shutdown/crash, and a repro case.

**Comment by rjklindsay** [comment]
Hi John. Yes, a double free could definitely cause this.  The error happens regardless of whether I run the app in single-threaded or multi-threaded mode.
Since it only happens when validation layers are enabled AND multiple pipelines (and renderpasses+swapchains+...) are used, I'm wondering if validation is getting its internal handles confused, and maybe deleting the wrong object instance?

Mark:  Validation layers did not print any ERROR or WARNING messages during the execution of the app, only the usual list of DEBUG messages at startup.
When I close the app, with validation layers enabled, it prints the following log messages: (These are my own log messages, not generated by Validation layers)
Unfortunately, the app is not open-source, so I can't send the code, but here is the output log, (if that helps)

[LunaRay Log.txt](https://github.com/KhronosGroup/Vulkan-ValidationLayers/files/5748975/LunaRay.Log.txt)

With validation layers enabled, if I close the app, it fails while deleting the first pipeline:

```
INFO : Closing Window
INFO : FBO destroyed
corrupted double-linked list
Press <RETURN> to close this window...
```

If I turn validation layers OFF, it prints this:

```
INFO : Closing Window
INFO : FBO destroyed
INFO : Renderpass destroyed
INFO : Swapchain destroyed
INFO : FBO destroyed
INFO : Renderpass destroyed
INFO : VMA Allocator destroyed
INFO : Logical device destroyed
INFO : Vulkan Surface destroyed
INFO : Vulkan Instance destroyed
Press <RETURN> to close this window...
```

**Comment by mark-lunarg** [comment]
Hi Rene!  Any chance you can run it through Valgrind and share the results?  You are the lucky first person to find this issue!

**Comment by jzulauf-lunarg** [comment]
@rjklindsay  -- or any way to get a replay of a simple test case?

**Comment by rjklindsay** [comment]
Hi Mark. Long time no see. :)    Sure I'll try Valgrind, and get back to you if/when I find new insights.
John: I heard you guys are working on a replacement for the old trace/replay tool. Is that right?
Which tool is currently the preferred option?

**Comment by jzulauf-lunarg** [comment]
@rjklindsay  -- gfxreconstruct is the preferred tool.

**Comment by mark-lunarg** [comment]
Hey @rjklindsay, know things are busy -- any updates at all about valgrind results?

**Comment by rjklindsay** [comment]
The issue was resolved when I upgraded to the latest SDK. 
Thank you guys.
Rene

**Comment by ncesario-lunarg** [comment]
Closing at it looks like this is resolve. @rjklindsay please re-open if that is not the case.
