### ISSUE TITLE
Attempting to enable extension VK_EXT_debug_utils, but this extension is intended to support the following uses: use by applications when debugging

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/Vulkan-ValidationLayers#2509]
**Describe the Issue**
I'm running my renderer with the best practices layer during development, and using the debug utils extension to name my objects. The best practices layer is telling me that I should only use the debug utils extension during application debugging... which is exactly what I'm doing

I guess the point of this message is to tell people to not use the debug utils extension in a shipping build? But even then there's a valid use case - for instance, a game engine like Unity naming its API objects to help game developers debug GPU-related problems. I'm not sure what useful information this message is intending to convey

**Valid Usage ID**
UNASSIGNED-BestPractices-vkCreateInstance-specialuse-extension 

**Environment:**
 - OS: Windows 10
 - GPU: RTS 2080 Super
 - SDK or header version if building from repo: Prebuilt LunarG SDK 1.2.162.1
 - Options enabled (synchronization, best practices, etc.): Synchronization, best practices

**Additional context**
Full message:
```
[2021-01-28 16:50:35.215] [VulkanBackend] [warning] [Validation]   Objects: Instance (0) Validation Warning: [ UNASSIGNED-BestPractices-vkCreateInstance-specialuse-extension ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_INSTANCE; | MessageID = 0x2dc65ef4 | CreateInstance(): Attempting to enable extension VK_EXT_debug_utils, but this extension is intended to support the following uses: use by applications when debugging, and it is strongly recommended that they be otherwise avoided.
```

**Comment by mark-lunarg** [comment]
@DethRaid, the best practices can be spammy this way, since they don't know (and can't know) your intent.  All BP checks are for things that are technically legal, and these 'specialuse' designations come directly from the spec and were added by the Vulkan Working Group specifically for this purpose.  If these messages are interfering with your workflow, you can suppress these or other messages using the [khronos_layer.message_id_filter layer setting](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/vk_layer_settings.txt) or the `VK_LAYER_MESSAGE_ID_FILTER `environment variable.
