### ISSUE TITLE
Validation layer complains about correct std140 Uniform Buffer layout

### ISSUE THREAD

**Issue by danielmaciel** [KhronosGroup/Vulkan-ValidationLayers#252]
The struct 'S' is a perfectly valid std140 layout
struct S
{
    mat4 m1;
    mat4 m2;
    mat4 m3;
    vec3 v;
    float f;
};
But when trying to use it I get a warning:

UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: -1 - SPIR-V module not valid: Structure id 13 decorated as Block must follow standard uniform buffer layout rules: member 4 at offset 204 overlaps previous member ending at offset 207
  OpFunctionEnd

    Objects: 1
       [0] 0x0, type: 0, name: (null)

Which is incorrect for this struct.
The fact that vec3 has a 16-byte alignment does not mean it *requires* padding, it just means that it needs to be at at 16-byte alignment boundary. The extra padding may (and is encouraged to) be used by another 4-byte aligned variable (a float in this case).

**Comment by danielmaciel** [comment]
OK thanks!

**Comment by danielmaciel** [comment]
"By the rules of std140, each vec3 must *start* on a 16-byte boundary. But vec3 *does not consume 16 bytes of storage; it only consumes 12*. And since float can start on a 4-byte boundary, a vec3 followed by a float will take up 16 bytes."

**Comment by danielmaciel** [comment]
As seen in the linked issue, the real problem is that glslang is using an older version of the spirv-tools that does not contain the fix yet.

**Comment by karl-lunarg** [comment]
LunarG has released [SDK Version 1.1.82.1](https://vulkan.lunarg.com/sdk/home) to address this problem.

**Comment by Ralith** [comment]
Is the fix published in source form anywhere? I'd like to update my distro's packages, but I don't see a tag or branch for 1.1.82.1.

**Comment by karl-lunarg** [comment]
The Vulkan SDK includes the contents of this repository, but this repository has dependencies on several other repositories.  The delta between the 1.1.82.0 and 1.1.82.1 SDKs involves picking a later revision of one of these dependent repositories for the 1.1.82.1 SDK.  This repository, SPIRV-Tools, is not a "Vulkan" repository and is used by other projects than Vulkan.  So we don't tag SPIRV-Tools with Vulkan-specific tags.

I don't know how you build this repository for your distro, but in some way, you must be determining a revision of SPIRV-Tools to use when you build this repo.  The 1.1.82.0 SDK used revision 9ecbcf5 and 1.1.82.1 used version 1a283f4 to pick up the SPIRV-Tools fix for this issue.

**Comment by Ralith** [comment]
> This repository, SPIRV-Tools, is not a "Vulkan" repository and is used by other projects than Vulkan. So we don't tag SPIRV-Tools with Vulkan-specific tags.

Github seems to think this is the Vulkan-ValidationLayers repo. Maybe you were thinking of https://github.com/KhronosGroup/SPIRV-Tools/issues/1734?

> I don't know how you build this repository for your distro, but in some way, you must be determining a revision of SPIRV-Tools to use when you build this repo.

I use the revision of glslang specified in scripts/known_good.json, which in turn uses the versions of spirv-tools and spirv-headers defined in its own known_good.json files. I can't find changes to any of these for 1.1.82.1.

**Comment by karl-lunarg** [comment]
>Github seems to think this is the Vulkan-ValidationLayers repo. Maybe you were thinking of KhronosGroup/SPIRV-Tools#1734?

The "This" in "This repository" was referring to the dependent repo mentioned in the previous sentence.

> I use the revision of glslang specified in scripts/known_good.json, which in turn uses the versions of spirv-tools and spirv-headers defined in its own known_good.json files. I can't find changes to any of these for 1.1.82.1.

We publish the revisions actually used to build the SDKs in the SDK [release notes](https://vulkan.lunarg.com/doc/sdk/1.1.82.1/linux/release_notes.html).  In general, these revisions come from the known_good files.  In this case, we needed a custom revision of SPIRV-Tools.  This custom revision (1a283f4) doesn't appear in any of glslang's known_good files, at any glslang revision.  So, we had to fork glslang and modify its known_good to point to SPIRV-Tools 1a283f4.  If you follow the [Glslang library and tools](https://github.com/lenny-lunarg/glslang/commit/c7f4e818ac55f545289f87f8c37571b2eadcde86) link in the Release Notes, you'll find that it leads to the correct custom SPIRV-Tools revision.

If the above information isn't sufficient or if you really need something in this (Vulkan-ValidationLayers) repo, we add a commit to the sdk-1.1.82 branch and tag it with 1.1.82.1.  This commit would contain a change to the known-good file in this repo to point to our glslang fork.  We were a bit reluctant to do this because of the reference to a forked repo.

**Comment by Ralith** [comment]
Got it, thanks! The release notes will be sufficient; consistent tagging/known_good.json usage would make my life easier in the future, but I can bodge this release manually.
