### ISSUE TITLE
vkCmdWriteAccelerationStructuresPropertiesNV incorrect errors with KHR flags - a common validation bug

### ISSUE THREAD

**Issue by Nimanf** [KhronosGroup/Vulkan-ValidationLayers#2556]
**Describe the Issue**
This is very common every time that Vulkan SDK promotes an extension to a KHR extension, we start getting incorrect errors of flags for previous VK_NV/VK_EXT extensions.

Issue: Running an app with `vkCmdWriteAccelerationStructuresPropertiesNV` that uses `VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_NV` flag now generates incorrect errors. Using a newer extension should not cause older extensions to generate errors based on KHR with SDK 1.2.162.1.

- Is there a strategy that validation layers can use to prevent this from happening that frequently? Some kind of unit test?
- Once we wait for months on all the bugs to be fixed, another old extension will be promoted to KHR and we get more new invalid errors. These bugs consistently generate thousands of errors, and have to filter them one by one based on ID.

**Valid Usage ID**
` ERROR:Validation: ID: VUID-vkCmdWriteAccelerationStructuresPropertiesNV-queryType-03432, message: Validation Error: [ VUID-vkCmdWriteAccelerationStructuresPropertiesNV-queryType-03432 ] Object 0: handle = 0x17edc6331f8, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xb9d6de38 | vkCmdWriteAccelerationStructuresPropertiesNV: queryType must be VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR or VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR. The Vulkan spec states: queryType must be VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR or VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR (https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-vkCmdWriteAccelerationStructuresPropertiesNV-queryType-03432)`

**Environment:**
- OS: Windows 10, 1909
- GPU: RTX 2080 TI
- SDK or header version if building from repo: SDK 1.2.162.1

Thanks a lot

**Comment by mikes-lunarg** [comment]
Thanks for the report! The 1.2.162 spec actually mandated that check, from https://vulkan.lunarg.com/doc/view/1.2.162.1/windows/1.2-extensions/vkspec.html#VUID-vkCmdWriteAccelerationStructuresPropertiesNV-queryType-03432:

> - VUID-vkCmdWriteAccelerationStructuresPropertiesNV-queryType-03432
queryType must be VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR or VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR

This is a case of a bug in the specification making it through to validation. The spec was fixed with the 167 header, and validation shortly after. VK_KHR_ray_tracing was also a little more complicated because it wasn't a direct promotion of VK_NV_ray_tracing but it does reuse some parts of that extension. This added some interactions between the two extensions, both in how they are specified and validated. The more common promotion workflow is much closer to a "rename".

I'm not sure the issue here can be generalized to a wider problem with validation and promoted extensions. I would be interested in some other examples to see if there is something we can do better. Also, don't hesitate to file issues for those incorrect errors you are ignoring. We do have tests on many of the validation checks (admittedly, not `03432`) but I don't know if it would have helped here since the spec itself was incorrect. There is also already a process in place to detect when spec changes impact existing validation, which is why it is already fixed.

**Comment by Nimanf** [comment]
> I would be interested in some other examples to see if there is something we can do better.

Another case was when `VK_EXT_buffer_device_address `was promoted to `VK_KHR`.
`VK_KHR `version added some new flags not existing in `VK_EXT`, and they were being mistakenly required by `VK_EXT `validation layers during every allocation for a while. it was fixed in the future validation releases.

Such bugs are at least easy to filter by ID, but cases like **timeline** semaphores have been very challenging for us. There is no way to filter them by ID or prevent them from being reported, as it breaks the state tracking everywhere. (e.g. `vkWaitSemaphoresKHR()` vs. `vkWaitSemaphores()` changes that was defined internally by validation layers)
I was told that the latest validation layers finally resolved them, after they got promoted from KHR to core 1.2, and it went through multiple stages to get fixed. 

Thanks again.
