### ISSUE TITLE
depth format compatiblity validation is missing

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/Vulkan-ValidationLayers#2631]
**Describe the Issue**
"42.1.6. Format Compatibility Classes

Uncompressed color formats are compatible with each other if they occupy the same number of bits per texel block. Compressed color formats are compatible with each other if the only difference between them is the numerical type of the uncompressed pixels (e.g. signed vs. unsigned, or SRGB vs. UNORM encoding). Each depth/stencil format is only compatible with itself. In the following table, all the formats in the same row are compatible."

The line each depth/stencil format is only compatible with itself doesn't appear to be validated.

It means validation allows creating a D32_FLOAT image view of a D32_FLOAT_S8_UINT image which my by reading is against the spec.

**Comment by sfricke-samsung** [comment]
The Validation Layers have a `vk_format_uilts.cpp` that handles all of this and these 2 formats are listed as

```cpp
{VK_FORMAT_D32_SFLOAT,                  {4, 1, VK_FORMAT_COMPATIBILITY_CLASS_NONE_BIT}},
{VK_FORMAT_D32_SFLOAT_S8_UINT,          {8, 2, VK_FORMAT_COMPATIBILITY_CLASS_NONE_BIT}},
```

But I just wrote a test and I see the issue is

```
if (FormatCompatibilityClass(image_format) != FormatCompatibilityClass(view_format)) {
```

is passing because they are both the same...but you are correct, it needs to properly handle the case they are both "only compatible with itself"
