### ISSUE TITLE
syncval: Validation error with resolve attachments

### ISSUE THREAD

**Issue by ShabbyX** [KhronosGroup/Vulkan-ValidationLayers#2636]
Take the following scenario:

1. Begin render pass
   - Subpass has resolve attachments
   - Final layout of resolve attachments is SHADER_READ_ONLY_OPTIMAL
2. End render pass
3. Dispatch compute call that reads from resolve attachments as sampled image

Between steps 2 and 3, I have added a global memory barrier:

```
	const VkMemoryBarrier barrier =
	{
		VK_STRUCTURE_TYPE_MEMORY_BARRIER,
		nullptr,
		VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
		VK_ACCESS_SHADER_READ_BIT,
	};

	vkCmdPipelineBarrier(cmdBuffer,
		VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,
		VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, 0, 1, &barrier, 0, nullptr, 0, nullptr);
```

According to spec, color resolve happens at COLOR_ATTACHMENT_OUTPUT stage with access COLOR_ATTACHMENT_WRITE. However, syncval produces the following error:

```
Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x170000000017, type = VK_OBJECT_TYPE_IMAGE_VIEW; | MessageID = 0x4cb75b2d | vkCmdDispatch: Hazard READ_AFTER_WRITE for VkImageView 0x170000000017[], in VkCommandBuffer 0x5649200ed370[], and VkPipeline 0x500000000050[], VkDescriptorSet 0x4d000000004d[], type: VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, imageLayout: VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, binding #3, index 0. Access info (usage: SYNC_COMPUTE_SHADER_SHADER_READ, prior_usage: SYNC_IMAGE_LAYOUT_TRANSITION, write_barriers: 0, command: vkCmdEndRenderPass, seq_no: 37, reset_no: 1).
```

If I add `VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT` to `srcStageMask`, the error goes away. Is this a bug in syncval or my understanding of the spec?

I'm guessing this has something to do with the stage the final layout transition is applied in, but I can't seem to find wording in spec that would specify which stage that is.

**Comment by jeremyg-lunarg** [comment]
Do you have a subpass dependency with dstSubpass set to VK_SUBPASS_EXTERNAL? If not, the final image layout transition of your renderpass will be synchronized with the implict subpass dependency described in chapter 8 of the spec:
```
VkSubpassDependency implicitDependency = {
    .srcSubpass = lastSubpass; // Last subpass attachment is used in
    .dstSubpass = VK_SUBPASS_EXTERNAL;
    .srcStageMask = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT;
    .dstStageMask = VK_PIPELINE_STAGE_NONE_KHR; (or VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT)
    .srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT |
                     VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
    .dstAccessMask = 0;
    .dependencyFlags = 0;
};
```
Because of the dstStageMask of this implicit dependency, any pipeline barrier after the renderpass will need include BOTTOM_OF_PIPE_BIT, as you've found,  in order to have a correct  dependency chain. You'll be much better off to add your own subpass dependency and to make it act as the pipeline barrier you need before your compute commands. That is, include VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT in the subpass dstStageMask and VK_ACCESS_SHADER_READ_BIT in the dstAccessMask.

Hopefully that will fix your problem, but let me know if not!

**Comment by ShabbyX** [comment]
Thanks for clarifying. It was not easy to make that connection.
