### ISSUE TITLE
Null pointer dereference in state tracker in PreCallRecordCmdBindPipeline

### ISSUE THREAD

**Issue by Tony-LunarG** [KhronosGroup/Vulkan-ValidationLayers#2770]
**Describe the Issue**
With the merge of #2749 (VK_NV_inherited_viewport_scissor coverage) the CTS test dEQP-VK.api.descriptor_set.descriptor_set_layout_lifetime.graphics run with validation dereferences a null pointer in state_tracker.cpp, line 3811/3812 where pipe_state->graphicsPipelineCI.pViewportState is NULL.  The test did not get any validation errors in previous runs.

**Environment:**
 - OS: Windows 10
 - GPU: GeForce RTX 2080
 - SDK or header version if building from repo: 44139b17
 - Options enabled (synchronization, best practices, etc.): KHRONOS_validation

**Comment by ncesario-lunarg** [comment]
@akeley98NV could you please take a look?

**Comment by akeley98NV** [comment]
Sure. I am *really bad* at running vulkancts so I may report back asking for help reproducing the issue, but I'll make an independent attempt today or tomorrow. It looks like the fix is pretty trivial at first glance (just skip all this stuff when rasterization disabled) but I am not 100% sure this is the correct course of action as I've never disabled rasterization before ... this means that the pipeline is just used for transform feedback (or whatever the modern equivalent is), right, and doesn't interact with the viewport state at all?

**Comment by akeley98NV** [comment]
Separate from vulkancts, are there any Vulkan-ValidationLayer test cases that exercise this code with rasterization disabled?

**Comment by akeley98NV** [comment]
For efficiency's sake, tried to take care of this issue w/o reproducing: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2776

**Comment by akeley98NV** [comment]
Decided to take the only truly moral course of action and repro the issue in running vulkancts myself (which was way easier than I remembered from last time, probably because I wasn't trying to patch in a custom extension this time), I think I've fixed the issue properly this time (look at VkPipelineRasterizationStateCreateInfo::rasterizerDiscardEnable) but could use the eyeballs of someone with experience in no-rasterization pipelines. Did a crude test with this: https://github.com/akeley98NV/VK-GL-CTS/commit/21d9f01031515737435ccf091cc4c7caf77a661a (basically, we should not rely on pViewportState being null when rasterization disabled; it could be left as any garbage value by the spec).

**Comment by ncesario-lunarg** [comment]
> this means that the pipeline is just used for transform feedback (or whatever the modern equivalent is), right, and doesn't interact with the viewport state at all?

I'm not sure what all of the use cases are, but I think #2776 looks correct w.r.t. the spec.

**Comment by Tony-LunarG** [comment]
#2776 fixed it - thanks!
