### ISSUE TITLE
vk_layers_settings not complete in VulkanSDK 1.1.82.0

### ISSUE THREAD

**Issue by dor666** [KhronosGroup/Vulkan-ValidationLayers#280]
There seems to be some issue in merged vk_layer_settings.txt in latest SDK.
After installation this is [my vk_layer_settings.txt](https://gist.github.com/dor666/b4e393b989b74775a1b0ff2222e75ba4)

Compare it [to this](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/vk_layer_settings.txt) version on master, and you will see missing section of "Validation Layer Common Settings", and no "VK_LAYER_LUNARG_core_validation Settings"

It seems to be badly merged with VK_LAYER_LUNARG_api_dump settings.

**Comment by mark-lunarg** [comment]
Hey @lenny-lunarg, can you fix this if it's Windows, or reassign to @johnzupin if Linux (or JeremyK for mac).  Thanks!

**Comment by lenny-lunarg** [comment]
I've gone and fixed this bug in our SDK build system, internally. As a result, this should be fixed in the next SDK that we release. For the time being, you should be able to get all of the missing content in that file from this repo &mdash; specifically from [this file](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/layers/vk_layer_settings.txt).

I'm going to close the issue, since it is fixed in our build system.
