### ISSUE TITLE
Waiting on a Submit-Fence will not cause SecondaryCommandBuffers to transition from "Pending" back to the "Invalid" or "Execuatable" state

### ISSUE THREAD

**Issue by MaikBusch78** [KhronosGroup/Vulkan-ValidationLayers#283]
Submitting a primary CommandBuffer with a Fence will cause this CmdBuffer to transition from Pending to Invalid/Executable state with successful waiting on the Fence given during submition.

Secondary Command Buffers that are executed from within a Primary Command Buffer should also transition from Pending to Invalid/Executable state with successful wait on the Fence given with the submition of the Primary Buffer.

The Spec states in Chapter 5.1.  "... if the primary is submitted to a queue, both the primary and any secondaries recorded to it move to the pending state. Once execution of the primary completes, so does any secondary recorded within it, and once all executions of each command buffer complete, they move to the executable state."

This Bug causes a false positive Validation Error for Secondary Command Buffers: "Error:  [ VUID-vkResetCommandBuffer-commandBuffer-00045 ] Object: 0x1f1b9350c48 (Type = 6) | Attempt to reset command buffer (0x1f1b9350c48) which is in use. The spec valid usage text states 'commandBuffer must not be in the pending state' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkResetCommandBuffer-commandBuffer-00045)"

**Comment by jzulauf-lunarg** [comment]
@MaikBusch78 -- looking our code, secondary command buffers are set to executable at the same time as the primary. However, we only treat fences as signaled during vkWaitForFences if:

1. The result is VK_SUCCESS
2. waitAll is TRUE or fenceCount == 1

Otherwise, we cannot prove that any given fence in pFences has been signaled (nor can the caller), and do not update the state of resources, queues, and command buffers. We look at vkGetFenceStatus results to update our internal state, when the fence status is signaled. 

If you aren't meeting the criteria above and/or following up with vkGetFenceStatus, this would be a correct error message.

Can you confirm the details of the vkWaitForFences call, or provide a reproduction case for this issue?

**Comment by mark-lunarg** [comment]
@MaikBusch78, any issue here with the correctness of the validation would be a very high priority for us.  Thanks in advance for any additional/clarifying information!

**Comment by MaikBusch78** [comment]
Mark, please give me a few days to provide additional infos.

**Comment by MaikBusch78** [comment]
This Bug-Report was my mistake.

I am having a fence for every swapchain-index, and I submit all commands at once. I am waiting on each fence before I prepare the commands for the current frame. But I did not see, that I am preparing the primary command buffers after waiting on the fence but the secondary command buffers before I have waited on the fence. I observed that the primary command buffer have been resetted correctly, so I deduced - wrongly - that the secondary failed to be resetted.
