### ISSUE TITLE
Sus QFOT pipeline stage validation code

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#2888]
This code handling queue family ownership transfer looks suspicious to me:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/ae3d0c3217316cd0364d4b9069d0e2afac5957b1/layers/core_validation.cpp#L7781..L7786

```
if (op_type == kAllRelease || op_type == kGeneral) {
    skip |= ValidatePipelineStage(objects, loc.dot(Field::srcStageMask), queue_flags, srcStageMask);
}
if (op_type == kAllAcquire || op_type == kGeneral) {
    skip |= ValidatePipelineStage(objects, loc.dot(Field::dstStageMask), queue_flags, dstStageMask);
}
```

Validation of stage flags should not be skipped. Only access flags checking should be skipped on the particular struct that includes QFOT.

**Comment by jeremyg-lunarg** [comment]
It looks like the code ended up this way because of earlier wording in the spec about the acquire and release barriers needing to be 'the same'.   (for context: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2015)

I can't find anything in the current spec which says that the stage flags should be ignored.  So, I'm going to  run some tests here with this checking (and the synchronization2 equivalent) changed to see how much it'll change validation results.

**Comment by jeremyg-lunarg** [comment]
My test change didn't seem to affect validation of our game replays. I was slightly worried we'd get a flood of VUID-vkCmdPipelineBarrier-*-4098 errors but we didn't.  The [CTS test cases for qfot](https://github.com/KhronosGroup/VK-GL-CTS/blob/master/external/vulkancts/modules/vulkan/synchronization/vktSynchronizationOperationMultiQueueTests.cpp#L334) also look like they won't be affected.

**Comment by krOoze** [comment]
If they did, that would also be a good thing. Would mean the layers do their job and found invalid usages for some users...

**Comment by jeremyg-lunarg** [comment]
> If they did, that would also be a good thing. Would mean the layers do their job and found invalid usages for some users. If anything it makes me paranoid that nothing was found...

I agree, but if there were suddenly thousands of new errors we'd need to be a bit more careful about rolling it out and warning people. There were validation unit test cases that I had to update to remove errors though.
