### ISSUE TITLE
GetLayerEnvVar() function unnecessarily changes layer_config.vk_layer_disables_env_var

### ISSUE THREAD

**Issue by shakti-hub** [KhronosGroup/Vulkan-ValidationLayers#3048]
**Describe the Issue**
GetLayerEnvVar() function unnecessarily changes layer_config.vk_layer_disables_env_var

**Valid Usage ID**
NA

**Environment:**
 - OS: ANY
 - GPU: ANY

**Additional context**
GetLayerEnvVar() function should read the environment value of the given string with call to GetEnvironment().
This should copied into a temp string and it should return the value of the temp string.

<VK_LAYER_EXPORT const char *GetLayerEnvVar(const char *option) {

    layer_config.vk_layer_disables_env_var = GetEnvironment(option);

    return layer_config.vk_layer_disables_env_var.c_str();

}>

**should be changed to:**

<VK_LAYER_EXPORT const char *GetLayerEnvVar(const char *option) {

    string env_var = GetEnvironment(option);

    return env_var.c_str();
}>

**Comment by ncesario-lunarg** [comment]
It's definitely a little suspect that we're returning a pointer to a string that is going to change later. Looks like this was done since GetLayerEnvVar is exported and we're avoiding returning a C++ object.

If this function still _really_ needs to be exported (I don't have the knowledge yet to know whether that's true or not), then I would vote for adding some comments/documentation that makes it clear the value returned by `GetLayerEnvVar` is _temporary_ and should be copied immediately after the function returns. We could also change the function signature to something along the lines of `char*` pointers and a length, but that seems more complicated than necessary for a utility function like this. Unfortunately, I don't think the proposed change will work, as it looks like that is returning a pointer to memory that will be freed before the function finishes returning.

If this function does _not_ need to be exported (again, I don't know that for sure yet), then it looks like this function should just be replaced by `GetEnvironment`.

FYI @mark-lunarg @Tony-LunarG @jeremyg-lunarg @ziga-lunarg.

**Comment by jeremyg-lunarg** [comment]
I agree with the proposed fix. Its possible that layer_config.vk_layer_disables_env_var will need to be set in a more appropriate way, outside of this funciton.

**Comment by jeremyg-lunarg** [comment]
Ugh. I agree that I need more coffee, I totally missed the temporary storage problem.
