### ISSUE TITLE
Access violation in ValidateCmdBeginRenderPass

### ISSUE THREAD

**Issue by kikijiki** [KhronosGroup/Vulkan-ValidationLayers#3097]
**Describe the Issue**

I had some code incorrectly call `vkCmdBeginRenderPass2` without passing any clear value, even if some attachment was specifying a clear operation.

In `core_validation.cpp` the check `if (clear_op_size > pRenderPassBegin->clearValueCount)` happens after `ValidateClearDepthStencilValue`, which tries to access a null `pRenderPassBegin->pClearValues[i]` with no checks.

This causes an access violation.

**Environment:**
 - OS: Windows 10.0.19043
 - GPU: Ryzen 5 4600H APU
 - SDK or header version if building from repo: VK_HEADER_VERSION 185
 - Options enabled (synchronization, best practices, etc.):

**Additional context**

**Comment by sfricke-samsung** [comment]
some background: There normally an implicit VU to say something like

> "if `clearValueCount` is not 0, it must be a valid pointer to `pClearValues`"

and this gets auto generated and would have been caught there. The issue is `VkClearValue` is a union so there is a special `noautovalidity` in the XML. I recently got `VUID-VkRenderPassBeginInfo-clearValueCount-04962` (and `VUID-vkCmdClearColorImage-pColor-04961`, for that matter) added to the spec and the "real issue" is that it wasn't there catching this before it got into `core_validation.cpp`

So for this case (and the `vkCmdClearColorImage` while at it tbh) there needs to be a manual check (the 2 VUIDs I listed above) to prevent this access violation
