### ISSUE TITLE
Allow AHARDWAREBUFFER_FORMAT_IMPLEMENTATION_DEFINED

### ISSUE THREAD

**Issue by zhangyiwei** [KhronosGroup/Vulkan-ValidationLayers#3155]
**Describe the Issue**
`VUID-VkImportAndroidHardwareBufferInfoANDROID-buffer-01881` currently complains about`AHARDWAREBUFFER_FORMAT_IMPLEMENTATION_DEFINED`.

**Valid Usage ID**
> ERROR: [Validation] Code 0 :  [ VUID-VkImportAndroidHardwareBufferInfoANDROID-buffer-01881 ] Object: 0x7afa5eefdf00 (Type = 3) | vkAllocateMemory: The AHardwareBuffer_Desc's format ( 34 ) and/or usage ( 0x20130 ) are not compatible with Vulkan. The Vulkan spec states: If buffer is not NULL, it must be a valid Android hardware buffer object with AHardwareBuffer_Desc::format and AHardwareBuffer_Desc::usage compatible with Vulkan as described in Android Hardware Buffers. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImportAndroidHardwareBufferInfoANDROID-buffer-01881)

@chrisforbes @critsec

**Comment by sfricke-samsung** [comment]
What version of the validation layers are you using, the current layers have a different message over [a year ago](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/f48ad4ad2aba23939a3499c41393e0fab94bbe9e) and since I made various fixes to the AHB part of the validation layers

**Comment by zhangyiwei** [comment]
Sure, that's an old one, but as I checked the latest VVL source code, it still doesn't handle `AHARDWAREBUFFER_FORMAT_IMPLEMENTATION_DEFINED` (though it adds support for blob format now).

**Comment by sfricke-samsung** [comment]
so I guess looking more at it, I never have seen `AHARDWAREBUFFER_FORMAT_IMPLEMENTATION_DEFINED` before, I know there is the language that says

> If the parameters define an import operation and the external handle type is VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID, and the pNext chain does not include a VkMemoryDedicatedAllocateInfo structure or VkMemoryDedicatedAllocateInfo::image is VK_NULL_HANDLE, the Android hardware buffer must have a AHardwareBuffer_Desc::format of AHARDWAREBUFFER_FORMAT_BLOB and a AHardwareBuffer_Desc::usage that includes AHARDWAREBUFFER_USAGE_GPU_DATA_BUFFER

So I assume this issue is when there is a dedicated image info object... I think the issue is the spec never talks about `IMPLEMENTATION_DEFINED` and it never came up but I can't find anything in the spec that would disallow this so I agree this is an issue

Should be an easy thing to add (looking at the code), so happy to fix this up

**Comment by zhangyiwei** [comment]
Cool! A lot of thanks to you!

**Comment by zhangyiwei** [comment]
@emilieroberts for visibility.

**Comment by sfricke-samsung** [comment]
Ok, so this took some digging, but the original VU message was [relaxed a while ago](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/3928) to remove the `format` as it would allow for this format

The real issue here it seems are usage flags causing the error, which your log shows was `0x20130` 

I added a positive tests #3192 and doesn't reproduce the error because the current logic for `VUID 01881` will see `AHARDWAREBUFFER_USAGE_GPU_SAMPLED_IMAGE` is set and not throw the error

@zhangyiwei please look at the test and let me know in the PR what needs to change in order to reproduce the error you are seeing

**Comment by zhangyiwei** [comment]
Ah, it looks like I was still using an old VVL layer. The latest relaxed logic should work. Thanks a lot for investigatin and the test LGTM as well!

**Comment by ncesario-lunarg** [comment]
Thanks @sfricke-samsung! @zhangyiwei is there still an issue that needs to be resolved with VVL here, or can this be closed?

**Comment by zhangyiwei** [comment]
This can be closed. Thanks!
