### ISSUE TITLE
Relaxed layout matching rules aren't reflected in validation layers

### ISSUE THREAD

**Issue by drakos-amd** [KhronosGroup/Vulkan-ValidationLayers#316]
A recent change to the Vulkan spec relaxed image layout matching rules to allow mismatch of the effective layout of aspects not actually referred to by the image view, in particular for depth/stencil images (see section Image Layout Matching Rules in the Vulkan spec). The change affects the VU of VkDescriptorImageInfo:

```
imageLayout must match the actual VkImageLayout of each subresource accessible from
imageView at the time this descriptor is accessed as defined by the image layout matching
rules
```

This issue is for tracking the necessary validation layer changes needed to account for the updated (relaxed) rules.

**Comment by aejsmith** [comment]
Is this in progress? I just hit validation errors while trying to make use of the relaxed rules for depth/stencil images.

**Comment by mark-lunarg** [comment]
@aejsmith, not currently -- folks are busy with other issues.  Will bump up the priority though and get this on the shortlist for you.

**Comment by aejsmith** [comment]
I made an attempt at handling this here: https://github.com/aejsmith/Vulkan-ValidationLayers/commit/027f7cef7565c4e3ff379b7ce1c179b710ca9376

However, it turns out that doesn't really work, because it doesn't handle the first access to a subresource within a command buffer using a layout that's not the same as, but compatible with, the current layout at  submit time (first access assumes that initial layout is the exact layout that was specified for that access). I don't know what the correct approach to deal with that is.

I'd really appreciate it if somebody could look at doing this properly soon - it's currently somewhat blocking me from doing some optimisations which make use of the relaxed layout matching rules, as I cannot be sure whether what I'm doing is actually correct due to the validation errors I'm getting by not having this handled properly by the layers.

**Comment by mark-lunarg** [comment]
I believe @jzulauf-lunarg is overhauling the layout tracking and validation.

**Comment by jzulauf-lunarg** [comment]
@aejsmith  I've got a change in review overhaulling image layout tracking, that needs to clear before I look at this.  Can you point me to the "relaxed rules" you're referencing, so I can get a head start?

**Comment by aejsmith** [comment]
These are the rules given in "Image Layout Matching Rules" in the spec: https://www.khronos.org/registry/vulkan/specs/1.1/html/chap11.html#resources-image-layouts-matching-rule

**Comment by jzulauf-lunarg** [comment]
@aejsmith  -- added in above PR if you want to check on your test case.  Implementation limits relaxed rules (effectively) to Draw and Dispatch uses ("accesses to an image with a depth/stencil format performed through descriptors referring to only a single aspect of the image")

**Comment by aejsmith** [comment]
It seems like the issue I hit in my attempt at implementing this is still problematic with your PR. Specifically, what I've got happening is this:
- Command buffer A transitions an image to DEPTH_READ_ONLY_STENCIL_ATTACHMENT, and uses it.
- Command buffer B (will be submitted after A) accesses the image through a descriptor with layout set to DEPTH_STENCIL_READ_ONLY (this is the first use of it in B). This should be fine, because the relaxed rules allow this to match with the actual layout of the image.
- Command buffer B later begins a render pass with the image as an attachment, with initialLayout set to DEPTH_READ_ONLY_STENCIL_ATTACHMENT. This should be fine as well, because it will exactly match the actual layout of the image.

When that render pass is begun, I get an error:
`[ UNASSIGNED-CoreValidation-DrawState-InvalidRenderpass ] Object: VK_NULL_HANDLE (Type = 0) | You cannot start a render pass using attachment 1 where the render pass initial layout is VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL and the previously used layout of the attachment is VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL. The layouts must match, or the render pass initial layout for the attachment must be VK_IMAGE_LAYOUT_UNDEFINED`

Which I think is because the first use within B was based on the relaxed rules, and DEPTH_STENCIL_READ_ONLY gets recorded as current layout of the image at that point, so the render pass assumes that initial layout needs to exactly match that.

On a side note - f660ad6d5b876765d26841ea2545f63b27a6e503 gives a huge performance improvement when running with the layers, almost 4x faster on the game I'm working on, so nice work there!

**Comment by jzulauf-lunarg** [comment]
As I read the "relaxed rules" it *only* applies to "accesses to an image with a depth/stencil format performed through descriptors" -- so the renderpass usage *must* match exactly.

Though I'm concerned that my change won't correct cover the descriptor use case for initial usage validation (in fact I don't know why you're not seeing a QueueSubmit time error for the descriptor usage case (unless the descriptor usage *isn't* the first use).

Nice that the perf work helped out so much. :)

**Comment by aejsmith** [comment]
@jzulauf-lunarg The situation I described above still does not work correctly with the code that was merged (though the submit time errors have gone away now). For that to work, the render pass usage (which uses the exact layout of the image) needs to be allowed to mismatch with the initial layout that was assumed during the draw which used the image earlier in the command buffer (which used DEPTH_STENCIL_READ_ONLY, not an exact match but allowed by the relaxed rules).

**Comment by jzulauf-lunarg** [comment]
@

**Comment by jzulauf-lunarg** [comment]
@aejsmith -- I think I've covered the case with the updates to the layout checker, pushed above.

**Comment by aejsmith** [comment]
Yep, that looks like it's working now, thanks a lot!

**Comment by jzulauf-lunarg** [comment]
Merged
