### ISSUE TITLE
possible issue with descriptor validation

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#3164]
When running certain apps in zink, I get the following validation errors:

```
zink DEBUG: ERR: 'Validation Error: [ VUID-vkCmdDrawMultiEXT-None-02697 ] Object 0: handle = 0x4ef9f4000000070a, type = VK_OBJECT_TYPE_PIPELINE; Object 1: handle = 0xb52fa90000000707, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; Object 2: handle = 0xb52fa90000000707, type = VK_OBJECT_TYPE_PIPELINE_LAYOUT; | MessageID = 0x830dea22 | vkCmdDrawMultiEXT(): VkPipeline 0x4ef9f4000000070a[] defined with VkPipelineLayout 0xb52fa90000000707[] is not compatible for maximum set statically used 2 with bound descriptor sets, last bound with VkPipelineLayout 0xb52fa90000000707[] The Vulkan spec states: For each set n that is statically used by the VkPipeline bound to the pipeline bind point used by this command, a descriptor set must have been bound to n at the same pipeline bind point, with a VkPipelineLayout that is compatible for set n, with the VkPipelineLayout used to create the current VkPipeline, as described in Pipeline Layout Compatibility (https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VUID-vkCmdDrawMultiEXT-None-02697)'
zink DEBUG: ERR: 'Validation Error: [ UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotBound ] Object 0: handle = 0x9ebdd10, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xcde11083 | vkCmdDrawMultiEXT(): VkPipeline 0x4ef9f4000000070a[] uses set #2 but that set is not bound.'
```

Initially I assumed this was a zink bug, but after spending a while looking into it, I'm no longer as certain. I added some printfs to verify a sequence of two draws that triggered the errors, and here's what I came up with.

The scenario here has the following descriptor layout on two pipelines:
* set 0 - push descriptors (this set is unaffected and so I've excluded it from further mention)
* set 1 - uniform buffers
* set 2 - samplers

Here's the descriptor update process for the non-push sets:

```
DESCRIPTOR UPDATE START
PIPELINE CHANGED 0x7fa57c3fc310 -> 0x7fa57cbaac10
DSL[1] CHANGED 0x5b7b600000000495 -> 0xb27f24000000043c
DSL[2] CHANGED 0x142bb500000005dc -> 0xee3cd000000043d
DSL[3] SAME (nil)
DSL[4] SAME (nil)
UPDATE: USAGE MASK(0x6) BIND_MASK(0x6)
BIND SET 1
BIND SET 2
DRAW

DESCRIPTOR UPDATE START
PIPELINE CHANGED 0x7fa57cbaac10 -> 0x7fa57cbf8510
DSL[1] CHANGED 0xb27f24000000043c -> 0x5b7b600000000495
DSL[2] SAME 0xee3cd000000043d
DSL[3] SAME (nil)
DSL[4] SAME (nil)
UPDATE: USAGE MASK(0x6) BIND_MASK(0x2)
BIND SET 1
DRAW
```

The first draw begins with a pipeline bind that changes the descriptor layout, so both sets are updated and rebound.

The second draw begins with a pipeline bind that changes only the uniform buffer descriptor layout, so only set 1 is updated and rebound: set 2 remains untouched from the previous draw.

I've verified both on the zink side and in the vulkan driver (RADV) that all the sets are bound when they should be (both by manual inspection at the time of the error and with asserts), and the GPU does not hang as it most certainly would if there truly was no set bound. Furthermore, the pipeline layout used has a total of 3 descriptor sets for both draws.

What's interesting here is that if I drop the state tracking in zink and force updating of all sets on the pipeline change (i.e., bind both sets 1 and 2 unconditionally), then the error goes away, even though there's no change in driver state, so this makes me think that the bug is in the validation state tracking and not on my end.

**Comment by ncesario-lunarg** [comment]
Sorry, I haven't had a chance to dive into this (it's not obvious to me what the problem might be without further investigation).

FYI @Tony-LunarG as I'm not sure if there might be something "special" about the use of multi-draw here?

**Comment by zmike** [comment]
No problem, it's a tricky issue for sure.

**Comment by Tony-LunarG** [comment]
Are both draws in the same command buffer?  It doesn't seem like they could be if there's an UpdateDescriptorSets between them.

**Comment by zmike** [comment]
Yes, this is all in one command buffer.

**Comment by Tony-LunarG** [comment]
I seem to only be able to launch the game from steam and the layer settings don't seem to stick from steam to the start of the game.

**Comment by zmike** [comment]
Ah, right, you'll also need `ZINK_DEBUG=validation` in the game's launch options to force validation at the driver level. Sorry about that!

**Comment by Tony-LunarG** [comment]
I'm still having trouble getting a repro.  I'm trying to take a trace of the game to make debugging easier, but I get no frames in the trace.  I'm setting MESA_LOADER_DRIVER_OVERRIDE=zink ZINK_DESCRIPTORS=lazy ZINK_DEBUG=validation in my launch options and using vkconfig to enable tracing and launch steam, then running game and then the benchmark.  All I see in the trace is CreateInstance, EnumeratePhysicalDevices, GetPhysicalDeviceProperties (several times) and then DestroyInstance. @zmike any ideas how I can reproduce this?

**Comment by zmike** [comment]
I uploaded a trace to the lunarg share which exhibits the behavior, though it was tagged as being for another ticket. I'm not sure how to link that to you, but I think you should just be able to search by my login there?

**Comment by ncesario-lunarg** [comment]
@Tony-LunarG I can point you to the share. It's an apitrace rather than gfxreconstruct, so I'm assuming the way to do this is do a GL playback on top of zink?

**Comment by zmike** [comment]
Yep, glretrace should work fine.

**Comment by Tony-LunarG** [comment]
Thank you for the trace - it was immensely helpful in figuring out what is going on.

The call sequence that I'm seeing to bind descriptor sets is as follows:

Bind Pipeline A with Pipeline Layout A
Update and bind DS-0 with Pipeline Layout A
Update and bind DS-1 with Pipeline Layout A
Update and bind DS-2 with Pipeline Layout A
Update and bind DS-3 with Pipeline Layout A
Draw (no errors)
Bind Pipeline B with Pipeline Layout B
Update and bind DS-1 with Pipeline Layout B
Update and bind DS-3 with Pipeline Layout B
Update and bind DS-0 with Pipeline Layout B
Draw (Error DS-2 used but not bound)

Pipeline layout compatibility is described in the spec here:
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#descriptorsets-compatibility

Pipeline layouts A and B are compatible for set 0 as the descriptor set layout for set 0 is identical in both pipeline layouts.
Pipeline layouts A and B are not compatible for set 1 because layout A's descriptor set layout for set 1 has 5 uniform buffers and layout B's has 6 uniform buffers.

Also from the compatibility section - "When binding a pipeline, the pipeline can correctly access any previously bound descriptor sets which were bound with compatible pipeline layouts, as long as all lower numbered sets were also bound with compatible layouts."

So when Pipeline B was bound with (incompatible at set 1) Pipeline Layout B, all sets 1 and above (in this case 2 and 3) were disturbed and inaccessible to the newly bound pipeline, essentially unbound.
DS-0, DS-1 and DS-3 were re-bound, but DS-2 was not, resulting in the error at draw time.

So by my reading of the spec, and validation layer's implementation of the pipeline layout compatibility rules, I think the error is warranted.

**Comment by zmike** [comment]
Huh. I'll have to triple check that then. Thanks for looking into it!

**Comment by zmike** [comment]
Yup, confirmed. Sorry for the mixup!
