### ISSUE TITLE
vkCmdBuildAccelerationStructuresKHR missing object tracking for VkAccelerationStructureBuildGeometryInfoKHR.buildInfo.scratchData.deviceAddress

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-ValidationLayers#3664]
**Describe the situation in which you encountered the missing validation**
Issue description:
I had a GPU hang on NVIDIA with vkCmdBuildAccelerationStructuresKHR.  After debugging it with Aftermath, I found that the GPU VA it referenced in the crash was the scratch buffer and this led me to find that we were freeing this buffer before it was used on the GPU.

**Valid Usage IDs requested**
Please include the valid usage IDs for the checks you are requesting:
I'm not sure if there is a VUID for this, but if vkCmdBuildAccelerationStructuresKHR is missing object tracking it would be good to catch a free of the scratch buffer before use.

**Additional Context**
Any additional information:

**Comment by jeremyg-lunarg** [comment]
VUID-vkCmdBuildAccelerationStructuresKHR-pInfos-03802 says the scratchData address must be valid at the time of the function call but it currently isn't checked. It looks like it'll be pretty easy to add though.

I think destroying the buffer to early should trigger VUID-vkDestroyBuffer-buffer-00922. But currently the state tracker isn't tracking usage for any of the buffers specified by device addresses and there are quite a few of these scattered around the ray tracking structures. So this problem is bigger than just the scratchData field.
