### ISSUE TITLE
build broken on Linux since "build: Skip find_package for added targets"

### ISSUE THREAD

**Issue by airlied** [KhronosGroup/Vulkan-ValidationLayers#3765]
I just went to rebuild the latest valdiation layers for Fedora, but it can't find the spirv headers install despite providing it on the cmake command line.

It looks like @asuonpaa change 
commit 7f229d154400d745259b10c21a6e4091a059ae86
Author: Ari Suonpää <ari.suonpaa@siru.fi>
Date:   Sat Jan 22 09:41:29 2022 +0200

    build: Skip find_package for added targets
    
    Amber uses add_subdirectory for some of the dependencies validation
    layers searches using find_package. In case these are not installed
    on the system the already added dependencies are not found. On the
    other hand, if they are installed, validation layers would use those
    instead of the locally checked out dependencies which should be
    prioritized.

breaks it.

It adds this line, which seems to destroy the command line setting and cause it be ignored.
+set(SPIRV_HEADERS_INCLUDE_DIR "" CACHE STRING "")

**Comment by jeremyg-lunarg** [comment]
The problem @asuonpaa was trying to solve is a complex interaction in the amber build system due to SPIRV-Tools, shaderc, Vulkan-ValidationLayers and possibly some other projects all trying to use their own copy of SPIRV-Headers and providing different cmake settings to override to a common one. I'm going to put up PRs to [amber](https://github.com/google/amber) and this project to make it possible to remove the line that broke fedora without rebeaking amber.  Interestingly SPIRV_HEADERS_INCLUDE_DIR is set  into the parent cmake scope by one of SPIRV-Tools [CMakeLists.txt](https://github.com/KhronosGroup/SPIRV-Tools/blob/d18d0d92e55f44da6af0dc87fb0e3c8034e9a3ac/external/CMakeLists.txt#L41) files.  There's a TODO in the code to fix it but so far I can't find a SPIRV-Tools issue tracking that.

**Comment by jeremyg-lunarg** [comment]
@airlied and @asuonpaa, Can you please check that the fix in #3775 works for your environments? 

I was able to come up with enough fallbacks to get amber to work without changes. It would be nice (but not required) if Fedora included the .cmake files for SPIRV-Headers, I filed https://bugzilla.redhat.com/show_bug.cgi?id=2055921 for that.

**Comment by asuonpaa** [comment]
Seems to work for me. Thanks!
