### ISSUE TITLE
Question about vkSetDebugUtilsObjectNameEXT in the dispatch table

### ISSUE THREAD

**Issue by mgorchak-blackberry** [KhronosGroup/Vulkan-ValidationLayers#3801]
Hi,

I have underlying Vulkan driver implementation what do not expose vkSetDebugUtilsObjectNameEXT in device name space, only as instance. The code quoted below is trying to extract function pointer using device interface:

https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/78684b1a0b9740a13815eb65cbbe7d15d9b26e3c/layers/generated/vk_dispatch_table_helper.h#L1445-L1446

According to the VK_EXT_debug_utils - it is an instance extension. Am I understand it right that vkSetDebugUtilsObjectNameEXT should be retrieved only using vkGetInstanceProcAddr() function?

Underlying Vulkan driver is exposing VK_EXT_debug_utils as an instance extension only and it is missing as device extension.

**Comment by sfricke-samsung** [comment]
So to be clear, when I read `Vulkan driver` I assume you mean just the physical device's implementation driver. For example, if I had a system with both a NVIDIA and AMD desktop GPU in it, there are 2 different Vulkan Drivers and each can be mapped to a `VkDevice` object while the Vulkan Loader is where the single instance of a `VkInstance` level occurs.

`VK_EXT_debug_utils` is a way for the loader and the validation layers to communicate information with each other, with that, there is no reason for a "Vulkan driver" to have it as there is nothing to implement as it should stop at the layer level in the stack

> should be retrieved only using vkGetInstanceProcAddr() function?

You should never try to use `vkGetDeviceProcAddr` on instance level functions if that is your intent of the quesiton

**Comment by ncesario-lunarg** [comment]
While VK_EXT_debug_utils is an instance level extension, [vkSetDebugUtilsObjectNameEXT](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap45.html#vkSetDebugUtilsObjectNameEXT) requires a logical device handle. Doesn't this mean we should be using the `vkGetDeviceProcAddr` to get the function pointer?

Any insight @charles-lunarg?

**Comment by mgorchak-blackberry** [comment]
The problem was spotted by our testers when both api_dump and validation layers were used together with vkcube --validate.

ICD loader draws this scheme:

LAYER: vkCreateDevice layer callstack setup to:
LAYER:    <Application>
LAYER:      ||
LAYER:    <Loader>
LAYER:      ||
LAYER:    VK_LAYER_LUNARG_api_dump
LAYER:      ||
LAYER:    VK_LAYER_KHRONOS_validation
LAYER:      ||
LAYER:    <Device>

vkcube starts and then segfaults on vkSetDebugUtilsObjectNameEXT() attempt of execution, because it is a NULL pointer. I cannot reproduce this behavior on Windows, both layers seems work normally.

This function is excluded from device dispatch table by validation layer, because extension was not activated on device creation, but it was activated on instance creation.

So my question why validation and apidump layers are expecting to resolve this function address via Device interface.

**Comment by charles-lunarg** [comment]
The spec is pretty clear about how you can query instance and device functions.

Third note in the table for `vkGetDeviceProcAddr`:
> The returned function pointer must only be called with a dispatchable object (the first parameter) that is device or a child of device e.g. [VkDevice](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap5.html#VkDevice), [VkQueue](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap5.html#VkQueue), or [VkCommandBuffer](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap6.html#VkCommandBuffer).

https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap4.html#initialization-functionpointers

This essentially says that any function which takes a device, queue, or command buffer can be queried with `vkGetDeviceProcAddr`. A similar table above states that `vkGetInstanceProcAddr` can be used on *all* vulkan functions, and that is consistent because a 'device' function will have the `VkDevice` handle passed as the first parameter so the loader/driver always knows which device to operate on.

One thing that is already common practice is for _device_ extensions to add `VkPhysicalDevice` functions, like [vkGetPhysicalDeviceToolPropertiesEXT](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceToolPropertiesEXT.html). 

However there is one hiccup in my description that "vkGetDeviceProcAddr can be used on all device level functions". Old loader bugs. [This issue reports and diagnoses the bug](https://github.com/KhronosGroup/Vulkan-Loader/issues/33). In short, for a whil,e the loader did not properly support getting the debug utils functions from `vkGetDeviceProcAddr`.

**Comment by Tony-LunarG** [comment]
@mgorchak-blackberry can this be closed?

**Comment by spencer-lunarg** [comment]
closing as does not seem to be a Validation Layer issue, please reopen if disagree
