### ISSUE TITLE
Enhance layers for detecting VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT when creating images with extended usage compatibility

### ISSUE THREAD

**Issue by marfre02-ARM** [KhronosGroup/Vulkan-ValidationLayers#3859]
An enhancement is required to the layers to recognize the correct use of VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT in association with VK_IMAGE_CREATE_EXTENDED_USAGE_BIT.

VUID-VkImageViewCreateInfo-image-01762 describes that if image was not created with the VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT flag, .. then the format must be identical to the format used to create image.

On the flip side of this, if we require to create images with extended usage compatibility then "a usage bit is valid if it is supported for at least one of the formats a VkImageView created from the image can have". 

This more than implies that when using VK_IMAGE_CREATE_EXTENDED_USAGE_BIT for formats not identical to the format used to create the image that VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT should also be used.

The current layers versions (tested with master @ d41543eb) do not detect the omission of VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT when using VK_IMAGE_CREATE_EXTENDED_USAGE_BIT.

**Comment by gnl21** [comment]
I made this comment originally on a Khronos issue. The connection between the `MUTABLE_FORMAT_BIT` and VU 01762 is that the mutable bit changes the set of "format[s] a VkImageView created from the image can have". If `VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT` is not set, then all image views must: be created using the same format as the underlying image, so the `VK_IMAGE_CREATE_EXTENDED_USAGE_BIT` is of no effect.

My original comment was that the validation layer should ignore the extended usage bit if the mutable format bit is not set, since the set of additional formats that would be allowed is empty. (I mean ignore in the sense of it having no effect on the allowed usages -- all the validation rules for setting the bit would still need to be followed).
