### ISSUE TITLE
Feature request: be able to turn off validation in certain parts of my code

### ISSUE THREAD

**Issue by Jasper-Bekkers** [KhronosGroup/Vulkan-ValidationLayers#4039]
We are seeing some very big performance issues when enabling the validation layer; mostly in our batched draw call routines even with moderate amounts of draw calls (3700 or so) it appears to easily take 10x longer.

Validation off:
![image](https://user-images.githubusercontent.com/49594/164230513-a94fb6d0-ca06-4859-9b77-54deab3ca801.png)

Validation on:
![image](https://user-images.githubusercontent.com/49594/164230528-b3130f53-2ed6-4185-b5bb-da7e956e696d.png)

It's understandable that validation has some overhead, however taking a 10x penalty on draw calls that aren't very interesting seems a bit excessive, so it would be nice to be able to disable validation for, say, a specific render pass or a certain set of draw calls.

Alternatively - a way to query the validation layers' underlying driver calls (e.g a GetProcAddr that skips the validation layer) would suffice here.

**Comment by sjfricke** [comment]
There is already a `VK_EXT_validation_features` but I guess that is at an instance creation level.

> disable validation for, say, a specific render pass or a certain set of draw calls.

There technically will always need to be the "state tracking" part running I assume for the future calls, but I guess the `chassis` code could more easily dynamically decide to skip the actual "checking" when the app would ask

**Comment by ncesario-lunarg** [comment]
I'm not sure how feasible "skipping" checks for specific calls would be in VVL, but that is something we can discuss and take a look at. As @sjfricke mentioned, we can't skip the state tracking, which is often a significant portion of the time taken for validation.

The performance issues in VVL are known, and a 10x perf hit is not unexpected, unfortunately. Things can get quite a bit worse depending on how your app is structured; e.g., if your app relies heavily on multi-threading for performance, VVL will incur an even bigger perf penalty due to synchronization that is currently required for state-tracking. 

FYI @jeremyg-lunarg who is leading an effort to improve performance in the validation layers, particularly with respect to multi-threaded performance (see the docs about fine-grained locking [here](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/docs/fine_grained_locking.md)).

**Comment by jeremyg-lunarg** [comment]
Another possibility is to turn off different parts of validation, such as Image layout validation.  See the[ validation layer docs](https://vulkan.lunarg.com/doc/sdk/1.3.211.0/windows/khronos_validation_layer.html)  To do this you'd set `VALIDATION_CHECK_DISABLE_IMAGE_LAYOUT_VALIDATION ` in vk_layer_settings.txt Variable: khronos_validation.disables

**Comment by jeremyg-lunarg** [comment]
We're going to track this as an item on https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/4, but it would be pretty difficult to implement.
