### ISSUE TITLE
Image layout not tracked between command buffers

### ISSUE THREAD

**Issue by asuonpaa** [KhronosGroup/Vulkan-ValidationLayers#409]
It was discovered Vulkan CTS test cases dEQP-VK.protected_memory.image.access.compute.* are having an issue with image layout and it's not  being caught by validation layers.

Those tests are running two command buffers in compute queue: Buffer 1 writes to a protected image and buffer 2 validates the image contents. Buffer 1 uses the image in VK_IMAGE_LAYOUT_GENERAL which is the layout the image is left when the commands are finished. Before running buffer 2 there is a vkWriteDescriptorSet call where the result image from buffer 1 is marked as being used in layout VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL. Validation layers should be able to track the image layout between these two command buffers and complain the image layout is not in expected layout specified by vkWriteDescriptorSet. If I add an image barrier with both old and new layout as VK_IMAGE_LAYOUT_GENERAL before vkCmdDispatch in command buffer 2 the validator gives the proper error message.

**Comment by asuonpaa** [comment]
I'll try to come up with a test code that reproduces this issue.

**Comment by jzulauf-lunarg** [comment]
@asuonpaa  -- The test case would be appreciated.  There are a couple of similar bugs about missing validation of layout mismatches and false positives where a layout transition appears to have been missed.  Hoping they have a common root, as they both seem to point to a hole in the image layout tracking and/or validation.

**Comment by jzulauf-lunarg** [comment]
@asuonpaa -- assign this back to me when you get a chance to push a test case.

**Comment by asuonpaa** [comment]
@jzulauf-lunarg: the test case is now in my fork: https://github.com/asuonpaa/Vulkan-ValidationLayers. Let me know if you have any questions.

**Comment by asuonpaa** [comment]
@jzulauf-lunarg: I didn't find a way to assign this back to you. Maybe I'm missing the permissions to do that?

**Comment by jzulauf-lunarg** [comment]
@asuonpaa  -- *Excellent* test case, thank you. 

Validation is working "as expected", if you were to add a QueueSubmit of cb2 in you example you would see the error...

>  [ UNASSIGNED-CoreValidation-DrawState-InvalidImageLayout ] Object: 0x263f1ee1018 (Type = 6) | Submitted command buffer expects image 0x6 (subresource: aspectMask 0x1 array layer 0, mip level 0) to be in layout VK_IMAGE_LAYOUT_GENERAL--instead, image 0x6's current layout is VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL.

The reason you would see this as a submit time error instead of a record time error is because the `vkCmdDispatch` is the *first* reference to the descriptor in the command buffer.  Since at record time it is impossible to know the state of layouts that will exist at queue submit time (imagine a third command buffer that does the correct image layout transition, recorded later, but submitted prior to the second one) the *first* use of a descriptor/resource within a command buffer is treated specially... validation is deferred to submit time as it must when the current layout will be known.

When you added the `vkCmdPipelineBarrier` to the second command buffer it made the the `vkCmdDispatch` the *second* use of the image resource, and because the barrier set the layout to a *known* state at record time, a record time error message could be created.  

Please feel free to ping back with any questions you might have.  Thanks again for the excellent test case.
