### ISSUE TITLE
READ_AFTER_WRITE syncval error on memory barriers, but only for certain ordering

### ISSUE THREAD

**Issue by martty** [KhronosGroup/Vulkan-ValidationLayers#4346]
**Describe the Issue**
In one trace I do cmdcopy indices -> memory barrier for index reads -> cmdcopy vertices -> memory barrier for vertex reads.
The other trace I do cmdcopy vertices -> memory barrier for vertex reads -> cmdcopy indices -> memory barrier for index reads.

First trace is no error, but the second one gives:
Validation Error: [ SYNC-HAZARD-READ_AFTER_WRITE ] Object 0: handle = 0x1d4aa4a1b60, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x4cb75b2d | vkCmdDrawIndexed: Hazard READ_AFTER_WRITE for vertex VkBuffer 0x1d4aa4a1b60[] in VkCommandBuffer 0x1d4aa737c60[]. Access info (usage: SYNC_VERTEX_ATTRIBUTE_INPUT_VERTEX_ATTRIBUTE_READ, prior_usage: SYNC_COPY_TRANSFER_WRITE, write_barriers: SYNC_INDEX_INPUT_INDEX_READ, command: vkCmdCopyBuffer, seq_no: 3, reset_no: 1).

The traces:
https://gist.github.com/martty/af47742ebdf182c74116b37832d6cd21

**Environment:**
 - OS: Win 10
 - GPU: RX 6700 XT
 - SDK or header version if building from repo: 1.3.216.0
 - Options enabled (synchronization, best practices, etc.): synchronization

**Additional context**

**Comment by jzulauf-lunarg** [comment]
You've tripped over a fundamental limitation in the current syncval implementation.  Since for indirect and indexed lookups we cannot know what portion of an indexed vertex buffer you will access, we test the *whole* buffer.  However, you're storing your indices and vertices in the *same* buffer.  This means if you update the indices *after* the vertices, there is a portion of the bound vertex buffer that has been changed since the memory barrier for vertex reads.

Since syncval (without reading the index buffer, which would be slow) cannot know which portion of the vertex buffer will be referenced by the draw, you get the error... and it order dependent.

Note that this only happens when you share a buffer like this. 

Closing as "known limitations" -- added to Sync Val project feature list.

**Comment by martty** [comment]
Thank you for the explanation, that makes a lot of sense. I suppose this means cmdBindVertexBuffers2 would be an effective workaround this issue? As that one uses ranges instead of offsets.

**Comment by jzulauf-lunarg** [comment]
@martty  -- It would if syncval supported it. I'll add an "add feature bug" to support this. #chagrin

**Comment by danginsburg** [comment]
I am running into this issue and trying to understand the current state of things.  You mention in this bug

> Closing as "known limitations" -- added to Sync Val project feature list.

Where is this list?  It's not in the "Known Limitations" in https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/docs/synchronization_usage.md

> @martty -- It would if syncval supported it. I'll add an "add feature bug" to support this. #chagrin

I can't find this issue, where is it?  Does vkCmdBindVertexBuffers2 now work properly to fix this?

**Comment by KarenGhavam-lunarG** [comment]
> Where is this list? It's not in the "Known Limitations" in https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/docs/synchronization_usage.md

There is a "classics project" in the validation layer github keeping track of work to be done: https://github.com/KhronosGroup/Vulkan-ValidationLayers/projects/5

**Comment by jzulauf-lunarg** [comment]
@danginsburg -- will update the document as I note it's out of date in several respects.
