### ISSUE TITLE
Missing VUID-VkGraphicsPipelineCreateInfo-pViewportState-04892

### ISSUE THREAD

**Issue by versalinyaa** [KhronosGroup/Vulkan-ValidationLayers#4366]
**Describe the situation in which you encountered the missing validation**
Found by code inspection while debugging a Mesa driver.

**Valid Usage IDs requested**
`VUID-VkGraphicsPipelineCreateInfo-pViewportState-04892`

**Additional Context**
The missing VUID is a sibling of `VUID-VkGraphicsPipelineCreateInfo-rasterizerDiscardEnable-00750`, which is handled correctly.

**Comment by spencer-lunarg** [comment]
In effort of adding this, ran into some other issues and wanted to document here until I get time to look more into it:

- in [5 years ago](https://github.com/KhronosGroup/Vulkan-ValidationLayers/commit/ad8e75fb3356af1f5cec1cff3a484933d6a3f869#diff-40e3af4ba2ed4415f093408c93d2298fb613982acb600269e02844a96e4b62d0R2968), because of the [spec change](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/2009) in [1.0.47](https://github.com/KhronosGroup/Vulkan-Docs/commit/0285e9c97749eb0db63843b76c6202e14996b5aa#diff-82eec07eaf207ff8c50739d967f15e8c744ed4f87747d2873ceadba9ed0ce704R367), pipeline structs were ignored with  `rasterizerDiscardEnable` disabled.
- 8 months ago an [internal issue](https://gitlab.khronos.org/vulkan/vulkan/-/issues/3028) about what is ignored was raised and a [change in the spec](https://gitlab.khronos.org/vulkan/vulkan/-/merge_requests/5075) in 1.3.207 was made not to say "ignored"
- There are also related VVL issues/PR related to `rasterizerDiscardEnable`
  - https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/930
  - https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/981
  - https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/1099/
  - https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/2923
  
So what still needs to be understood is what is "actually" ignored and how it is different between `rasterizerDiscardEnable` and `VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE`
