### ISSUE TITLE
Potential invalid error with vkAcquireNextImageKHR 

### ISSUE THREAD

**Issue by youss2017** [KhronosGroup/Vulkan-ValidationLayers#4523]
**Describe the Issue**
When calling vkAcquireNextImageKHR with both semaphore and fence are nullptr and a timeout of UINT64_MAX, the validation layer reports the following error
`[2022-09-06.20:21:19]: Validation Error: [ VUID-vkAcquireNextImageKHR-semaphore-01780 ] Object 0: handle = 0xe7f79a0000000005, type = VK_OBJECT_TYPE_SWAPCHAIN_KHR; | MessageID = 0x94557523 | vkAcquireNextImageKHR: semaphore and fence are both VK_NULL_HANDLE. The Vulkan spec states: semaphore and fence must not both be equal to VK_NULL_HANDLE (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html#VUID-vkAcquireNextImageKHR-semaphore-01780)`, this is invalid because vkAcquireNextImageKHR will block indefinitely because the timeout is UINT64_MAX and will not return until an image is ready therefore this error should not be reported. 

**Environment:**
 - OS: Windows 11
 - GPU: Ryzen 7 5825U Integrated GPU
 - SDK or header version if building from repo: SDK Version 1.3.216.0
 - Options enabled (synchronization, best practices, etc.):

**Comment by jeremyg-lunarg** [comment]
Please see this comment, which explains how the timeout and fence / semaphore interact: https://github.com/KhronosGroup/Vulkan-Docs/issues/117#issuecomment-200064412
The whole discussion in that Issue is probably relevant, but that comment is a very clear explanation (IMO).

In short, the timeout specifies how long to wait for an image that *will become usable at some point*. BUT, you still must wait on the fence or semaphore before the image is actually acquired and ready for your application to use.

Also, Issues in this repository are for problems with the implementation of validation, such as if we have a bug in the code that implements a VUID check.  Problems with the VUID definitions should be filed in the https://github.com/KhronosGroup/Vulkan-Docs repository.
