### ISSUE TITLE
Assert-less Validation Layers

### ISSUE THREAD

**Issue by Cry-Mory** [KhronosGroup/Vulkan-ValidationLayers#453]
Hi Guys,

Is it possible to compile validation layers on Android excluding the asserts? It causes my application to crash.

**Comment by tobine** [comment]
Hi @Cry-Mory there are various ways that you could build assert-less layers, but no built-in config that does this. If the assert is due to a bug in the validation layers, then please provide file a bug on that issue so that it can be fixed.
If the assert is due to an error in your app that includes a validation error then fix the error in your app.

**Comment by Cry-Mory** [comment]
@tobine The assert which was causing the problem was in descriptor_sets.cpp. I am not sure if the expression it checks in the assert is correct or not. After changing the expression (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/465/commits/426b89022bece6696a9c0fa8d1c9251cd4412b81), everything seems to work fine but my pull request validation layer tests are failed. I haven't look why yet.
