### ISSUE TITLE
Missing validation error if `vkQueuePresentKHR` doesn't wait for `vkAcquireNextImageKHR`

### ISSUE THREAD

**Issue by Rua** [KhronosGroup/Vulkan-ValidationLayers#4593]
The following two calls happen right after each other:
```
Thread 0, Frame 3:
vkAcquireNextImageKHR(device, swapchain, timeout, semaphore, fence, pImageIndex) returns VkResult VK_SUCCESS (0):
    device:                         VkDevice = 0x55d640f00090
    swapchain:                      VkSwapchainKHR = 0x55d640f2d010
    timeout:                        uint64_t = 18446744073709551615
    semaphore:                      VkSemaphore = 0x55d640e706d0
    fence:                          VkFence = 0x55d640f46a50
    pImageIndex:                    uint32_t* = 0

Thread 0, Frame 3:
vkQueuePresentKHR(queue, pPresentInfo) returns VkResult VK_SUCCESS (0):
    queue:                          VkQueue = 0x55d640e2fe90
    pPresentInfo:                   const VkPresentInfoKHR* = 0x55d641561eb0:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR (1000001001)
        pNext:                          const void* = NULL
        waitSemaphoreCount:             uint32_t = 0
        pWaitSemaphores:                const VkSemaphore* = NULL
        swapchainCount:                 uint32_t = 1
        pSwapchains:                    const VkSwapchainKHR* = 0x55d641567fa0
            pSwapchains[0]:                 const VkSwapchainKHR = 0x55d640f2d010
        pImageIndices:                  const uint32_t* = 0x55d641567f80
            pImageIndices[0]:               const uint32_t = 0
        pResults:                       VkResult* = 0x55d641567fe0
            pResults[0]:                    VkResult = VK_SUCCESS (0)
```

`vkAcquireNextImageKHR` signals a semaphore, but `vkQueuePresentKHR` doesn't wait for any semaphores and immediately presents. This means that the present could occur before the acquire has completed. I expect a validation error for this, but there isn't one.

**Comment by jeremyg-lunarg** [comment]
See also https://gitlab.khronos.org/vulkan/vulkan/-/issues/565 (thanks @jzulauf-lunarg!)

**Comment by artem-lunarg** [comment]
Thanks for the suggestions! I'll check syncval. Might be queued for a week or two until some other work is done.

**Comment by artem-lunarg** [comment]
> can we verify this occurs without error when SyncVal with Submit time validation is enabled?

This does not generate error for SyncVal with Submit time validation: https://github.com/artem-lunarg/Vulkan-ValidationLayers/commit/44d4644d10533a6af060fdac011e09aaac62b982
IIRC we model acquire as read and presentation as write, with this setup it looks like WAR situation.
@jzulauf-lunarg do you think we need to detect this in SyncVal? (Should it be a new PRESENT_AFTER_ACQUIRE hazard type?)

Going to check what options do we have to detect this during regular validation. And sorry for the delayed response.

**Comment by jzulauf-lunarg** [comment]
@artem-lunarg  -- has the acquire fence been waited in this scenario?

**Comment by jzulauf-lunarg** [comment]
I'm sure this *should* trigger an error... but aren't contents of an acquired image undefined at acquisition? I can't imagine this as a valid real-world use case.  Someone should at least be *clearing* the acquired image before presenting it.

Actually, that's something we could track, by storing "stage/access" meta-state of undefined and reporting READ-UNDEFINED as a hazard class.  (with application to QFO release/acquire, ILT from UNDEFINED, etc.

**Comment by artem-lunarg** [comment]
> has the acquire fence been waited in this scenario?

No, the test does not wait for the fence. This ticket says "two calls happen right after each other", so my assumption that fence wait is not part of this scenario.

**Comment by jzulauf-lunarg** [comment]
Looks like validation and test gap, then.

**Comment by artem-lunarg** [comment]
@Rua @jzulauf-lunarg Thinking about this ticket it's not obvious to me if there is a problem. Currently I'm worming through the relevant parts of the spec and online discussions.

from this issue description:
>  present could occur before the acquire has completed

Yes, but present in the spec terminology it's a queue operation (puts a packet with present request on the queue), actual present happens when this queue operation is consumed by the presentation engine.  Then according to spec:

> presentation requests sent to a particular queue are always performed in order. 

If `vkQueuePresentKHR` enqueues request (without waiting for Acquire semaphore) with the same image that is currently being processed by the presentation engine (from the previous present), does it create a problem? If PE is currently presenting image 0,  should it be fine to have enqueued request that also references image 0? After PE finishes with current presentation it will grab the next request from the queue and will start presenting image 0 again.

The spec says the purpose of `vkAcquireNextImageKHR`'s semaphore/fence is to ensure app won't submit workload that modifies the image that is simultaneously being processed by the PE. 
> Use of semaphore allows rendering operations to be recorded and submitted before
the presentation engine has completed its use of the image.

and this:
> the application must use semaphore and/or fence to ensure that the image layout and contents
are not modified until the presentation engine reads have completed.

The scenario of this issue does not submit workload that modifies the image.

Also according to spec presentation is read-only operation (until mechanism other than Vulkan modifies swapchain window):
> Presentation is a read-only operation that will not affect the content of the presentable images. Upon
 reacquiring the image and transitioning it away from the VK_IMAGE_LAYOUT_PRESENT_SRC_KHR layout, the
 contents will be the same as they were prior to transitioning the image to the present source layout
 and presenting it.

Talking about practicality of the scenario described in this issue, it does not sound for me too unrealistic (sure you won't do this in a game or interactive app). One example is a test that is used by the developers of a windowing subsystem to test a presentation engine. As the first step, the test transitions all swapchain images to presentable layout and then runs a loop that does Acquire+Present sequence to show static image with a sole purpose to test the presentation engine.

Feel free to comment on the above considerations. Are they too far fetched? Please correct if I missed something.

**Comment by artem-lunarg** [comment]
I had a conversation with @Tobski and the conclusion so far is that Present should synchronize with Acquire (with a fence or semaphore). 

The scenario I described about queue present operation is not a general model, and enqueueing new frame with the same image that is still being presented by PE can create a risk of a hazard between two presentations. As I understand enqueueing the present operation can be more complex flow then just putting a package on the queue. There is a place in the spec, that I think, explains this:

> The set of queue operations defined by queuing an image for presentation, as well as operations performed by the presentation engine access the payloads of objects associated with the presentation operation. The associated objects include:
  The swapchain image, its implicitly bound memory, and any other resources bound to that memory.
  The wait semaphores specified when queuing the image for presentation.

It says that queue's presentation operation itself can access payloads, not only the presentation engine.

I'll ask for a change to the spec to explicitly mention that Present should use either fence or semaphore sync. Currently we only have VUID that Acquire should specify at least fence or semaphore. Then it's allowed for Present to not specifying semaphore: 
> waitSemaphoreCount is the number of semaphores to wait for before issuing the present request. The number may be **zero**.

But nothing mentions that Acquire's fence should be waited on when present does not use semaphore.

**Comment by artem-lunarg** [comment]
Spec update request: https://gitlab.khronos.org/vulkan/vulkan/-/issues/3616

**Comment by artem-lunarg** [comment]
Spec update request: https://gitlab.khronos.org/vulkan/vulkan/-/issues/3616

**Comment by artem-lunarg** [comment]
Section 34.10, part of vkAcquireNextImageKHR documentation (which I missed initially):
> An application must wait until either the semaphore or fence is signaled before accessing the image’s data.
