### ISSUE TITLE
Missing checks for VkWaylandSurfaceCreateInfoKHR's display and surface members 

### ISSUE THREAD

**Issue by charles-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4790]
**Describe the situation in which you encountered the missing validation**
Was helping a user on the Vulkan Discord when they reported issues creating a swapchain. Turns out they were NOT specifying the `VkWaylandSurfaceCreateInfoKHR::surface` member in their creation of the wayland surface.

This is because there is no validation of either the wl_display and wl_surface members of VkWaylandSurfaceCreateInfoKHR, likely because they are *not* core Vulkan types, but are "wayland" types.

**Valid Usage IDs requested**
VUID-VkWaylandSurfaceCreateInfoKHR-display-01304
VUID-VkWaylandSurfaceCreateInfoKHR-surface-01305

**Additional Context**
This definitely should be an autogenerated check in the parameter validation checks, but seems that the code-gen doesn't deal with the WSI related types at all, which is a shame.

**Comment by spencer-lunarg** [comment]
> This definitely should be an autogenerated check

So we only really autogenerate the Implicit VUIDs, these are explicit due to the nature of using non-Vulkan API items

I guess outside of checking if it is null or not, a manual wayland API call to see if `wl_display` is valid or not is needed

Also for record, all the "must be a valid type" for the other WSI VUIDs are also not completed

- `VUID-VkAndroidSurfaceCreateInfoKHR-window-01248` 
- `VUID-VkXcbSurfaceCreateInfoKHR-connection-01310`
- `VUID-VkXlibSurfaceCreateInfoKHR-dpy-01313`
- `VUID-VkDirectFBSurfaceCreateInfoEXT-dfb-04117`
- `VUID-VkDirectFBSurfaceCreateInfoEXT-surface-04118`
- `VUID-VkScreenSurfaceCreateInfoQNX-context-04741`
- `VUID-VkScreenSurfaceCreateInfoQNX-window-04742`
