### ISSUE TITLE
StringPipelineStageFlags function doesn't handle all bits correctly

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#4833]
`sync_utils::StringPipelineStageFlags()` does not handle all bits correctly, for example passing `VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR ` will give `Unhandled VkPipelineStageFlagBits`

**Comment by spencer-lunarg** [comment]
ok, this is interesting, so the `StringPipelineStageFlags` code was making the assumption that if enum value was less than `UINT32_MAX` it would be in the `VkPipelineStageFlagBits` but for `VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR` it was never in "sync1" but still is in the first 32-bit range (This is because the Access Mask were the ones that we ran out of that caused the need to expand to 64 bit)

In theory we "could" try to argue to the WG to get the stages in the Sync1 enum for completeness, but seems like that causes it own churn/mess.. rather just fix this print statement :smile: 

cc @jeremyg-lunarg (making the PR right now, but figured you would like to know this)
