### ISSUE TITLE
2D_ARRAY_COMPATIBLE_BIT not being respected while creating image view of 3D texture

### ISSUE THREAD

**Issue by tbotting** [KhronosGroup/Vulkan-ValidationLayers#488]
**Steps:**

1. Create 3D texture with VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT flag
2. Create imageview with > 1 layer

According to specs it should be allowed, see **bottom of table 15** in https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-subresourceRange-01719

**Results in:**

VUID-VkImageViewCreateInfo-subresourceRange-01719(ERROR / SPEC): msgNum: 0 - vkCreateImageView: pCreateInfo->subresourceRange.baseArrayLayer + .layerCount (= 0 + 32 = 32) is greater than the arrayLayers of the image when it was created (i.e. greater than 1). The Vulkan spec states: If subresourceRange.layerCount is not VK_REMAINING_ARRAY_LAYERS, subresourceRange.baseArrayLayer + subresourceRange.layerCount must be less than or equal to the arrayLayers specified in VkImageCreateInfo when image was created (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageViewCreateInfo-subresourceRange-01719)
    Objects: 1
       [0] 0x5d, type: 10, name: (null)

I'm quite certain this should not result in an error being logged, but I might be wrong.
I've tried to keep the issue report very simple, if you need any more details let me know and I'll try to provide them.

Thanks for all your work!

**Comment by tbotting** [comment]
Any updates?

**Comment by daveh-lunarg** [comment]
@tbotting, I think you're correct that the _intent_ of the spec is that this should not be a validation error. The VUID language, however, fails to account for 2D array views of 3D images, and the validation code strictly follows the spec. 

Typically you'd have to submit a spec issue to https://github.com/KhronosGroup/Vulkan-Docs to have the VUID language changed before we would consider changing the validation code, even where the intent seems clear. But as you point out, the _Table 15: Image and image view parameter compatibility requirements_ table explicitly allows this use, so I think we can justifiably diverge from the strict spec language.

I suggest you should submit a spec issue in any case, as it will improve the spec to be more consistent. I'll have a look at the VUID validation code.

**Comment by daveh-lunarg** [comment]
@tbotting, on reviewing the validation code, it is already modified to account for 2D views of 3D images. Using this feature requires either Vulkan 1.1, or Vulkan 1.0 with extension `VK_KHR_maintenance1`. You should not see error 01719 if you've set the API level or extension correctly. Or, possibly, you might have a quite old SDK installed?

If you verify you have the correct extension and/or API level, and a recent (~3 mon) SDK, and still see this error, reply back and I'll dig deeper - otherwise I'll assume this resolves the issue.

(And disregard the spec issue comment - there does exist conditional language that supports these changes).

**Comment by daveh-lunarg** [comment]
Closing, _qui tacet consentit_
