### ISSUE TITLE
vkGetPhysicalDeviceSurfaceCapabilities2KHR: VkSurfacePresentModeEXT is not handled properly

### ISSUE THREAD

**Issue by BeastLe9enD** [KhronosGroup/Vulkan-ValidationLayers#5151]
When calling `vkGetPhysicalDeviceSurfaceCapabilities2KHR` with a `VkSurfacePresentModeEXT` in the pNext chain of `VkPhysicalDeviceSurfaceInfo2KHR`, validation layers complain:

> vkGetPhysicalDeviceSurfaceCapabilities2KHR: pSurfaceInfo->pNext chain includes a structure with unknown VkStructureType (1000274000); Allowed structures are [VkSurfaceFullScreenExclusiveInfoEXT, VkSurfaceFullScreenExclusiveWin32InfoEXT]

The spec says:
> VUID-VkPhysicalDeviceSurfaceInfo2KHR-pNext-pNext
    Each pNext member of any structure (including this one) in the pNext chain must be either NULL or a pointer to a valid instance of [VkSurfaceFullScreenExclusiveInfoEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfaceFullScreenExclusiveInfoEXT.html), [VkSurfaceFullScreenExclusiveWin32InfoEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfaceFullScreenExclusiveWin32InfoEXT.html), or [VkSurfacePresentModeEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfacePresentModeEXT.html)

So `VkSurfacePresentModeEXT` is missing there

**Comment by spencer-lunarg** [comment]
So this is most likely just because you are using an older version of the Validation Layers as [this is currently supported](https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4934/files#diff-710da3cf062301eca05f37c89583ffc8001c2f3aa86c3e4962e891481cd8cffeL12987-R13056), the `VK_EXT_surface_maintenance1` will be out in the next SDK which will have this supported
