### ISSUE TITLE
Build broken with ToT Vulkan-Headers, due to removal of `VK_LAYER_EXPORT`

### ISSUE THREAD

**Issue by zoddicus** [KhronosGroup/Vulkan-ValidationLayers#5243]
This commit, https://github.com/KhronosGroup/Vulkan-Headers/commit/e8b8e06d092ab406b097907ecaae1a8aae9c7d53, removed `VK_LAYER_EXPORT` from Vulkan-Headers, but VVL still contains references to it, so trying to use ToT of these repos together fails to build.

This was detected by the Chromium bots that roll these dependencies, https://ci.chromium.org/ui/p/chromium/builders/try/chromeos-arm-generic-rel/1136175/overview.
I don't think it is a blocking issue at the moment, so this is mostly an FYI.

**Comment by juan-lunarg** [comment]
I'm going to remove it from VVL today

**Comment by juan-lunarg** [comment]
The main reason for removing it is because VVL currently has inconsistent exported function across multiple platforms.

Here are the currently exported functions from a linux binary:

```sh
# nm - list symbols from object files
$ nm --dynamic build/layers/libVkLayer_khronos_validation.so
000000000097bbc0 T vkEnumerateInstanceExtensionProperties
000000000097bbf0 T vkEnumerateInstanceLayerProperties
000000000097bcf0 T vkGetDeviceProcAddr
000000000097bd20 T vkGetInstanceProcAddr
000000000097bd80 T vkNegotiateLoaderLayerInterfaceVersion
```

It correctly only exports these 5 functions since it uses `--version-script` which has the benefit of silencing unintended exports.

```
{
  global:
    vkGetInstanceProcAddr;
    vkGetDeviceProcAddr;
    vkEnumerateInstanceLayerProperties;
    vkEnumerateInstanceExtensionProperties;
    vkNegotiateLoaderLayerInterfaceVersion;
  local:
    *;
};
```

However, for every other platform more functions than necessary are being exported. Which results in inconsistency.

I also couldn't just fix VK_LAYER_EXPORT in Vulkan-Headers by adding Windows support. Because MSVC will mangle 32 bit symbols unless you use `.def` files (IE broken 32 bit windows binaries).

So sadly the only correct option was to completely remove `VK_LAYER_EXPORT`.

Which also reveals problems in VVL anyway like this:

```
VK_LAYER_EXPORT std::string GetEnvironment(const char *variable);
```

std::string has NO abi guarantees. Even worse this function will only be exported on non Linux platforms due to aforementioned `--version-script`
