### ISSUE TITLE
Fence status tracking

### ISSUE THREAD

**Issue by konstantinegorov** [KhronosGroup/Vulkan-ValidationLayers#5306]
Sometimes the validation layer reports that a fence is in use if the fence signal occurs immediately within vkQueueSubmit (for example, if you don't pass any command buffers to vkQueueSubmit, fence may be signalled immediately).

Example:

```
thread 2:
vkQueueSubmit(fence) // don't pass any command buffers

thread 1:
vkWaitForFences(fence) // or busy loop like "while (vkGetFenceStatus(fence) == NotReady);"
vkDestroyFence(fence)
```

In this case order of execution may be like this:

1) thread 1: begin vkWaitForFences

2) thread 2: begin vkQueueSubmit(fence)
3) thread 2: signal fence

4) thread 1: end vkWaitForFences(fence)
5) thread 1: vkDestroyFence(fence) // validation layer reports that fence is in use here

5) thread 2: end vkQueueSubmit

**Comment by artem-lunarg** [comment]
@konstantinegorov, according to spec `The fence parameter in vkQueueSubmit` requires external synchronization. I means it's not allowed to use fence by multiple threads simultaneously, the application have to ensure that during `vkQueueSubmit` call other threads do not call vulkan functions that accept this fence object as parameter (including `vkWaitForFences`).

Can you confirm that `fence` object was accessed by `vkQueueSubmit` and `vkWaitForFences` at the same time?

If that's what was happening, then you might also check if the 'Thread Safety' validation is enabled. If vkconfig was used, then thready safety checks are disabled by default for the standard preset. Thread Safety validation helps to catch similar issues and reports messages like this:

```
 [ UNASSIGNED-Threading-MultipleThreads ] Object 0: handle = 0xfa21a40000000003, type = VK_OBJECT_TYPE_FENCE; | 
MessageID = 0x141cb623 | THREADING ERROR : vkQueueSubmit(): object of type VkFence is simultaneously used in thread
 20460 and thread 24504
```

**Comment by artem-lunarg** [comment]
Going to close this ticket since it's not a VVL bug. The described scenario suggests it's violation of external synchronization for `fence` parameter of `vkQueueSubmit` function.

Relevant part of the spec:
> If two commands operate on the same object and at least one of the commands declares the object to be externally synchronized, then the caller must guarantee not only that the commands do not execute simultaneously, but also that the two commands are separated by an appropriate memory barrier (if needed).

also from _Externally Synchronized Parameters_
> The fence parameter in [vkQueueSubmit](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#vkQueueSubmit)

As an additional note, my personal impression that this part of the API is not obvious, and just on intuitive level I personally would expect that `vkWaitForFences` does some internal synchronization since it is already has blocking behavior, so additional internal synchronization won't be out of the character. For example we can ask similar question why `vkGetSemaphoreCounterValue`  is allowed to be called (in a loop) to wait for `vkQueueSubmit` results? Anyway, here we have follow the specification rules.
