### ISSUE TITLE
VK_NV_raytracing: vkGetMemoryRequirements is not called for scratch buffer  

### ISSUE THREAD

**Issue by georgeouzou** [KhronosGroup/Vulkan-ValidationLayers#546]
I create a buffer for scratch memory with  the following code:

		VkMemoryRequirements2 mem_req = {};
		mem_req.sType = VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2;
		VkAccelerationStructureMemoryRequirementsInfoNV ri = {};
		ri.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_INFO_NV;
		ri.type = VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_BUILD_SCRATCH_NV;
		ri.accelerationStructure = m_bottom_as.structure;
		vkGetAccelerationStructureMemoryRequirementsNV(m_device, &ri, &mem_req);
	
		VkMemoryAllocateInfo ai = {};
		ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
		ai.allocationSize = mem_req.memoryRequirements.size;
		ai.memoryTypeIndex = find_memory_type(mem_req.memoryRequirements.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);

		vkAllocateMemory(m_device, &ai, nullptr, &m_bottom_as.scratch_memory);
	
		VkBufferCreateInfo bi = {};
		bi.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
		bi.size = mem_req.memoryRequirements.size;
		bi.usage = VK_BUFFER_USAGE_RAY_TRACING_BIT_NV;
		bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
		bi.pQueueFamilyIndices = qidx;
		bi.queueFamilyIndexCount = 1;

		vkCreateBuffer(m_device, &bi, nullptr, &m_bottom_as.scratch_buffer);
		vkBindBufferMemory(m_device, m_bottom_as.scratch_buffer, m_bottom_as.scratch_memory, 0);

And i get the following validation warning:
**validation layer: vkBindBufferMemory(): Binding memory to buffer 0x31 but vkGetBufferMemoryRequirements() has not been called on that buffer.**
But i already query the memory requirements through vkGetAccelerationStructureMemoryRequirementsNV

**Comment by jzulauf-lunarg** [comment]
@jeffbolznv -- can you triage to see if this is apropos to the NV_raytracing changes, and assign back to me if not.

**Comment by jeffbolznv** [comment]
Piers offered to take this one, too.

**Comment by pdaniell-nv** [comment]
@jzulauf-lunarg yes this validation warning is due to VK_NV_ray_tracing. However, I think it's a valid warning. It's true that the code snippet above used vkGetAccelerationStructureMemoryRequirementsNV to query how much scratch buffer space is required for building an acceleration structure, but I think the application should still query vkGetBufferMemoryRequirements for the buffer itself before allocating memory for it and binding it. There are other factors that may influence the memory required for a buffer and vkGetAccelerationStructureMemoryRequirementsNV by itself is probably not enough.

In other words, I think the code should be more like this:
		VkMemoryRequirements2 mem_req = {};
		mem_req.sType = VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2;
		VkAccelerationStructureMemoryRequirementsInfoNV ri = {};
		ri.sType = VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_INFO_NV;
		ri.type = VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_BUILD_SCRATCH_NV;
		ri.accelerationStructure = m_bottom_as.structure;
		vkGetAccelerationStructureMemoryRequirementsNV(m_device, &ri, &mem_req);
    
    VkBufferCreateInfo bi = {};
		bi.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
		bi.size = mem_req.memoryRequirements.size;
		bi.usage = VK_BUFFER_USAGE_RAY_TRACING_BIT_NV;
		bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
		bi.pQueueFamilyIndices = qidx;
		bi.queueFamilyIndexCount = 1;
		vkCreateBuffer(m_device, &bi, nullptr, &m_bottom_as.scratch_buffer);
    
    VkBufferMemoryRequirementsInfo2 bmr = {};
    bmr.sType = VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2;
    bmr.buffer = m_bottom_as.scratch_buffer;
    vkGetBufferMemoryRequirements2(m_device, &bmr, &mem_req);
	
		VkMemoryAllocateInfo ai = {};
		ai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
		ai.allocationSize = mem_req.memoryRequirements.size;
		ai.memoryTypeIndex = find_memory_type(mem_req.memoryRequirements.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);

		vkAllocateMemory(m_device, &ai, nullptr, &m_bottom_as.scratch_memory);
		vkBindBufferMemory(m_device, m_bottom_as.scratch_buffer, m_bottom_as.scratch_memory, 0);

**Comment by georgeouzou** [comment]
@pdaniell-nv Thanks for the clarification.  
@jzulauf-lunarg Should i close this?

**Comment by karl-lunarg** [comment]
It looks to me that this could be closed.  Thanks @pdaniell-nv !

**Comment by kennyalive** [comment]
@pdaniell-nv vkGetAccelerationStructureMemoryRequirementsNV signature is defined in such a way that is returns VkMemoryRequirements2 not just required buffer size. That's why I'm a bit confused with your example. I looks like either we forgot to use memoryType/Alignment that we also get from vkGetAccelerationStructureMemoryRequirementsNV or signature is too general and it should return only buffer size.

A bit another perspective: according to the example we use memory type from vkGetBufferMemoryRequirements2 to create allocation, as I understand there is not guarantee it's the same as memory type we get from vkGetAccelerationStructureMemoryRequirementsNV .

**Comment by JamesAMD** [comment]
I have the same question as @kennyalive : Is it okay to just ignore the `alignment` value returned by `vkGetAccelerationStructureMemoryRequirementsNV` ?

**Comment by dgkoch** [comment]
The intent was clarified with the release of KHR_ray_tracing (for both NV and KHR): 

Scratch space is allocated as a VkBuffer, so for VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_BUILD_SCRATCH_NV and VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_UPDATE_SCRATCH_NV the pMemoryRequirements->alignment and pMemoryRequirements->memoryTypeBits values returned by this call must be filled with zero, and should be ignored by the application.
