### ISSUE TITLE
Using `c++_static` in Android builds causes random test crashes on all devices

### ISSUE THREAD

**Issue by mark-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5508]
Changing the android build to use `c++_static` instead of `c++_shared` for the layer and shaderc libs causes random crashes in the LVTs in CI.  The static lib used to work, was sensibly changed by JeremyG and those changes were reverted to fix some usability/install problems.  SDK testing showed that the reversion caused test crashes and this also became the case on Main. 

The change was removed from the SDK branch and the removal from main is in progress, but the goal is to build VVL with the static libs so an investigation/fix is needed.

Jeremy's original PR changing from static to shared: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/4408

PR that reverted the shared changes: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5493

PR changing to shared again (at least temporarily) to get CI running cleanly: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5501

**Comment by KarenGhavam-lunarG** [comment]
It should be noted that this issue motivated the change back to static libraries: [Android builds switching to use libc++_shared.so breaks some workflows #5491](https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/5491)

Although the dynamic library can be used, it must be used with an APK which is a more difficult developer workflow than linking with the static library.

Since we are posting Android build releases coincident with SDK releases, I believe this issue needs to be triaged and fixed with some amount of urgency.

**Comment by mark-lunarg** [comment]
After looking at the information JeremyG originally included and running tests locally and in CI, it seems that without significant changes to our test infrastructure (and maybe not even then) we would be unable to build using `libc++_static` universally.  The viable option is probably to always default to shared, and restore instructions (or add a cmake build option) to allow static lib builds which we'd then use for posting Android binaries to Github.

**Comment by jeremyg-lunarg** [comment]
The other option is to change the test framework. I'm pretty sure that the crashes are related to how many CreateInstance/DestroyInstance cycles we do (1 per test) vs what an application normally does (1 ever).
