### ISSUE TITLE
Semaphore was previously signaled by VkQueue 0x0[] but has not since been waited on by any queue.

### ISSUE THREAD

**Issue by DethRaid** [KhronosGroup/Vulkan-ValidationLayers#5589]
**Environment:**
 - OS: Windows 11
 - GPU: RTX 2080 Super
 - SDK or header version if building from repo: 1.3.243.0
 - Options enabled (synchronization, best practices, etc.): Sync, best practices, GPU assisted validation

**Describe the Issue**

The validation layer gives me an error message that contains incorrect information. It reports that a semaphore was last signaled by VkQueue 0x0, which is not correct

**Expected behavior**

The validation layer should clearly state the operation that last signaled the semaphore - in this case, acquiring a swapchain image

**Valid Usage ID**

```
Validation Error: [ UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress ] Object 0: handle = 0xbb79f200000000ca, name = Graphics submit semaphore, type = VK_OBJECT_TYPE_SEMAPHORE; Object 1: handle = 0x284fb225fe0, name = Graphics queue, type = VK_OBJECT_TYPE_QUEUE; Object 2: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xe825f293 | vkQueueSubmit(): pSubmits[0].pSignalSemaphores[0] is signaling VkQueue 0x284fb225fe0[Graphics queue] (VkSemaphore 0xbb79f200000000ca[Graphics submit semaphore]) that was previously signaled by VkQueue 0x0[] but has not since been waited on by any queue.
```

This error message states that my semaphore was previously signaled by `VkQueue` 0x0. `VkQueue` 0x0 does not exist. The semaphore was previously signaled by a call to `vkAcquireNextImageKHR`. The validation message should state something like `vkQueueSubmit(): pSubmits[0].pSignalSemaphores[0] is signaling VkQueue 0x284fb225fe0[Graphics queue] (VkSemaphore 0xbb79f200000000ca[Graphics submit semaphore]) that was previously signaled by vkAcquireNextImageKHR but has not since been waited on by any queue.`

**Comment by ncesario-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/4ee65679bb24a86437477630e319c88cbf3ed7b6/layers/core_checks/core_validation.h#L302

This and/or `SEMAPHORE_STATE::LastOp` probably needs to get updated.

**Comment by abbator** [comment]
It seems like maybe the updated message has the VkQueue and VkSemaphore flipped. It currently implies that the queue is being signaled, when in reality it is of course the semaphore that is signaled. It currently reads: 
`vkQueueSubmit(): pSubmits[0].pSignalSemaphores[0] is signaling VkQueue 0x284fb225fe0[Graphics queue] (VkSemaphore 0xbb79f200000000ca[Graphics submit semaphore]) that was previously signaled by vkAcquireNextImageKHR but has not since been waited on by any queue.`

It should probably read something like this instead: 
`vkQueueSubmit(): pSubmits[0].pSignalSemaphores[0] (VkQueue 0x284fb225fe0[Graphics queue]) is signaling VkSemaphore 0xbb79f200000000ca[Graphics submit semaphore] that was previously signaled by vkAcquireNextImageKHR but has not since been waited on by any queue.`
