### ISSUE TITLE
Add more context to unassigned VUID declarations

### ISSUE THREAD

**Issue by ncesario-lunarg** [KhronosGroup/Vulkan-ValidationLayers#5652]
Unassigned VUIDs in https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/error_message/validation_error_enums.h should contain some reference back to the Vulkan specification justifying their existence. e.g. (as pointed out by @zmike), `UNASSIGNED-CoreValidation-Shader-MissingOutput` is in reference to section [15.1.3](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/chap15.html#interfaces-iointerfaces-matching) in the spec:
```
All input variables and blocks must have an interface match in the preceding shader stage, except for built-in variables in fragment shaders. Shaders can declare and write to output variables that are not declared or read by the subsequent stage.
```

**Comment by spencer-lunarg** [comment]
for `UNASSIGNED-CoreValidation-Shader-MissingOutput` I just labeled this https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/5645 

I have been working through and should soon (once spec changes are approved and land) all the `kVUID_Core_Shader_*` should be gone

I guess instead of improving the band-aid we have, I'm still trying to just get actual VUID for them

**Comment by spencer-lunarg** [comment]
closing, I have an ongoing goal to finally reduce the few `UNASSIGNED` we have, some are being tracked in other issues already
