### ISSUE TITLE
Validate sparse bindings at submit time

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#57]
**Issue by [tobine](https://github.com/tobine) (MIGRATED)**
_Thursday Dec 14, 2017 at 19:04 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2277_

----

Sparse binding is a queue-based operation and therefore proper sparse memory bindings should not be validated until their related resources are used at submit time. Currently validation for sparse bindings is limited so opening this up as a tracking issue.

As a short-term mitigation technique it may be useful to track on a global scale if any spare bindings are ever made and, if so, warn the user that spare validation is currently incomplete.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/jzulauf-lunarg"><img src="https://avatars0.githubusercontent.com/u/32470354?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jzulauf-lunarg](https://github.com/jzulauf-lunarg) (MIGRATED)**
_Friday Jan 05, 2018 at 17:35 GMT_

----

I just added [some](https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/2301/commits/76c6b501fecab02934111d8067c9da110e1caf38#diff-b68a644ae0f3cbb1b3f42a7c11a19bc7R435) enqueuing for sparse buffer validation to ValidateDrawState in PR #2301.  Prior to that, sparse buffers were validating at draw time like non-sparse, so we probably don't have any test coverage of validation timing.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/tobine"><img src="https://avatars0.githubusercontent.com/u/7526739?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tobine](https://github.com/tobine) (MIGRATED)**
_Wednesday Jan 31, 2018 at 23:52 GMT_

----

@chrisforbes is tackling sparse testing in CTS and feeling pain of limited sparse binding validation. I might add a few simple enhancements, but in looking at spec I realize that a comprehensive solution is going to take weeks+ of effort which is beyond any near-term capacity I'll have. Just wanted to check if @mark-lunarg or @jzulauf-lunarg or anyone else has ambition/desire to start chipping at away at more complete sparse binding validation. I'm in for consultation & code review, of course.

**Comment by karl-lunarg** [comment]
<a href="https://github.com/jzulauf-lunarg"><img src="https://avatars0.githubusercontent.com/u/32470354?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jzulauf-lunarg](https://github.com/jzulauf-lunarg) (MIGRATED)**
_Friday Feb 02, 2018 at 18:53 GMT_

----

@tobine @chrisforbes I'm doing a bit of an overhaul/leak plugging for Pipeline Layout Compatibility that could go out a couple weeks, but possibly could be available after that to take look (modulo higher priorities).

**Comment by aitor-lunarg** [comment]
The main pain point for this issue is tracking down which VUIDs need to be pushed back until submission due to containing sparse resources. I still need to more investigation, but I think we can narrow them down to the ones regarding memory bound to the resource. The main ones that led me into taking this issue are mentioned in #3993. These VUIDs require correct memory tracking for resource which we currently don't have for sparse resources (currently we can only bind. No way to unbind, or rebind an already bound range). The bound memory tracking is currently WIP #4084 and #4094 

It could be a good idea to break the issue down into multiple ones:
 - Rework sparse memory tracking so that we can correctly know what is bound
 - Find which VUIDs get affected by sparse resource, and after that, maybe generate a separate issue to group VUIDs by function/struct.

**Comment by ncesario-lunarg** [comment]
No, I think that makes sense. Github has already affectively "linked" these issues, so we should always be able to easily reference one from the other.

**Comment by spencer-lunarg** [comment]
I agree, closing in favor of #3993 and #4047 tracking missing sparse coverage with their relevant VUIDs
