### ISSUE TITLE
VK_KHR_deferred_host_operations - VK_OPERATION_NOT_DEFERRED_KHR crash

### ISSUE THREAD

**Issue by dorian-apanel-intel** [KhronosGroup/Vulkan-ValidationLayers#5817]
**Environment:**
 - OS: Windows
 - GPU: Intel A770
 - SDK or header version if building from repo: VVL: ea79898d1372bd9ca46f186d8d4febbe282d762e
 - Options enabled (synchronization, best practices, etc.): Standard checks (with handle wrapping)

**Describe the Issue**

App is calling:
1. vkCreateRayTracingPipelinesKHR (driver returns VK_OPERATION_NOT_DEFERRED_KHR)
2. vkDestroyDeferredOperationKHR
3. vkGetRayTracingShaderGroupHandlesKHR (with pipeline created in pt1.) - CRASH when unwrapping pipeline handle.

**Expected behavior**

It should not crash.

**Additional context**

I see no VK_OPERATION_NOT_DEFERRED_KHR handling in [layers\generated\layer_chassis_dispatch.cpp](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/43c4cd3504645bb9fd91383f45a867090264d993/layers/generated/layer_chassis_dispatch.cpp#L1456) in function `DispatchCreateRayTracingPipelinesKHR`

I have a commit that seems to workaround the issue (for this single function).

**Comment by spencer-lunarg** [comment]
Was added in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/3793 @aitor-lunarg any idea (cc @arno-lunarg since I'm no RTX expert)

**Comment by aitor-lunarg** [comment]
I had to dig a little bit to refresh. The reason behind the crash is that the handle is not wrapped, so when it "unwraps" it, it'll be null and therefore crash when we try to use that null handle.

I didn't correctly check if the operation was deferred or not for the object tracker part (thread safety is correctly handled) which leads to the post completion functions never being triggered because there's no call to `vkGetDeferredOperationResultKHR` (where the post completion functions are exectued for deferred operations, and therefore, the wrapping of the handle).

I couldn't find any CTS nor VVL test that cover this case, so that's probably one of the reasons this went unnoticed. I'll double check and open a CTS issue if I find none. All CTS tests did call `vkGetDeferredOperationResultKHR` even if the operation was not deferred. It would also be good to have some VVL test to be extra safe.

I'll provide a PR to fix the issue.

**Comment by dorian-apanel-intel** [comment]
@aitor-lunarg @spencer-lunarg 
Thanks for fix.
Do we need similar one for `vkBuildAccelerationStructuresKHR`, `vkCopyAccelerationStructureToMemoryKHR`, `vkCopyAccelerationStructureKHR`, `vkCopyMemoryToAccelerationStructureKHR` ?

**Comment by aitor-lunarg** [comment]
I just checked and need to fix those ones too, otherwise we will have memory leaks. Thank you for pointing it out!

I'll prepare the PR.
