### ISSUE TITLE
Validate debug naming

### ISSUE THREAD

**Issue by Nielsbishere** [KhronosGroup/Vulkan-ValidationLayers#590]
Whenever passing an invalid Vulkan object or a different pointer to the debug object name function, there will be no runtime or compiletime errors. The validator should check the validity of the object passed in.

**Comment by jzulauf-lunarg** [comment]
@MarkY-LunarG looks like in the original bug, the application was passing down an application pointer instead of a Vulkan handle and with the validation layers enabled, what we hand on to the driver crashes it.  Without the layers enabled this *doesn't* crash down in the driver (for reasons unknown), but the validation layers also don't generate an error for the invalid handle.

**Comment by karl-lunarg** [comment]
I took a look because I was curious, so it's worth recording what I found.

The DebugUtils calls do run through validation in object_tracker.  But the codegen generates code to validate only the device object.  Codegen is supposed to find all the object handles in the function parameters and generate code to validate them.  But for the DebugUtils, the object handles are specified as `unint64_t` and so the codegen does not generate code to validate these, because they are not a handle type.

Fix probably involves adding some special-case code to the object_tracker codegen to detect DebugUtils structs that use `uint64_t` as a "generic" handle.  I don't think that there is a (good) way to decorate these generic handles as real handles in the registry xml withount introducing additional semantics to the xml definitions.  Since this is an isolated case, it is probably better to special-case the codegen.

**Comment by jzulauf-lunarg** [comment]
@karl-lunarg thanks -- I'd be interested in what the behavior of the unique_objects is here as well.  Given that without layers the application didn't crash in the driver, and with layers it did.  

@MarkY-LunarG We may also want to look at the behavior of unique_object w.r.t. handle not found cases.

**Comment by MarkY-LunarG** [comment]
@Nielsbishere, can you verify that you at least get a proper warning now with PR #593?  The code is now generated to verify the handles are of the indicated type in the DebugUtils structs now.
