### ISSUE TITLE
 ABI Break: libVkLayer_parameter_validation.so

### ISSUE THREAD

**Issue by winehub** [KhronosGroup/Vulkan-ValidationLayers#591]
Sorry to influence here again. We try to figure out how to handle ABI breaks for fdo.

From the release 1.1.96 -> 1.1.97 we got again an ABI break by missing file 
   libVkLayer_parameter_validation.so

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/jobs/146648391

Why the changes so hard in minor releases?

**Comment by valentindavid** [comment]
So all libraries we find in `.json` files are not to be linked directly?

**Comment by karl-lunarg** [comment]
Yes, many of the libraries that are accompanied by `.json` files are meant to be loaded by the Vulkan loader via `dlopen`, and are not to be linked to another module.  The document that @jeremy-lunarg posted in a previous comment describes the interface between the Vulkan loader and these "layer" libraries.

In short, each of the layer shared libraries export a fairly thin interface consisting of functions like `GetProcAddress` and `NegotiateLayerInterface` to allow a sort of "introspection" process to be performed by the Vulkan loader.  The Vulkan loader typically calls `GetProcAddress` to get additional function pointers and the negotiate function to determine what's supported, etc.

Since this interface is the same for all layer shared libraries, it would be impossible to link more than one into an executable image anyway.

Nothing breaks if things other than the documented interfaces change.  Even if the filename of the shared library changes, this is handled by the indirection in the `.json` files, as @jeremy-lunarg explained.

Technically, I don't think that there is an ABI breakage here.  We do appreciate the efforts to scan these modules to look for changes in exported symbols, etc.  But we wonder if you can treat this as some sort of false positive that you can address by "blacklisting" these modules from these sorts of checks.  It seems that this usage of shared libraries (intended to be loaded only by a specialized loader) isn't that unusual and you would have encountered it before and have some mechanism in place to deal with it.

That being said, we also understand that there's the principle of not exporting things that don't need to be exported.  And we should probably look into changing how these modules are linked so that only the documented interfaces are exported.  Since this won't happen quickly, we're hoping that you can avoid running these checks.  Please let us know if this is possible and how important it is for you to continue scanning these modules, now that you understand that they are loaded and not linked directly.

**Comment by valentindavid** [comment]
Thank you for the explanation.

**Comment by winehub** [comment]
@valentindavid  for me it is ok.

**Comment by valentindavid** [comment]
@jeremy-lunarg yes
