### ISSUE TITLE
Question: parse_dependency package

### ISSUE THREAD

**Issue by catcor01** [KhronosGroup/Vulkan-ValidationLayers#5970]
In common_codegen.py, I get the following error:

```
    from parse_dependency import dependencyBNF
ModuleNotFoundError: No module named 'parse_dependency'
```

pip install parse_dependency does not work. After spending sometime searching online for the package, I cannot find it's correct name. Could you please provide it?

**Comment by spencer-lunarg** [comment]
Hey, so that is actually not a `pip` module, but instead is found in the Vulkan-Headers

https://github.com/KhronosGroup/Vulkan-Headers/blob/main/registry/parse_dependency.py

normally when building, you pass in the Vulkan Registry

`python3 scripts/generate_source.py external/Vulkan-Headers/registry/ external/SPIRV-Headers/include/spirv/unified1/`

But the CMake should be doing this for you

If you are still having issues, you can always set set `PYTHONPATH` maunally

```bash
PYTHONPATH=/path/to/Vulkan-ValidationLayers/external/Vulkan-Headers/registry 
```

**Comment by juan-lunarg** [comment]
As of 20e0afffa934946a0c3dacab668e06154f06de4a users shouldn't need to set PYTHONPATH.

Please refer to the [generated_code.md](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/docs/generated_code.md)

**Comment by catcor01** [comment]
Thank you all, issue has been resolved with your help.
