### ISSUE TITLE
False positive threading error with vkWaitForFences and vkGetFenceStatus

### ISSUE THREAD

**Issue by Cyphall** [KhronosGroup/Vulkan-ValidationLayers#5997]
**Environment:**
 - OS: Windows 11
 - GPU: RTX 3070
 - SDK version: 1.3.250.0
 - Options enabled: eBestPractices

**Describe the Issue**

When my engine calls `vkWaitForFences` and `vkGetFenceStatus` simultaneously from different threads, I get this validation error:

> Validation Error: [ UNASSIGNED-Threading-MultipleThreads ] Object 0: handle = 0xb9181f0000000029, type = VK_OBJECT_TYPE_FENCE; | MessageID = 0x141cb623 | THREADING ERROR : vkGetFenceStatus(): object of type VkFence is simultaneously used in thread 9836 and thread 9536

**Expected behavior**

As per the specs, neither `vkWaitForFences` nor `vkGetFenceStatus` require any host synchronization.

**Valid Usage ID**
`UNASSIGNED-Threading-MultipleThreads`

**Comment by filnet** [comment]
related: https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/3615

**Comment by artem-lunarg** [comment]
@Cyphall How does the application signal the fence? If `vkQueueSubmit` does this, please clarify which thread calls it.

**Comment by artem-lunarg** [comment]
The potential problem here is collision between `vkQueueSubmit` and `vkGetFenceStatus`, since `vkQueueSubmit` requires external synchronization of the fence. When the error is detected the second thread usually has chance to progress a bit further, so if `vkWaitForFences` is placed after `vkQueueSubmit` the callstack can show the `vkWaitForFences` instead of `vkQueueSubmit` - that was a common source of confusing with how VVL reports this type of messages and we are planning to improve this to provide precise names of both race participants.

**Comment by Cyphall** [comment]
It may be caused by that, as my worker thread calls vkWaitForFences right after vkQueueSubmit.
Also, I haven't had this problem recently and it may be related to me adding a mutex lock to where the main thread calls vkGetFenceStatus (the call to vkQueueSubmit already had one)
