### ISSUE TITLE
broken handling for nullptr IMAGE_STATE in PostCallRecordCreateImageView

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#6122]
Not exactly sure what to file this as, but `ValidationStateTracker::PostCallRecordCreateImageView` seems broken if `auto image_state = Get<IMAGE_STATE>(pCreateInfo->image);` returns a nullptr. I'm hitting this when trying to use VVL with zink on steam, and I'm not entirely sure what to do about it.

**Comment by spencer-lunarg** [comment]
1. Did you have `VkImageViewCreateInfo::image` set to null by accident?
2. Did you not hit ` VUID-VkImageViewCreateInfo-image-parameter` first in stateless validation?

**Comment by zmike** [comment]
1. No
2. There are no errors printed

**Comment by spencer-lunarg** [comment]
is this a reproducible issue or sometimes happens?

**Comment by zmike** [comment]
100% when running steam on zink

**Comment by spencer-lunarg** [comment]
@zmike still not sure where this would have gone wrong, but even if we go

```patch
   auto image_state = Get<IMAGE_STATE>(pCreateInfo->image);
+   if (!image_state) return;
```

it will probably just fail later as we won't have the ImageView state

@zmike  Is there a no-zero chance the image and imageview have different `VkDevice`?

**Comment by spencer-lunarg** [comment]
as always @zmike, feel free to reopen if this doesn't solve the issue

**Comment by gents83** [comment]
@spencer-lunarg & @zmike I'm getting the exact same error while trying to use NVIDIA NSight Graphics to do a frame debug on my test app in wgpu (on Vulkan), but it's not really clear to me reading here how to solve the issue :)

**Comment by spencer-lunarg** [comment]
@gents83 to help understand, as of the latest spec (1.3.260) there is now a dedicated VU

> VUID-vkCreateImageView-image-09179
> VkImageViewCreateInfo::image must have been created from device

as the working group agreed this is not valid Vulkan that works everywhere.

This was not being caught before the change in #6132 was added 2 weeks ago, so anything that was violating this, would most likely crash (but now we will not crash **at Image View creation time** and return the error message)

So I am curious if the issue is only when you enabled NVIDIA NSight Graphics? Is your WGPU app doing anything that would involve multiple Device instances (multi-GPU)?

**Comment by gents83** [comment]
Tnx a lot for the explanation 🤗
Nope, it only happens with nsight graphics, but not when launching the app alone
