### ISSUE TITLE
Regression for VkLayerTest.InstanceCreateEnumeratePortability

### ISSUE THREAD

**Issue by richard-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6152]
**Environment:**
 - OS:  macOS
 - GPU: M1
 - SDK or header version if building from repo: 1.3.250.1
 - Options enabled (synchronization, best practices, etc.): Standard Preset

**Describe the Issue**

A validation check that was previously working is now failing on macOS. The specific test can be run on the command line:

./vk_layer_validation_tests --gtest_filter=VkLayerTest.InstanceCreateEnumeratePortability

Failed
Did not receive expected error 'VUID-VkInstanceCreateInfo-flags-06559'

The specific error is that if the VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY extension is enabled, the VkInstanceCreateInfo structures flags member must contain VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR

I don't know when the regression occured, but I do know in the distant pass, this check was being done and I'd see validation errors for it. Now, the standard test fails, and my own test application fails to generate this validation error when I remove the flag as a test.

**Comment by richard-lunarg** [comment]
I should add that I inspected the source for the test, and it indeed should be working. The error is in the validation layer, not the VVL unit test code.

**Comment by spencer-lunarg** [comment]
why was this not caught in the CI? That is more concerning

**Comment by charles-lunarg** [comment]
The cause of this is due to the Vulkan-Loader failing to create an instance due to there not being any available drivers, and because the instance failed to be created before layers get a chance to run, the VUID is never generated.

This test is useful so it shouldn't be removed or added to the blacklist again, which means making the vulkan-loader emit the VUID for either case (missing extension when flag is present and vice versa).

**Comment by richard-lunarg** [comment]
This is actually a Loader bug, and has been moved to that repo:
https://github.com/KhronosGroup/Vulkan-Loader/issues/1254
