### ISSUE TITLE
Core validation: No checks for min image transfer granularity adherence

### ISSUE THREAD

**Issue by karl-lunarg** [KhronosGroup/Vulkan-ValidationLayers#62]
**Issue by [DominikWitczakAMD](https://github.com/DominikWitczakAMD) (MIGRATED)**
_Wednesday Jan 31, 2018 at 16:19 GMT_
_Originally opened as https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/2383_

----

Validation layers do not appear to be verifying if copy op regions submitted via buffer<->image / image<->image transfer ops adhere to the min image transfer granularity, reported separately for each queue family.

In particular it appears that core validation layer does not verify that the rightmost, bottommost, Z-most (?) tiles that exceed past the last aligned tile for each dimension are never submitted for updates via copy ops.

**EXAMPLE:**

Consider:
* 2D image of size 2x3
* Min image transfer granularity for queue family X: 2x2x1.

Copy ops submitted to queue 0 forming queue fam X should never attempt to update a 1x1 block at offset 2x1 because:

1. Size of the block doesn't meet the granularity requirement.
2. Offset is illegal, because its Y offset is not aligned to the required granularity

**Comment by daveh-lunarg** [comment]
This issue is fairly old, and possibly pre-dates the granularity checks implementation.  I see code in buffer_validation.cpp to explicitly check image-image and buffer-image copies offset and extents against the queue granularity. See _ValidateCopyBufferImageTransferGranularityRequirements()_ and _ValidateCopyImageTransferGranularityRequirements()._ 

I'm going to assume this issue is resolved by current validation code. Please re-open with a specific repro case if otherwise.
