### ISSUE TITLE
Pass pNext struct down to Dispatch calls in the Layers

### ISSUE THREAD

**Issue by zmike** [KhronosGroup/Vulkan-ValidationLayers#6256]
It seems like some part of the `CreateImage` chain in VVL is stripping out `VkImageFormatListCreateInfo` / `VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO` structs, which prevents drivers from validating mutable format chains in the implicit `vkGetPhysicalDeviceImageFormatProperties2` call, which then guarantees a `NOT_SUPPORTED` error.

This struct must be included.

**Comment by spencer-lunarg** [comment]
(everything this VU comes up :cry: )

So looking, I see there are a few pNext structs that are allowed in both `vkGetPhysicalDeviceImageFormatProperties2` and `vkCreateImage`

- VkImageFormatListCreateInfo
- VkImageStencilUsageCreateInfo
- VkImageCompressionControlEXT
- VkVideoProfileListInfoKHR
- VkOpticalFlowImageFormatInfoNV

Should be easy to add the logic, much harder to write a test with these `vkGetPhysicalDevice` as can't guarantee return values (until we make better improvements to MockICD for testing)

**Comment by zmike** [comment]
fwiw I've filed this same issue in a variety of places (possibly even this same exact one) at least once before, so it seems like something has to be done to ensure all the pnext structs are passed to functions that need them.

**Comment by spencer-lunarg** [comment]
Yes, the issue is knowing which pNext structs are allowed between the `caller` (ex `vkCreateImage`) and our internal dispatch calls (ex. `vkGetPhysicalDeviceImageFormatProperties2`)

(noting this for @arno-lunarg to take a stab at)
Luckily with the new `VulkanObject` we can generate this easily now, the `Struct` object has a `extends` and `extendedBy` member that can be used, so before would dispatch a call `vkGetPhysicalDeviceImageFormatProperties2`, it would see what `extendedBy` is for `VkPhysicalDeviceImageFormatInfo2` and if the `caller` has any, it would append to the pNext chain.

**Comment by spencer-lunarg** [comment]
@zmike we hopefully got a temp fix for the `VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251` you were having (if not please shout again!) but keeping issue open for Arno to track work on providing a proper solution to this problem

**Comment by zmike** [comment]
I just built 5546d5e82e0a365c4c3a5393c469ae3156fee85c and I'm still seeing the same issue.

**Comment by arno-lunarg** [comment]
@zmike I expect https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6465 to solve this issue, just reopen the issue if it does not!

**Comment by zmike** [comment]
FWIW I think https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6573 is the fix for all the remaining issues I've been seeing.
