### ISSUE TITLE
vkCmdClearAttachments is missing validation of pRects

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/Vulkan-ValidationLayers#627]
In vkCmdClearAttachments spec says:

> The `layerCount` member of each element of `pRects` must not be 0

But this isn't currently validated. I don't think the other VU statements for `pRects` are validated yet, but I may have missed where they're implemented. This one seems to correspond to VUID 01934 FYI.

**Comment by karl-lunarg** [comment]
Triage:  Parameter validation codegen generates a comment saying that there is no xml driven validation.  The codegen does validate structures with a sType member because at least sType can be validated.  But `VkClearRect` does not have a sType.  There is no PV codegen for this type.

This command is already mostly validated in core validation (buffer_validation.cpp) but there is no check for `pRects[].layerCount > 0`.  It is probably easiest to add this simple check here.   The alternative would be to add a `VkClearRect` validator to PV codegen since this is a pure PV situation, requiring no other state to validate.  This alternative needs to be weighed against the simpler solution in CV.

**Comment by mark-lunarg** [comment]
If its stateless, we should add a manual check (similar to `StatelessValidation::manual_PreCallValidateCmdDrawIndexedIndirect`) in `parameter_validation_utils.cpp`. I'll do it.
