### ISSUE TITLE
Continous Deployment via GitHub Actions

### ISSUE THREAD

**Issue by juan-lunarg** [KhronosGroup/Vulkan-ValidationLayers#6356]
During our validation layer meeting we discussed creating nightly binaries for the vulkan validation layers in similar fashion to glslang.

I asked on Discord and there is interest:
https://discord.com/channels/427551838099996672/1129428441981259836/1144347742395715624

Developers overall see the idea as quite useful.

**Comment by zmike** [comment]
I'd like to see tags created every week regardless of spec updates. We use VVL in Mesa CI, and going nearly a month without any updates now is excruciating.

**Comment by juan-lunarg** [comment]
> I'd like to see tags created every week regardless of spec updates. We use VVL in Mesa CI, and going nearly a month without any updates now is excruciating.

That's really a separate issue entirely. VVL nightly binaries would be akin to mimicking what `glslang` does.
https://github.com/KhronosGroup/glslang/releases/tag/main-tot

**Comment by zmike** [comment]
Mesa uses tags for its CI, so that's my area of interest.

**Comment by juan-lunarg** [comment]
> Mesa uses tags for its CI, so that's my area of interest.

I've made a seperate issue to track your concern @zmike:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/6674

**Comment by spencer-lunarg** [comment]
So something I found is https://github.com/actions/upload-artifact/

We are building the binaries in CI and with this, we should be able to automatically upload it after our build for Main every commit so anyone can in theory grab ToT

since the binaries are smalll enough, should be find for the Free storage tier we have

**Comment by SaschaWillems** [comment]
Or simply upload to some LunarG owned server using old-school FTP ;)

I do that for the builds of my caps viewer: https://github.com/SaschaWillems/VulkanCapsViewer/blob/master/.github/workflows/build.yml#L45

**Comment by spencer-lunarg** [comment]
> simply use old-school FTP

@SaschaWillems I agree that would be more ideal, but our internal CI ninjas are fully backlogged with work and for the short term, I got the artifact flow working

https://github.com/KhronosGroup/Vulkan-ValidationLayers/actions/runs/8625957102

I plan to add something to the readme after confirming things are working.. the biggest issue with this workflow is you need to be logged into GitHub in order to down them
