### ISSUE TITLE
Possible false positive for UNASSIGNED-CoreChecks-unhandled-bad-access-flags

### ISSUE THREAD

**Issue by ikapoura** [KhronosGroup/Vulkan-ValidationLayers#6560]
**Environment:**
 - OS: Windows 10
 - GPU and driver version: NVIDIA RTX 2070 super on driver 537.42
 - SDK or header version if building from repo: 1.3.261.1
 - Options enabled (synchronization, best practices, etc.): none

**Describe the Issue**

This validation error is triggered when I insert a memory barrier which has srcAccessMask = eAccelerationStructureReadKHR | eAccelerationStructureWriteKHR (6291456) and reports that I am using pipeline stages instead.

Validation Error: [ UNASSIGNED-CoreChecks-unhandled-bad-access-flags ] Object 0: handle = 0x1f6901414b0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xbbe6b7b8 | vkCmdPipelineBarrier(): INVALID_EMPTYpMemoryBarriers[2].srcAccessMask contains pipeline stages VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT|VK_PIPELINE_STAGE_VERTEX_SHADER_BIT|VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT|VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT|VK_PIPELINE_STAGE_TRANSFER_BIT|VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR.

**Expected behavior**

I expected to not see such an error.

**Comment by ziga-lunarg** [comment]
@ikapoura Can you tell me the exact values of `srcStageMask` and `srcAccessMask`?

**Comment by ikapoura** [comment]
Yes, sure!

**srcStageMask** = eTopOfPipe | eVertexShader | eFragmentShader | eEarlyFragmentTests | eLateFragmentTests | eComputeShader | eTransfer | eAccelerationStructureBuildKHR (33561481)

**srcAccessMask** = eAccelerationStructureReadKHR | eAccelerationStructureWriteKHR (6291456)

**Comment by ikapoura** [comment]
Also I think that the logged message is a bit vague to convey the intend of the validation message. Can we make it a bit more verbose in some way?

**Comment by ziga-lunarg** [comment]
This has already been partially fixed by #6364, which has been merged after the SDK, but the message was still wrong as it says `srcAccessMask` instead of `srcStageMask` (this will be fixed in the linked PR #6569).

So now the message you will be seeing will be this:
`Validation Error: [ VUID-vkCmdPipelineBarrier-srcAccessMask-06257 ] Object 0: handle = 0x25d2d79b060, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x235b7e76 | srcStageMask contains pipeline stages VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT|VK_PIPELINE_STAGE_VERTEX_SHADER_BIT|VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT|VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT|VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT|VK_PIPELINE_STAGE_TRANSFER_BIT|VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR. The Vulkan spec states: If the rayQuery feature is not enabled and a memory barrier srcAccessMask includes VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR, srcStageMask must not include any of the VK_PIPELINE_STAGE_*_SHADER_BIT stages except VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-vkCmdPipelineBarrier-srcAccessMask-06257)`

I hope this sufficiently explains the issue.

**Comment by ikapoura** [comment]
Yes that is perfect, thank you for the immediate response!
