### ISSUE TITLE
Debug version hangs at instance creation.

### ISSUE THREAD

**Issue by psionic12** [KhronosGroup/Vulkan-ValidationLayers#6890]
**Environment:**
 - OS: ubuntu 22.04 (also checked on an arm platform, the problem is the same)
 - GPU and driver version: NVIDIA GeForce RTX 2060 nvidia-driver-535
 - SDK or header version if building from repo: build from sorce code (main branch).
 - Options enabled (synchronization, best practices, etc.): VK_LAYER_KHRONOS_validation
 - Env Var: LD_LIBRARY_PATH=/home/lleo/sources/Vulkan-ValidationLayers/build/layers:/home/lleo/sources/Vulkan-Loader/build/loader
 - Compile command: 
 ```
cmake -S . -B build -D UPDATE_DEPS=ON -D BUILD_WERROR=ON -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=Debug

cmake --build build --config Debug
```

**Describe the Issue**

When using a debug version of validation layers, the program hangs at `vkCreateInstance`.

**Expected behavior**

Instance created without problem.

**Valid Usage ID**
The vkcube example in Vulkan-Tools, with `--validate`
**Additional context**

UPDATE: Release version got the same problem.

Calling stack:
```
futex_wait 0x0000fffff7ce9ffc
__GI___lll_lock_wait 0x0000fffff7ce9ffc
lll_mutex_lock_optimized 0x0000fffff7cf070c
___pthread_mutex_lock 0x0000fffff7cf070c
loader_platform_thread_lock_mutex vk_loader_platform.h:401
vkCreateInstance trampoline.c:557
loader_create_instance_chain loader.c:4677
vkCreateInstance trampoline.c:720
demo_init_vk cube.c:3681
demo_init cube.c:4441
main cube.c:4651
__libc_start_call_main 0x0000fffff7c973fc
__libc_start_main_impl 0x0000fffff7c974cc
_start 0x0000aaaaaaaa2eb0
```

**Comment by psionic12** [comment]
After debugging, I found that the problem might come from this line: chassis.cpp:15768:
```
VVL_EXPORT VKAPI_ATTR VkResult VKAPI_CALL vkNegotiateLoaderLayerInterfaceVersion(VkNegotiateLayerInterface* pVersionStruct) {
    assert(pVersionStruct != nullptr);
    assert(pVersionStruct->sType == LAYER_NEGOTIATE_INTERFACE_STRUCT);

    // Fill in the function pointers if our version is at least capable of having the structure contain them.
    if (pVersionStruct->loaderLayerInterfaceVersion >= 2) {
        pVersionStruct->pfnGetInstanceProcAddr = vkGetInstanceProcAddr;
        pVersionStruct->pfnGetDeviceProcAddr = vkGetDeviceProcAddr;
        pVersionStruct->pfnGetPhysicalDeviceProcAddr = vk_layerGetPhysicalDeviceProcAddr;
    }

    return VK_SUCCESS;
}
```
In the debug version, the address of `vkGetInstanceProcAddr` is not the real address, but the address of the loader. In this case, the code flow called the same `vkGetInstanceProcAddr` again and again, since the `vkGetInstanceProcAddr` in loader are protected by lock, it hangs. If you change the lock to a reentrantlock, the calling stack will overflow.

Don't know why this happens, is there any special symbol link trick in debug build here?

**Comment by charles-lunarg** [comment]
What is the version of the loader you are using? I am trying to match the stack trace up with the loader source but they do not match.

**Comment by psionic12** [comment]
@charles-lunarg the loader I used is built from main branch of Vulkan-Loader.

**Comment by charles-lunarg** [comment]
It would help to have the *correct* branch checked out locally...
But that at least confirms you are using tip of main which wasn't apparent from the issue (a good assumption though).

The stack trace doesn't make much sense with the idea of `vkGetInstanceProcAddr` referring to the loader instead of the validation layer. Can you get the stack trace from inside of `vkNegotiateLoaderLayerInterfaceVersion`?

Also, are you setting VK_LAYER_PATH to that of the validation layers? Cause otherwise the loader is finding the layer manifest in the system paths and may be using the system validation layer instead of the local build.

**Comment by psionic12** [comment]
I didn't use VK_LAYER_PATH but I think I use the layers which is built from the source code, because when I checkout the code to a stable tag, the program no longer hangs.

As for the 

> Can you get the stack trace from inside of `vkNegotiateLoaderLayerInterfaceVersion`?

Since I just checkout the code to a stable tag, it takes times to checkout back and build, I'll update the issue ASAP.

**Comment by charles-lunarg** [comment]
I'd really like you to be sure you aren't using the wrong binary. I can tell you that the system installed packages locate the layer binaries differently than local builds (relative path vs no path). I'm not 100% sure LD_LIBRARY_PATH will correctly load the locally built library due to using the default search paths. You'll note that the documentation for this project says to use VK_LAYER_PATH rather than LD_LIBRARY_PATH for that reason (among others).



FYI LD_DEBUG (dynamic linker debug environment variable) is a great way to see exactly what is being loaded, what symbols are being linked, etc etc.

**Comment by charles-lunarg** [comment]
Apologies for doubting the original issue creator, as dynamic linking is complicated at the best of times. 

The issue indeed appears to be `vkGetInstanceProcAddr` is taken from the Vulkan-Loader instead of the Validation Layers, causing the weird crashes you are seeing.

The underlying problem is that the validation layers "links" to vkGetInstanceProcAddr, when it should just use `vulkan_layer_chassis::GetInstanceProcAddr`.

I will make a PR for this shortly.

**Comment by charles-lunarg** [comment]
@psionic12 Can you report your exact linker version?

I cannot reproduce it locally, but am curious if its linker version dependent.
```bash
/usr/bin/ld --version
GNU ld (GNU Binutils for Ubuntu) 2.41
```

A colleague of mine does have the same issue, and is using a different linker version than I am
`/usr/bin/ld:  GNU ld version 2.39-16.fc38`

**Comment by psionic12** [comment]
@charles-lunarg here's the result of `ldd --version`:
ldd (Ubuntu GLIBC 2.35-0ubuntu3.4) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
