### ISSUE TITLE
ValidateLayer crash when index 0 is missing a location assignment in as shader

### ISSUE THREAD

**Issue by psionic12** [KhronosGroup/Vulkan-ValidationLayers#6928]
I have a Vulkan example which may have some ill-formed grammar in shaders:
```
VUID-VkShaderModuleCreateInfo-pCode-08737(ERROR / SPEC): msgNum: -1520283006 - Validation Error: [ VUID-VkShaderModuleCreateInfo-pCode-08737 ] | MessageID = 0xa5625282 | vkCreateShaderModule(): pCreateInfo->pCode is not valid SPIR-V: [VUID-StandaloneSpirv-Location-04919] Member index 0 is missing a location assignment
  %IO = OpTypeStruct %v4float
. The Vulkan spec states: If pCode is a pointer to SPIR-V code, pCode must adhere to the validation rules described by the Validation Rules within a Module section of the SPIR-V Environment appendix (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkShaderModuleCreateInfo-pCode-08737)
    Objects: 0
terminate called after throwing an instance of 'std::out_of_range'
  what():  key not found

```

I'm not sure the termination here is intended. Should validate layers terminate a target program even though the program itself can run without problem?

**Comment by spencer-lunarg** [comment]
> Should validate layers terminate a target program even though the program itself can run without problem?

So the SPIR-V is not valid (as it fails `spirv-val`) and while it might work for your device, it is still [undefined behavior](https://raphlinus.github.io/programming/rust/2018/08/17/undefined-behavior.html) and might crash another driver's compiler stack

The issue is we do a lot with the incoming SPIR-V for runtime spirv validation that needs to assume the SPIR-V is at least statically valid (otherwise we are re-writing `spirv-val` logic in the Validation Layers)

The chassis is designed to return `VK_ERROR_VALIDATION_FAILED_EXT` for `vkCreateShaderModule` if this happens... I guess not really sure how else to handle invalid SPIR-V
