### ISSUE TITLE
possible false positive with VUID-VkSwapchainPresentModesCreateInfoEXT-pPresentModes-07763 when not requesting VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME

### ISSUE THREAD

**Issue by AlexRouSg** [KhronosGroup/Vulkan-ValidationLayers#7294]
**Environment:**
 - OS:  OS: Windows 10
 - GPU and driver version: NVIDIA GTX 1080 ti with 546.33
 - SDK or header version if building from repo: 1.3.268.0
 - Options enabled (synchronization, best practices, etc.): Standard validation + Sync

**Describe the Issue**
 When passing `VkSwapchainPresentModesCreateInfoEXT` to `VkSwapchainCreateInfoKHR`, even if `pPresentModes` is literally the pointer to `VkSwapchainCreateInfoKHR.presentMode` this VUID triggers, The moment I request/enable VK_KHR_GET_SURFACE_CAPABILITIES_2_EXTENSION_NAME this VUID disappears.

**Expected behavior**

This VUID does not trigger.

**Valid Usage ID**
 VUID-VkSwapchainPresentModesCreateInfoEXT-pPresentModes-07763

**Comment by spencer-lunarg** [comment]
- `VkSwapchainPresentModesCreateInfoEXT` is part of `VK_EXT_swapchain_maintenance1`
- `VK_EXT_swapchain_maintenance1` requires `VK_EXT_surface_maintenance1`
- `VK_EXT_surface_maintenance1` requires `VK_KHR_get_surface_capabilities2`

so I guess I would assume you would have got an error at `vkCreateDevice` for not having the all the extensions enables needed

The `07763` VU logic will use `vkGetPhysicalDeviceSurfacePresentModesKHR` if called, otherwise it does call `vkGetPhysicalDeviceSurfaceCapabilities2KHR` for you and not enabling the extension might be the reason it is returning no valid present modes

**Comment by AlexRouSg** [comment]
> VK_EXT_surface_maintenance1 requires VK_KHR_get_surface_capabilities2
somehow I've missed that, my bad

tho I didn't get any errors or warnings about it, so maybe repurpose the issue to be about that?

**Comment by spencer-lunarg** [comment]
> tho I didn't get any errors or warnings about it, so maybe repurpose the issue to be about that?

ya, I will get a test to confirm all of this... something seems wrong here regardless and deserves someone to look at it, thanks for the report
