### ISSUE TITLE
Meaning of the "seq_no"

### ISSUE THREAD

**Issue by OnePride** [KhronosGroup/Vulkan-ValidationLayers#7417]
What is it?

https://www.lunarg.com/wp-content/uploads/2024/01/Guide-to-Vulkan-Synchronization-Validation-FINAL-01-18-2024.pdf

This paper says that it is just "The zero based index of command within the command buffer it is
recorded within", but it looks like not all 'commands' are treated as commands. Where can I find the list of all commands that increment the seq_no in the messages?

**Comment by artem-lunarg** [comment]
In general, the commands that can make memory accesses are tagged. My feeling that for complex applications usefulness of seq_no is limited because it's non-trivial to map it to the exact command from the stream, but it still can be used to estimate region where the command is located. In the source code the tagged commands use `NextCommandTag` or `NextIndexedCommandTag` to generate ids, that's how you can determine if specific command generates seq_no.

@jzulauf-lunarg might know about details or have additional insights.

**Comment by OnePride** [comment]
Thanks for answer! The conditional breakpoint (command_number_ == 42) in CommandBufferAccessContext::NextCommandTag(...) does the job. 

An ideal solution would be to allow the user to set seq_no, reset_no and command buffer's debug name somewhere in Vulkan Configurator to get a debug break and make the debugging experience more effective.

**Comment by artem-lunarg** [comment]
@OnePride Check this: https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/6904
