### ISSUE TITLE
make tests resilient against VK_ERROR_DEVICE_LOST and VK_ERROR_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by lunarpapillo** [KhronosGroup/Vulkan-ValidationLayers#7526]
We occasionally see issues when running `vk_layer_validation_tests.exe` where a test has failed due to `VK_ERROR_DEVICE_LOST` or `VK_ERROR_INITIALIZATION_FAILED`.  The conditions for such are not well understood, but may be related to (possibly unrelated) GPU TDR recovery, and/or other Vulkan processes running on the system.

Making the tests resilient against these errors, to detect them, wait a brief time (to give the GPU a chance to recover), and re-attempting the test, would make CI testing more reliable.

**Comment by lunarpapillo** [comment]
We're showing a lot of random failures on `tcubumes5` and `tcubumes6` tonight involving `VK_ERROR_DEVICE_LOST`, that seem to disappear when only one test process is running at a time.

Is it possible that some VVL test cases are deliberately provoking a `DEVICE_LOST`, and that Windows drivers can keep the consequences of the event isolated to just the provoking process, but **Linux-Mesa** drivers might trigger a `DEVICE_LOST` for all processes that had acquired the device (causing all other test processes on the system to fail)?

I'd like someone to investigate.  If this turns out to be the case, we may have to use other mechanisms to ensure that multiple tests aren't running on a system at a time.  (Unfortunately, if this is the case, throughput will be affected.)

**Comment by spencer-lunarg** [comment]
So looking into this, the issue is even if I checked and caught a `DEVICE_LOST` in a test, I don't know what you would want it to do

The test itself can't just "run itself again" otherwise you would be in scope to have infinite recursion 

> Is it possible that some VVL test cases are deliberately provoking a DEVICE_LOST

At some level, yes, every test for Validation is something that is "invalid" and could possibly cause a device lost... if the layer code is working correctly, it would catch it and prevent it from running on the device

> causing all other test processes on the system to fail

So when there is a "Device Lost" it can be 1 of 2 types

1. The device context failed and it will only effect the current tests
2. The physical device failed and it might need a full reboot (and is probably the reason other tests fails)
