### ISSUE TITLE
Test crashes/failures for Radeon RX 6800 XT (RADV NAVI21) on Ubuntu 22.04 using Mesa 23.2.1 driver

### ISSUE THREAD

**Issue by johnzupin** [KhronosGroup/Vulkan-ValidationLayers#7549]
On Ubuntu 22.04 using the Mesa 23.2.1 radv driver, and running on a Radeon RX 6800 XT GPU, the following tests crash/fail. This was seen on VVL version `v1.3.278-16-g55b36b7f0`.

Crashes:

- `PositiveGraphicsLibrary.PushConstant`
- `PositiveGraphicsLibrary.PushConstantOneLibrary`
- `PositiveRayTracing.StridedDeviceAddressRegion`
- `PositiveRayTracing.BasicTraceRays`
- `PositiveRayTracing.BasicTraceRaysMultipleStages`
- `PositiveRayTracing.DynamicTminTmax`
- `PositiveRayTracing.BasicTraceRaysDynamicRayFlags`
- `PositiveRayTracing.DynamicRayFlagsSkipTriangle`
- `NegativeWsi.SwapchainPresentModeInfoImplicit`
- `PositiveWsi.CreateSwapchainWithPresentModeInfo`

Fails:

- `PositiveDescriptors.CopyAccelerationStructureMutableDescriptors`
- `PositiveRayTracing.ScratchBufferCorrectAddressSpaceOpBuild`

This can be replicated on  the LunarG's `tcubumes5` and `tcubumes6` CI nodes.

**Comment by spencer-lunarg** [comment]
So I looked into this, there was a combination of bad tests and things there were fixed in the 24 Mesa driver

https://gitlab.freedesktop.org/mesa/mesa/-/issues/10663
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7571
https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7568

The only thing left is `PositiveGraphicsLibrary` which are our fault, there is a no VU for GPL I will be adding that will fix those, in the mean time, closing as I now have a Linux RADV driver I am running the test suite on and fixing these

(hopefully by the time we update this driver it will be empty next time we do this exercise)
