### ISSUE TITLE
Cannot find `spirv-opt`, needed to run `generate_spirv.py`

### ISSUE THREAD

**Issue by arno-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7594]
`spirv-opt` (the exe) is not built/downloaded in the dependency processing step, but is required to run `generate_spirv.py`

**Comment by jeremyg-lunarg** [comment]
Remove this from known_good.json:
`                "-DSPIRV_SKIP_EXECUTABLES=ON"`

**Comment by spencer-lunarg** [comment]
I agree it would be nice to make sure everyone is using the "same" `spirv-opt`

I am 99% sure what happen is someone added `DSPIRV_SKIP_EXECUTABLES` because was set because it wasn't be used by anyone

I had an old version in that path so when I added `spirv-opt` to `generate_spirv.py` it worked for me... so yes, happy to have it back for everyone
