### ISSUE TITLE
gpu-av: move instrumentation from CreateShaderModule() to CreateGraphicsPipelines()

### ISSUE THREAD

**Issue by jeremyg-lunarg** [KhronosGroup/Vulkan-ValidationLayers#7804]
The time it takes to instrument shaders is often a bottleneck, especially when the instrumented shaders are not cached by VVL or any drive-specific caches.  It might be possible to reduce this overhead by not instrumenting until vkCreateGraphicsPipelines() is called.

**Comment by ncesario-lunarg** [comment]
IIRC, the problem with this is that we must (?) pass down the instrumented shader code at `vkCreateShaderModule` time or when creating a non-executable GPL (Graphics Pipeline Library). I suppose we could do something like intercept a `vkCreateShaderModule` and effectively turn it into a no-op, delaying dispatch to the driver until CGP time, but that seems like a nightmare to track, and would probably have to be an opt-in feature at best.

**Comment by spencer-lunarg** [comment]
ya, as Nate said, the issue is the driver can save the `VkShaderModule`, so if we did it at Pipeline Creation time, we would have to create a new `VkShaderModule` and then map/manage the handles which seems not fun

> The time it takes to instrument shaders is often a bottleneck

Is this possibly just an issue with my implementation of the shader instrumentation, I know there is possible performance issue depending on the nature of the SPIR-V (having lots a `OpLoad`/`OpStore` in a certain order)

Do you have specific SPIR-V files that are slow, I can look into it... also regradless, I have the `tests/spirv/instrumentation.exe` that can run things one at a time, I could take any trace, dump the SPIR-V, and run this over them and get a baseline of how much time we are spending on instrumentation by itself

**Comment by jeremyg-lunarg** [comment]
> Do you have specific SPIR-V files that are slow, I can look into it...

I think it is the sheer number of shaders some games load. CS2 takes so long to load when our shader cache is empty that I switch to a different computer and come back a few hours later.

**Comment by danginsburg** [comment]
> Right, I think in the CS2 case (or maybe it was a different Source title @danginsburg?), 

Yes, the ratio of pipeline libraries to full PSOs in CS2 just going to the main menu is 6166:348 or ~18:1.  I'd therefore expect somewhere around an 18x startup speedup if you deferred instrumentation until full PSO link.

**Comment by spencer-lunarg** [comment]
so took some profiling snapshots, it seems that all the time spent in `vkCreateShaderModule` is actually running `spirv-val` 

for large shaders, it can make 30k to 100k small allocations which becomes a death-by-thousand cuts

I small workaround may be to have a dedicated env to disable `spirv-val` on runs. With the exception of maybe applying spec constants, I assume the hlsl/glsl/slang generated code is going to almost always be valid static SPIR-V
