### ISSUE TITLE
SyncVal: should report VkCmdSetEvent call on an already signaled event

### ISSUE THREAD

**Issue by cclao** [KhronosGroup/Vulkan-ValidationLayers#8004]
**Environment:**
 - OS: Linux
 - GPU and driver version: Nvidia

**Describe the Issue**
This is discovered while working on ANGLE using VkEvent. 

With the following call sequence on the same VkEvent:

created, 
VkCmdSetEvent, 
VkCmdWaitEevent,
// Wait for command to finish, or not
VkCmdSetEvent, 

SInce the second setEvent will be called on an already signaled event, the call will be ignored. This is not a good use case. VVL should report it. For example, ANGLE is recycling VKEvent. So the second setEvent call was issued because VkEvent was recycled from an internal event pool. We apparebtly missed a ResetEvent call, so there is a bug. But VVL does not complain in this kind of bad usage.

**Comment by AlbinBernhardssonARM** [comment]
For reference, calling vkCmdSetEvent on an already signaled event is valid according to the spec but probably not intended behavior by the developer (I have a hard time thinking of use cases for intentionally doing this).

**Comment by artem-lunarg** [comment]
I agree with @AlbinBernhardssonARM this is allowed by the spec so probably not an issue.

> If event is already in the signaled state when [vkCmdSetEvent2](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#vkCmdSetEvent2) is executed on the device, then [vkCmdSetEvent2](https://registry.khronos.org/vulkan/specs/1.3-extensions/html/vkspec.html#vkCmdSetEvent2) has no effect, no event signal operation occurs, and no dependency is generated.

One example to show it can be useful, not necessarily it's likely. The application has two optional code paths and when active the pass sets and event. Each code path does not have an easy way to check if the other one is active or not. The solution is that each code path just sets an event without checking if the second one is active and the event was already set. In this example it might simplify design by minimizing dependencies.

**Comment by cclao** [comment]
Agree that this is not out of spec. But this is dangerous practice and could easily introduce a bug that very hard to detect and debug. That is why I think SyncVal will be useful here.

**Comment by artem-lunarg** [comment]
One remark I'd like to make is that this functionality is not part of SyncVal, but is a Core validation. SyncVal checks runtime race conditions and core validation if API is used correctly. Yeah, currently we have some pieces of Event code in SyncVal module that should be moved to Core, and that might be confusing when inspecting the code.

But I don't agree that Core validation should complain about this since it's valid use case.  Setting an event is a state update and in some regard this can be similar, for example, to updating current viewport, you can duplicate a call and it's not an error. 

In some cases when not resetting an event leads to a situation that subsequent vulkan code violates the spec then the error will be reported for that code. One example is provided in this issue https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/7970 and it triggered validation error. But this probably depends on specific scenario.

**Comment by artem-lunarg** [comment]
One potential place to check that `vkCmdResetEvent` was called before `vkCmdSetEvent` is in the best practices validation, in case that's what the most applications do.

**Comment by cclao** [comment]
Right, best practices validation sounds a better place.
