### ISSUE TITLE
vkCreateInstance validation does not seem to work

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-ValidationLayers#811]
The validation of vkCreateInstance (and vkDestroyInstance) does not seem to work.

Even if the check is implemented it fails to be reported.

There might be some Loader bug to this too. E.g. `vkCreateInstance(&info, nullptr, nullptr)` crashes.

See PR #810 for failing tests.

#658 Seem related. It seem to report the undestroyed device to me, but with wrong VUID.

**Comment by lenny-lunarg** [comment]
This isn't a bug. The basic problem with passing a null instance is that the loader has to create the instance before it calls into any layers. And since you've given a null pointer for the instance handle, the loader is unable to write the information to the struct. This also means that validation can't really do anything in `vkCreateInstance` because the instance has already been created by the time the layer is called.

We do not want to add validation to the loader. Half of the point of Vulkan is that it eliminates a lot of the runtime error checking in favor of improved performance. The layers implement validation, but they can be removed for performance. The loader cannot be removed. While it would be possible to enable/disable loader validation, we believe mixing validation and the loader would create more problems than it would solve.

I'll also add that a null pointer crash is generally a pretty easy case to debug. If someone can't figure out how to prevent a null pointer from being passed, they probably shouldn't be using Vulkan.

And finally, this is a consistent pattern in the loader. Try calling `vkEnumerateInstanceVersion(nullptr)` and see what happens. You'll get another crash.

**Comment by krOoze** [comment]
> And since you've given a null pointer for the instance handle, the loader is unable to write the information to the struct.

Not clear how this would be a show stopper. It is only a return variable. The loader can still have any structs it wants, assuming it does not rely on validity of the `pInstance` parameter in the trampoline part (which it does not need to AFAICT).

> This also means that validation can't really do anything in vkCreateInstance because the instance has already been created by the time the layer is called.

Actually, I would expect layers to be called first. That's their job. Naively speaking, Loader should only do the minimum before layers, and do the heavy lifting only in the terminator (after Layers, and when the "true" arguments are known).

>We do not want to add validation to the loader. Half of the point of Vulkan is that it eliminates a lot of the runtime error checking in favor of improved performance.

Hm. I did not said there should be validation in the Loader. Although now that you bring it up, `vkCreateInstance` is not really a hotspot. If it is fundamentally unvalidatable by layers, we should perhaps return an `VK_ERROR_*` instead. Typical `vkCreateInstance` call takes up to 100 ms. Check for the few simple VUs there would take what; nanoseconds?

> I'll also add that a null pointer crash is generally a pretty easy case to debug. If someone can't figure out how to prevent a null pointer from being passed, they probably shouldn't be using Vulkan.

Sure. It is a matter of image. This might be the first thing a new dev might try to break on purpose to test the layers. If it does not work to report error, it signals Vulkan can't even validate one simple `nullptr` on the most frequently used commands...

And I mean, all of the `vkCreateInstance` Validation Checks do not seem to work. Not just this particular one...

> And finally, this is a consistent pattern in the loader. Try calling vkEnumerateInstanceVersion(nullptr) and see what happens. You'll get another crash.

`vkEnumerateInstanceVersion` does not have a Validation layers and debug report callback. `vkCreateInstance` does. You can specifically link `VkDebugReportCallbackCreateInfoEXT` to `pNext` in order for this to be possible.

**Comment by krOoze** [comment]
Anyway.
It should be made to work as expected, if it is feasable and practical.
Or it should be documented it doesn't work. Notably in spec which says the `pNext` debug reporter does cover events from `vkCreateInstance` execution.

**Comment by mark-lunarg** [comment]
@krOoze, we can add support for the `pNext `debug reporters in the layers.  Some limited support for this was present before the layer reorg, but now we can do a cleaner, more comprehensive implementation in the chassis.  We'll make this in 'incomplete', just as if it were missing validation checks.
