### ISSUE TITLE
Crash in VkLayerTest.GpuValidationArrayOOB

### ISSUE THREAD

**Issue by asuonpaa** [KhronosGroup/Vulkan-ValidationLayers#815]
I'm seeing a crash inside RADV driver when running this test.

**Comment by asuonpaa** [comment]
The driver is crashing during pipeline creation, and it only happens if the vertex shader has this line:

`gl_Position += 1e-30 * texture(tex[uniform_index_buffer.tex_index[0]], vec2(0, 0));`

Disabling the GPU validation still gives the same crash, which happens in libvulkan_radeon.so.

Also, the fragment shader tests which should have debug data included complains about not having OpLines.

**Comment by Tony-LunarG** [comment]
The driver is segmentation faulting because the call to spirv_to_nir is failing to compile the shader.  Changing the line in question to 
```
gl_Position += 1e-30 * texture(tex[0], vec2(0, 0));
```
causes the shader to compile successfully.  I ran the test on the same system running Windows and the shader compiles and the tests pass. The shader is run through shader validation with no errors.  There is something about using a variable to index into a descriptor array that is causing the RADV driver to fail to compile the shader.  The driver itself claims to support the descriptor_indexing extension which is even more extensive in it's allowance of descriptor array indexing, but enabling the extension did not fix the problem.  Initial diagnosis is there seems to be a problem with the RADV driver.

I did not see complaints about missing OpLines running the two fragment shader tests using today's master.

**Comment by Tony-LunarG** [comment]
Looking more closely, this appears to be a problem with the instrumented shader used by GPU assisted validation.  I do not see the issue with GPU assisted validation disabled.  I've filed an issue with SPRIV-Tools:
https://github.com/KhronosGroup/SPIRV-Tools/issues/2572

**Comment by Tony-LunarG** [comment]
Latest glslang brings in the fixed spirv-tools that fixes this issue
