### ISSUE TITLE
Doesn't catch VK_STRUCTURE_TYPE_EXPORT_MEMORY_WIN32_HANDLE_INFO_KHR on VkImportMemoryWin32HandleInfoKHR

### ISSUE THREAD

**Issue by rygo6** [KhronosGroup/Vulkan-ValidationLayers#8409]
Minor bug but it drove me crazy for an entire day.

If you put VK_STRUCTURE_TYPE_EXPORT_MEMORY_WIN32_HANDLE_INFO_KHR on VkImportMemoryWin32HandleInfoKHR and use it to import an image, validation will not report an error. Instead, your imported image just appears black.

I was looking at the source code and it looks like VkMemoryAllocateInfo doesn't check the specific sType on a specific struct for anything added via pNext? Instead, it has an array of multiple allowed sTypes for VkMemoryAllocateInfo and if any struct added via pNext is in that array, it passes validation, even if it is not the correct sType for the struct. 

Can this even be validated? Or is this some limitation of validation layers and you cannot check that the sType matches the struct type on pNext's?

If it is some limitation, I wish that was noted somewhere! If you have some incomprehensible bug, check all the sTypes on your pNext's because validation doesn't check them!

**Comment by spencer-lunarg** [comment]
So the `sType` is the only way a tool such as Validation (or even the driver) can guess what the `pNext` chained struct is

I guess the only thing I could see is since you used the `Export` struct sType, all the validation would have been on that, it was unlucky that `VUID-VkMemoryAllocateInfo-pNext-pNext` allows both the import and export

 > Can this even be validated? 
 
 This would really require some compile time check in your C++ compiler (or any wrapper language) to detect which struct name you have matches the sType, but the layers only see a `void* pNext` and use the sType to know what the data in it is
 
 > If it is some limitation, I wish that was noted somewhere!
 
 I guess my question is here is where would have looked, somewhere like https://github.com/KhronosGroup/Vulkan-Guide/blob/main/chapters/pnext_and_stype.adoc, somewhere in the spec? There are other limitation like this due to the fact that Validation is a layer and not a source code compile time checker

**Comment by rygo6** [comment]
> I guess my question is here is where would have looked

Hm, that is a good question.

Someone once said, "One does not learn Vulkan. Rather through years of pain and struggle it simply becomes imbued in your muscle memory like a kind of trauma." 

This might be one of those things.

Me personally, some bold red text in the list of checkboxes in the Vulkan Configurator which said "Things Validation Cannot Check" would have got my attention.

Or maybe a section in the main readme on this repo.

**Comment by spencer-lunarg** [comment]
> Or maybe a section in the main readme on this repo.

Ok, this is a very reasonable ask, I can get something written up soon
