### ISSUE TITLE
GPU-AV Shader caching: Account for driver version

### ISSUE THREAD

**Issue by arno-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8415]
Delete cache if driver version has changed

**Comment by spencer-lunarg** [comment]
Also need to account for the instrumentation passes that are done

if you have 2 shaders that are the same input, but the first is only using `--buffer-device-address` pass, and the second only uses `--bindless-descriptor` pass, it will be cached from the first one and produce the incorrect output

**Comment by spencer-lunarg** [comment]
^ Nvm - I forgot this was already done in https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8021

**Comment by spencer-lunarg** [comment]
@arno-lunarg this actually makes no sense why we would do this

the GPU-AV shader cache just decides skips running the shader instrumentation code or not, but the final SPIR-V is still the same regardless... what is the goal of deleting this cache if the driver changes, the output SPIR-V we send down will look **the same** to the driver and deleting the cache with a new driver version will have zero effect

I think this was created because of the bug that was fixed in our caching (in #8416)

**Comment by arno-lunarg** [comment]
Ah yes exactly
