### ISSUE TITLE
Issue with VUID 06409

### ISSUE THREAD

**Issue by ziga-lunarg** [KhronosGroup/Vulkan-ValidationLayers#8423]
On android I am receiving this error:

`VUID-VkBufferCreateInfo-size-06409(ERROR / SPEC): msgNum: -332260500 - Validation Error: [ VUID-VkBufferCreateInfo-size-06409 ] | MessageID = 0xec321b6c | vkCreateBuffer(): pCreateInfo->size (4653056) is larger than the maximum allowed buffer size VkPhysicalDeviceMaintenance4Properties.maxBufferSize (0). The Vulkan spec states: size must be less than or equal to VkPhysicalDeviceMaintenance4Properties::maxBufferSize (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkBufferCreateInfo-size-06409)`

`VkPhysicalDeviceMaintenance4Properties.maxBufferSize` is reported being `0`, but vulkaninfo says it should be `7537405952`.

This might be due to `VK_KHR_maintenance4` being promoted to 1.3 and validation layers only checking `VkPhysicalDeviceMaintenance4PropertiesKHR` and not `VkPhysicalDeviceVulkan13Properties`.

**Comment by spencer-lunarg** [comment]
I see what is happening, if you search `shaderSignedZeroInfNanPreserveFloat64` in `ValidationStateTracker::PostCreateDevice` you will see we funnel all the extension properties into the `VkPhysicalDeviceVulkan12Properties` so that we only use `VkPhysicalDeviceVulkan12Properties` everywhere

... we have completely forgot to do that for `VkPhysicalDeviceVulkan13Properties` ... seems this `maxBufferSize` is the only thing used and why no one didn't really notice, but yes good catch @ziga-lunarg !! Let me fix this
