### ISSUE TITLE
DebugPrintf not working in Raygen shader (works in other stages)

### ISSUE THREAD

**Issue by danginsburg** [KhronosGroup/Vulkan-ValidationLayers#8562]
**Environment:**
 - OS: Windows 10
 - GPU and driver version: GTX 2080 553.00
 - SDK or header version if building from repo: 1.3.290
 - Options enabled (synchronization, best practices, etc.): shader debug printf

**Describe the Issue**

I put a DebugPrintf in a raygen shader and am not getting any output from validation layers.  I'm able to get debug messages from printf's in a compute shader.  When I debug it in validation I am hitting this internal error: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/e433331f18bc9b5b0e7484fd60f14923d10a3b5c/layers/gpu/debug_printf/debug_printf.cpp#L243

**Expected behavior**

It should print the messages from RTX shaders as it does from other stages.

**Comment by spencer-lunarg** [comment]
added a quick test here https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8568 so seems it "works" when used with basic use cases (which is good!) but we have zero test coverage and adding tests for DebugPrintf will indirectly also improve our GPU-AV coverage (now that they are sharing code paths)

handing over to @arno-lunarg to add more tests (since he in charge of Ray Tracing test framework). We should add DebugPrintf checks where
- [ ] We make sure we can do a basic print in the various other stages as well
  - [ ] Miss
  - [ ] Any Hit
  - [ ] Closest Hit
  - [ ] Intersection
  - [ ] Callable
- [ ] Adjust the binding tables to try and fool the layers (aka, the issue above shows we see the output buffer written, but can't back track to the VkShaderModule`)
- [ ] Currently RTX test framework builds each shader stage as its own VkShaderModule, but HLSL/Slang support multi-entrypoint shaders

@danginsburg if there are any other variation of RTX you use that you think we should add to the test plan comment here

**Comment by danginsburg** [comment]
> added a quick test here https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8568 so seems it "works" when used with basic use cases (which is good!) but we have zero test coverage and adding tests for DebugPrintf will indirectly also improve our GPU-AV coverage (now that they are sharing code paths)

Interesting, I wasn't getting any messages out of a raygen shader, I'm not sure what was different in our case but I can provide a gfxrecon capture privately if it's helpful.

> @danginsburg if there are any other variation of RTX you use that you think we should add to the test plan comment here

That looks like the right set of stages.  It would be good to also verify that it works with inline raytracing (i.e. ray query dispatched from pixel/compute shader) and bonus points for indirect dispatches ;)

**Comment by spencer-lunarg** [comment]
>  but I can provide a gfxrecon capture privately if it's helpful.

now that I have a similar machine, I probably can actually replay it if you can provide me the trace offline

> inline raytracing

We have a test for Ray Query already, that is simple as that is just a normal graphics/compute flow from the Vulkan point of view

> indirect dispatches 

I like bonus points!

**Comment by arno-lunarg** [comment]
@danginsburg to confirm: the lack of message is probably coming from the lack of support for deferred ray tracing pipeline creation in GFXR?
If running hammer directly with debug printf, can you see the messages?

So far the tests I have added for debug printf + RT are correctly printing messages. To be exhaustive, I still need tests with any hit and callable shaders, and maybe play with the `stride` member of shader binding tables, but if the problem is in VVL, I would have expected to see it by now

**Comment by danginsburg** [comment]
> If running hammer directly with debug printf, can you see the messages?

I was not seeing them at the time I tested this directly from Hammer, no.  I only tried to use gfxr so I could give you a repro case.  I can try again with latest main if it's helpful.

**Comment by arno-lunarg** [comment]
Ok, in the meantime I did find some issues in printf (some missing messages, hopefully root cause is the same as in your case)
I will also have a look at some ray tracing samples that I can modify (https://github.com/nvpro-samples/vk_mini_samples/ and https://github.com/KhronosGroup/Vulkan-Samples) to see how things go there
