### ISSUE TITLE
VkSwapchainPresentModesCreateInfoEXT with swapchain recreation produces wrong message

### ISSUE THREAD

**Issue by Agrael1** [KhronosGroup/Vulkan-ValidationLayers#8772]
**Environment:**
 - OS: Windows 11
 - GPU and driver version: NVidia A4000, 560.x
 - SDK or header version if building from repo: 1.3.296
 - Options enabled (synchronization, best practices, etc.): yes

**Describe the Issue**

I had created the swapchain with `VkSwapchainPresentModesCreateInfoEXT` initially, but on resize I forgot to add the same pNext and got weird error:
```
[Validation layer]: VUID-VkSwapchainCreateInfoKHR-pNext-07781
 [Message]:Validation Error: [ VUID-VkSwapchainCreateInfoKHR-pNext-07781 ] | MessageID = 0x4c8929c1 | vkCreateSwapchainKHR(): pCreateInfo->imageExtent (width = 2560, height = 1349), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (width = 1920, height = 1080), minImageExtent = (width = 1920, height = 1080), maxImageExtent = (width = 1920, height = 1080).
The Vulkan spec states: If a VkSwapchainPresentScalingCreateInfoEXT structure was not included in the pNext chain, or it is included and VkSwapchainPresentScalingCreateInfoEXT::scalingBehavior is zero then imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://vulkan.lunarg.com/doc/view/1.3.296.0/windows/1.3-extensions/vkspec.html#VUID-VkSwapchainCreateInfoKHR-pNext-07781)
```
although the resize code contains `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` and returned size is correct.

**Expected behavior**

A message stating that I have forgot to include the same pnexts or nothing.

**Comment by artem-lunarg** [comment]
> A message stating that I have forgot to include the same pnexts or nothing.

@Agrael1 validation layer probably can't use previous behavior to make suggestion about API use, it validates API usage only based on specification. 

As I understand there first part of the message is problematic:
> pCreateInfo->imageExtent (width = 2560, height = 1349), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (width = 1920, height = 1080), minImageExtent = (width = 1920, height = 1080), maxImageExtent = (width = 1920, height = 1080).

Does the message report `pCreateInfo->imageExtent (width = 2560, height = 1349` incorrectly compared to what you get from `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` ?

**Comment by artem-lunarg** [comment]
One suggestion is to enable Thread Safety checks (for example in vkconfig) to check there is no threading errors (in theory it can affect caching we use to store surface queries).

**Comment by Agrael1** [comment]
> Does the message report `pCreateInfo->imageExtent (width = 2560, height = 1349` incorrectly compared to what you get from `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` ?

Yes, I get correct extents, but they are reported as incorrect:
![image](https://github.com/user-attachments/assets/754521d1-357a-4f6d-998b-3d9ef7be422c)

There is no multithreading in my app, it is a basic example.

**Comment by artem-lunarg** [comment]
@Agrael1 if it’s a small program do you have an opportunity to provide source code, we can then quickly analyze it? There is an option to use LunarG sharing portal, the shared material won’t be publicly visible. If this is an option we can send the invitation on your preferred email.

**Comment by Agrael1** [comment]
well, if you can download [Wisdom](https://github.com/Agrael1/Wisdom/tree/fix/swapchain_instability) there is branch `fix/swapchain_instability`. The CMake config should either be preset x64-debug-vk from CMakePresets or just add `-DWISDOM_FORCE_VULKAN`. 

The example of interest is Example.exe. Its location is examples/platform/shared. If you just resize the window, the message will pop up. 

Otherwise I could try to make smaller example, yet it will still download Wisdom.

Code of swapchain creation is [here](https://github.com/Agrael1/Wisdom/blob/fix/swapchain_instability/wisdom/include/wisdom/vulkan/impl/vk_device.cpp#L924)

and recreation is [here](https://github.com/Agrael1/Wisdom/blob/fix/swapchain_instability/wisdom/include/wisdom/vulkan/impl/vk_swapchain.cpp#L284)

**Comment by artem-lunarg** [comment]
@Agrael1 thanks, that's great. I will work with this.

**Comment by artem-lunarg** [comment]
Can reproduce the validation error with nvidia gpu. No errors when run on amd.

**Comment by Agrael1** [comment]
Can you also see the stutters of the triangle? If so, the Swapchain maintenance on NVidia is not working correctly and should be reported to NVidia.

**Comment by Agrael1** [comment]
Also, IIRC AMD may not have swapchain maintenance implemented, the code I provided would just skip the creation of dynamic vsync altogether

**Comment by artem-lunarg** [comment]
Yes, on amd it's probably because of extension support. 
I can see the issue in our code, already reproduced in the internal test, working on the fix.

**Comment by gabezal** [comment]
I can still reproduce this vulkan-sdk-1.4.304.1. Has the fix been released yet?

The symptoms are exactly the same: only reproduceable on a discrete NVIDIA GPU, but not on integrated AMD. I have Thread Safety enabled in vkConfig and everything else.

For some reason, the validation layer doesn't pick up that I'm calling `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` right before `vkCreateSwapchainKHR`. The error message always seems to show old-by-one values for `VkSurfaceCapabilitiesKHR`. Although, if I call `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` twice or more times, it doesn't fix the problem, so there must be some other point in time where it updates it's internal values that are used for validation during the next `vkCreateSwapchainKHR` call.

The problem seems to be better exemplified in #9034, where they add another call to  `vkGetPhysicalDeviceSurfaceCapabilitiesKHR`, after recreating the swapchain, with a "guessed" future swapchain size, which fixes the problem for them. However, I've tried adding another `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` call at different spots in my code (before and after `vkCreateSwapchainKHR`), without success. And unlike that issue, I am not using any of the swapchain maintenance extensions.

I've also tried adding delays between the different API calls, thinking that this is maybe a thread synchronization/memory access error on the part of the validation layer, but nothing seems to be helping. It feels like the validation layer is using the results of the older `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` call, and always ignoring the latest one, on purpose.

And I'm not 100% sure about this, but I think the problem only started after a recent driver update.

**Comment by artem-lunarg** [comment]
> I can still reproduce this with vulkan-sdk-1.4.304.1. Has the fix been released yet?

@gabezal Yes, the fix is available in 1.4.304.1. The fix is not broken in the latest code.  We have the tests the reproduce that scenario (`PositiveWsi.MixKHRAndKHR2SurfaceCapsQueries`, `PositiveWsi.MixKHRAndKHR2SurfaceCapsQueries2`) that were failing before the fix and after the fix they pass, including the latest public nvidia drivers (on windows it's 572.82).

You might experience an issue with a different scenario. If that looks like a validation false positive I'd recommend to open a separate issue and to describe the steps that lead to the error message or to provide some form of pseudo code (if there is possibility to provide minimal examplle that's ideal). If we can reproduce this then usually it's relatively easy to understand whats going on.

**Comment by gabezal** [comment]
Thanks for looking into it. The latest NVIDIA drivers for my 3060 RTX are 572.83, not 572.82.

> You might experience an issue with a different scenario.

AFAICT, the scenario is exactly the same as described here and in #9034.  I would rather not open a new issue, as there's not any more info I could provide than there's already available in these existing issues.

My code is nothing special, it's just regular tutorial code.

I guess I'll try to rollback the driver tomorrow, to see if the issue goes away. But it would be weird if that were the problem, as it would mean that a Vulkan implementation can do something that affects the outcome of the validation layer.

In the meantime, I've also tried an older version of my code, which I know for a fact didn't reproduce the problem, yet now it does.

**Comment by gabezal** [comment]
Nevermind, it seems that I hada bug in my code. (I was overwriting the `selected_gpu` variable, due to some overflow in an array I was using for push constants). Sorry for the inconvenience.
