### ISSUE TITLE
semaphore errors and asserts with LightweightVK

### ISSUE THREAD

**Issue by spencer-lunarg** [KhronosGroup/Vulkan-ValidationLayers#9009]
If you grab https://github.com/corporateshark/lightweightvk and run `001_HelloTriangle` you will see a flood of `VUID-vkAcquireNextImageKHR-semaphore-01779 ` even though it seems to try and work around this
https://github.com/corporateshark/lightweightvk/blob/master/lvk/vulkan/VulkanClasses.cpp#L1253-L1262

edit - the following has been fixed

I also just noticed that https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/9000 now will have it 
> layers/state_tracker/semaphore_state.cpp:248: bool vvl::Semaphore::CanBinaryBeSignaled() const: Assertion 

after a few frames

**Comment by spencer-lunarg** [comment]
note, pinned down the VUs starting in 9afdbfa354ffe67ec02c88be357925dab1a466ea (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8906)

**Comment by artem-lunarg** [comment]
The reported 01779 is a valid issues, still not sure you'll believe me, it's almost like a detective story. I have to start from the beginning.

If we take a validation layer code from a year ago, lets say Dec 16, 2023: c7cd4d9 - scripts: Cleanup pip usage.
If we run `001_HelloTriangle` with that layer we get our friend `VUID-vkAcquireNextImageKHR-semaphore-01779`.

The same day but few hours later it all started. We had
<img src="https://github.com/user-attachments/assets/d36c6680-8bc8-48d2-8ed2-a0d556abfadf" width=10% height=5%> situation:

 (https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/7145): 9b946da - layers: Retire submissions using acquire fence. If we run `001_HelloTriangle` against this version we find out pretty quickly that our friend 01779 is gone.

The above PR introduces new synchronization method using acquire fence (acquire-fence-sync) and it's not related to what LightweightVK's 001_HelloTriangle does. Unfortunately due to being a human that solution was few steps away from being perfect.

One imperfection is that  `acquire-fence-sync` code path became accidentally active in `001_HelloTriangle` (when WaitForFences is used before AcquireNextImage) which is not a scenario where `acquire-fence-sync` is used. As a side affect it marked semaphore as not in use and that's how we lost our 01779-companion. But... spoiler:
<img src="https://github.com/user-attachments/assets/e8d0a525-5541-458f-a2e9-b8e9f2f541ec" width=15% height=15%>

Over the last year we got older but also discovered few bugs in the `acquire-fence-sync` code path and fixed them. It was around 4 iterations. The last one is https://github.com/KhronosGroup/Vulkan-ValidationLayers/pull/8906. It turns out this PR fixes behavior that `acquire-fence-sync` gets accidentally active in `001_HelloTriangle `. Our 01779-companion is back

<img src="https://github.com/user-attachments/assets/e39044b4-71ba-4889-8c97-33327d9a2cde" width=15% height=15%>

As a side note, I was completely unaware of what LightweightVK does and that my changes at first hid validation error, and then, a year later, presented it again. Those fixes were made based on other reports.

Why in the first place VVL reports 01779 for `001_HelloTriangle `? Thre is this line:
```
 vkWaitForFences(device_, 1, &acquireFence_, VK_TRUE, UINT64_MAX);
```

It ensures that corresponding `acquireSemaphore_` is signaled, but the specification does not guarantee it is unsignaled
(Batch with wait semaphore operation can still be pending. In practice it can be very short period or maybe even no gap on some implementation, still validation has to follow specification. Waiting on the fence from the submission that contains wait semaphore will ensure the semaphore is unsignaled, for example). 

01779 says: ` it must not have any uncompleted signal or wait operations pending`.
During `vkAcquireNextImageKHR` we have guarantee of the first part: `it must not have any uncompleted signal` thanks to the above `vkWaitForFences`. But no guarantee that there is no `wait operations pending`. There are many apporoaches how to avoid this error (different sync methods, buffering of semaphores/resources, etc.), any vulkan sample that runs error free with the latest vvl code can be used as an example.

**Comment by spencer-lunarg** [comment]
cc @corporateshark

**Comment by corporateshark** [comment]
I'm looking at [NVidia's minimalistic Vulkan sample](https://github.com/nvpro-samples/vk_minimal_latest/blob/c504ae02d76efe447360fb38c6138bb3583e9308/src/minimal_latest.cpp#L1221) and I cannot see any acquire-fence there at all.
Am I missing something?

**Comment by artem-lunarg** [comment]
@corporateshark That's intentional. It pretty common that fence is not provided to AcquieNextImage, only semaphore that is waited on by queue submit. Then in order to synchronize you pass synchronization primitive to QueueSubmit and wait for in at the beginning of the next frame (of some future frames in case of double/tripple buffering). This synchronization primitive can be VkFence and many apps to that. With the introduction of timeline semaphores it's possible to signal timeline semaphore from QueueSubmit and do not use fence at all. Then at the beginning of the next frame the program uses vkWaitSemaphores to wait for timeline signal (instead of vkWaitForFences).

**Comment by artem-lunarg** [comment]
My personal sample uses more traditional approach (old school?) with fences where at the beginning of the frame we wait for the fence then this guarantees it's safe to re-use acquire semaphore because it was waited on by the frame associated with the fence: https://github.com/kennyalive/vulkan-base/blob/f1f9fb2562d2eecb2eae8215f9e02ef82c27bbc3/src/vk.cpp#L950

**Comment by artem-lunarg** [comment]
@corporateshark I will close this ticket as not a VVL issue. Feel free to re-open or if you suspect VVL missteps, or if any behavior needs additional clarification we are happy to provide more details.
