### ISSUE TITLE
VK_ERROR_INCOMPATIBLE_DRIVER problem

### ISSUE THREAD

**Issue by Buballs** [KhronosGroup/Vulkan-ValidationLayers#989]
Hi there. I was just trying to play some games on rpcs3. Vulkan opiton didn't show up so i tried to find a solution for it. Whatever i tried didn't work. Whenever i run vulkaninfo.exe it says this:

Cannot create Vulkan instance.
C:\VulkanSDKBuild\workspace\Khronos-Tools\repo\vulkaninfo\vulkaninfo.c:921: failed with VK_ERROR_INCOMPATIBLE_DRIVER

I tried that entry glitch thing -adding the file directory-

I'd be really glad if someone can help me. I have GTX 1060 6G as the GPU

**Comment by mark-lunarg** [comment]
Errors like this are usually related to some kind of driver configuration problem. This particular repository is related to the validation layers -- you might try posting your query (along with some additional hardware information) to the [Vulkan  subreddit](https://www.reddit.com/r/vulkan/), or perhaps looking at the [Vulkan-related posts on the Nvidia subreddit](https://www.reddit.com/r/nvidia/search/?q=Vulkan&restrict_sr=1).  Good luck!

**Comment by mark-lunarg** [comment]
@johnzupin, do you have any more suggestions for resources related to configuration issues?

**Comment by karl-lunarg** [comment]
This situation has been coming up a lot recently.

It might be useful to enhance _this particular_ error message to say a bit more, like "please check that your Vulkan drivers are properly installed and your GPU supports Vulkan" or something similar.  I'll open an issue in Vulkan-Tools to propose this.

**Comment by mark-lunarg** [comment]
@karl-lunarg, it would be really good to have a boilerplate response for these issues, as they show up everywhere, maybe even a troubleshooting page on the website that we could point to.

**Comment by johnzupin** [comment]
Sorry I don't have much to add to this. Maybe try re-installing your driver https://www.nvidia.com/Download/index.aspx?lang=en-us. The subreddits mark posted would be responsive for help.

**Comment by karl-lunarg** [comment]
@mark-lunarg  Right, my point is that `VK_ERROR_INCOMPATIBLE_DRIVER` can _really_ mean that there isn't even a driver installed, it is improperly installed, or is really incompatible.  I think that a one-sentence translation at this particular location has some high ROI.  Response templates for issues are fine, but a hint like this one might avoid the need for someone to file an issue to begin with.

@MarkY-LunarG Yes, I mentioned VIA in the Vulkan-Tools issue.  While it might be OK to suggest running VIA, I hesitate because a Linux user, for example, may have `vulkaninfo` installed via a distro package and may have no idea what VIA is.  To cover that case, you'd have to explain all that in the error message and we don't want the message to turn into a book.

Probably better to continue discussion in https://github.com/KhronosGroup/Vulkan-Tools/issues/207.
